### ISSUE TITLE
Files cannot be found

### ISSUE THREAD

**Issue by rubenCodeforges** [Gbuomprisco/ng2-tag-input#100]
ERROR in ./~/ng2-tag-input/dist/modules/components/icon/icon.js
ERROR in ./~/ng2-tag-input/dist/modules/components/tag-input.js
Cannot resolve 'file' or 'directory' ./tag-input.style.scss
Cannot resolve 'file' or 'directory' ./tag-input.template.html 
Cannot resolve 'file' or 'directory' ./tag-input-form.template.html in

**Comment by rubenCodeforges** [comment]
I think the problem is in package.json a old version is perhaps installed with npm install

**Comment by Gbuomprisco** [comment]
Hi @rubenCodeforges,

Sorry I'll need some more information :) Can you paste the stacktrace returned?

**Comment by henri-ihalainen** [comment]
Check your import in app.module. It should be: import { TagInputModule } from 'ng2-tag-input';

**Comment by rubenCodeforges** [comment]
@henri-ihalainen @Gbuomprisco the problem is that when you execute npm install ng2-tag-input --save
It installs a old version of the module.
The files are different a bit. 
Maybe a issue with npm ?

**Comment by rubenCodeforges** [comment]
@henri-ihalainen i use intellij it does it automaticaly , but even in that case you would get a module not found exception and not a webpack error.

**Comment by henri-ihalainen** [comment]
@rubenCodeforges I also use IntelliJ and that was the problem. It added automatically the wrong import import { TagInputModule } from 'ng2-tag-input/dist/modules/ng2-tag-input.module';

when it should be import { TagInputModule } from 'ng2-tag-input';

That caused me similar kind of error messages

**Comment by rubenCodeforges** [comment]
@henri-ihalainen  you would get a different error .
Ive already explained that the files are different from the repo , looks like old version.
Anyway it can be closed , ive removed the module due to the use of material drop down

**Comment by Gbuomprisco** [comment]
OK, I'll try to republish it on NPM anyway. Thanks :)
