### ISSUE TITLE
how to clear entered text from input?

### ISSUE THREAD

**Issue by sivamamidi-REISys** [Gbuomprisco/ng2-tag-input#104]
We are looking for a way that how to remove text from text input onBlur event.

**Comment by Gbuomprisco** [comment]
HI @sivamamidi-REISys,

There should be a way by registering a reference on the component and reset its form's value. I need to dig in the code and try it out to be sure though. Will let you know.

**Comment by Gbuomprisco** [comment]
Hi @sivamamidi-REISys,

I haven't tried this yet, but it should work: try using the `onBlur` event to be notified when a new item is added.  Reference a local variable for the form you wish to clear and call

```
this.inputForm.value.setValue('');
```

Of course, this wouldn't work if you need to create dynamic forms.

I'll probably be adding a property `clearOnBlur` in the near future

**Comment by Gbuomprisco** [comment]
Hi @sivamamidi-REISys,

This is now possible. Check the input `[clearOnBlur]="true"`
