### ISSUE TITLE
Doesn`t work with server rendering

### ISSUE THREAD

**Issue by MrZaYaC** [Gbuomprisco/ng2-tag-input#105]
`angular/universal` server crashing because of 
```
if(typeof document !== "object") throw new Error("The style-loader cannot be used in a non-browser environment");
```

Perhaps you should make ability to don`t use style-loader

**Comment by Gbuomprisco** [comment]
Hi @MrZaYaC,

thanks for reporting, I'm going to have a look soon (finally holidays time)

**Comment by Gbuomprisco** [comment]
Hi @MrZaYaC,

the package doesn't use style-loader anymore - maybe it could work now? I'll test asap with an universal boilerplate
