### ISSUE TITLE
Multiple errors on sample page

### ISSUE THREAD

**Issue by jmynes** [Gbuomprisco/ng2-tag-input#107]
[https://gbuomprisco.github.io/ng2-tag-input/](url) has samples listed of various uses for your module. However, if you delete the typescript or javascript tag in the max 5 field above it and then click the tag with the same text in read-only, it deletes itself. Additionally, the max 5 field only allows for 3 tags.

Using Firefox Developer Edition 52.0a2 (2016-12-09) (64-bit) on fully updated Arch Linux if relevant.

Edit: Sorry this is my first issue, I forgot to use the labels and cannot seem to go back and fix it.

**Comment by Gbuomprisco** [comment]
Hi @jmynes,

that is a very old version I ought to update. Can you check instead the webpackbin link in the readme? Does the issue still persist? Thanks
