### ISSUE TITLE
Delete Only?

### ISSUE THREAD

**Issue by Tgure** [Gbuomprisco/ng2-tag-input#108]
Is there a way to allow delete but not adding?  I am populating the tags dynamically but only want the user to be able to delete.

**Comment by Gbuomprisco** [comment]
Hi @Tgure,

not at the moment unfortunately. I will try adding an option for that.

**Comment by Gbuomprisco** [comment]
Hi @Tgure,

not sure you're still interested, but the latest version allows to hide the form with `[hideForm]=true`

**Comment by Tgure** [comment]
@Gbuomprisco Awesome, I will give it a try thanks.
