### ISSUE TITLE
autocomplete custom template/ modify the css for autocomplete dropdown to include the font-awesome icons?

### ISSUE THREAD

**Issue by anvesh48** [Gbuomprisco/ng2-tag-input#109]
# Gbuomprisco,

I am trying to add a custom template for autocomplete dropdown can you please point me to any example in the documentation or please confirm whether it is available or not. Actually, in our project we have two custom partial templates one for the displaying tags name  and the other one is for displaying autocomplete dropdown list, but in the documentation i can see only custom template for tag. Is there any way  to add a custom template for both of them.

Also, I was playing with this plugin for a while actually we used ngTagsInput plugin http://mbenford.github.io/ngTagsInput for Angular 1.x. And i was trying to migrate the features that is available in that plugin. I know that this plugin is inspired from the md-chips which has the similar features. But i am wrapping my head around to compare the features and found some of them missing. If i miss anything in the below list can you please confirm if it's already there. 

display-property: Property used to render tags label.
key-property:  Property to be used as the unique identifier for the tag.
text: Assignable angular expression for data-binding to the element’s text.
allow-leftover-text:  Sets the leftoverText validation error  key in the input element when the directive loses focus.

on-tag-adding: Expression to evaluate that will be invoked before adding a new tag. The new tag is available as $tag. This method must return either a boolean value or a promise.( Kind of doubt to use validators, i tried to use exactly the way you mentioned in the documentation but getting error).

template: It uses URL or id for rendering custom template for each tag.(autocomplete)

load-on-down-arrow: Flag indicating that the source option will be evaluated when the down arrow key is pressed and the suggestion list is closed. The current input value is available as $query.

load-on-focus:  Flag indicating that the source option will be evaluated when the input element gains focus. The current input value is available as $query.

**Comment by tomalex0** [comment]
@Gbuomprisco  as its dependent on https://github.com/Gbuomprisco/ng2-material-dropdown
Any option to change the dropdown template?

**Comment by Gbuomprisco** [comment]
Hi @anvesh48,

all good suggestions, thanks. But obviously, it is going to take a little before I can add them all. I would very welcome PRs that could speed up that :).

@tomalex0 not at the moment :(

**Comment by Gbuomprisco** [comment]
Hi everyone,

just FYI I am working on changing the dropdown template possible.

See https://github.com/Gbuomprisco/ng2-tag-input/pull/116

**Comment by anvesh48** [comment]
Thanks..!

**Comment by tomalex0** [comment]
@Gbuomprisco  is it possible to  have html inside  `chips` and `dropdown`

What i'm trying to do is to call function by  passing item and get back other values and render .

**Comment by Gbuomprisco** [comment]
Hi @tomalex0,

not sure I understand correctly, but you may need to use `[innerHTML]`?
