### ISSUE TITLE
Duplicate handling

### ISSUE THREAD

**Issue by FallenRiteMonk** [Gbuomprisco/ng2-tag-input#11]
Hy,

would it be possible to handle duplicates same as in the original ng-chips?
In the original the input filed gets cleared if a duplicate input is entered.

Further more I once found such a input that also made the corresponding duplicate blink once in a different color, to show that such a tag has already been entered. Such a feature would also be great I think.

**Comment by Gbuomprisco** [comment]
Hi @FallenRiteMonk, that would be quite good to have, it's true. I'll be adding it soon!

**Comment by FallenRiteMonk** [comment]
If you would add some contribution description I would be pleased to contribute by my self.

**Comment by Gbuomprisco** [comment]
@FallenRiteMonk feel free to submit a PR with, your contribution is absolutely welcome. At the moment my contribution description would be to just write Angular 2 that adheres with tslint (already configured in the package).

**Comment by FallenRiteMonk** [comment]
I found a bug, which is somehow related to this.
It can be easily reproduced in you live demo. Just go to the example which has space as separator key. At a tag, for example 'hello' if you then enter 'hello hello' then the tag '@@hello hello' gets added.
Implementing the above described feature would clear the input on pressing the spacebar and no such strange tag could be added.

**Comment by Gbuomprisco** [comment]
As of version 0.1.5 duplicate values entered cause the input to be reset :) The blink behaviour though is would still be very nice to have! I guess I'll do it after completing the autocomplete feature (which requires a new component to be added, ng2-dropdown).
