### ISSUE TITLE
File error when building production build

### ISSUE THREAD

**Issue by Taffatech** [Gbuomprisco/ng2-tag-input#110]
I have a seed project:

https://github.com/mgechev/angular-seed
I am trying to build a production build of the app using:

$ npm run build.prod
I am using a module that I have installed using:

npm install ng2-tag-input --save
I am getting an error:

'build.bundles.app' errored after 1.41 s
Error on fetch for ng2-tag-input.js at file:///D:/APP/node_modules/ng2-tag-input.js
    Loading dist\tmp\app\content/timeline/mainArea.module.js
    Loading dist\tmp\app\content/content.module.js
    Loading dist\tmp\app\app.module.js
    Loading dist\tmp\app\main.js
    Error: ENOENT: no such file or directory, open 'D:\APP\node_modules\ng2-tag-input.js'
I am using this module in my app and it works fine when running the app in localhost. The error only shows up when trying to package the app.

The module I am using is:

https://github.com/Gbuomprisco/ng2-tag-input
In the root of the ng2-tag-input folder in node_modules there is:

dist
index.ts
package.json
README.md
Inside the dist folder is:

modules
index.d.ts
index.js
index.js.map
ng2-tag-input.bundle.js
ng2-tag.input.map
vendor.bundle.js
vendor.map
Inside the modules folder is:

components
ng2-tag-input.module.d.ts
ng2-tag-input.module.js
ng2-tag-input.module.js.map
Inside the components folder is:

helpers
icon
pipes
tag-input-form
tag-input-form
index.d.ts
index.js
index.js.map
tag-input.d.ts
tag-input.js
tag-input.js.map
..and so on.

**Comment by Gbuomprisco** [comment]
Hi @Taffatech,

are you using SystemJS or Webpack?

**Comment by Taffatech** [comment]
Hey, I am using the following seed project:
https://github.com/mgechev/angular-seed

**Comment by Manikandan-Constient** [comment]
Hey, I'm using Webpack, and I get the following error.

node_modules/ng2-tag-input/dist/node_modules/ng2-material-dropdown/index"' has no exported member 'DropdownStateService'.
node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.d.ts(11,15): error TS2304: Cannot find name 'Ng2Dropdown'.
node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.d.ts(30,28): error TS2304: Cannot find name 'Ng2Dropdown'.
node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.d.ts(32,28): error TS2304: Cannot find name 'Ng2MenuItem'.

Any workaround..?

**Comment by Gbuomprisco** [comment]
Hi @Manikandan-Constient,

can you try version 0.8.6?

**Comment by mtfurlan** [comment]
Moving from 0.8.5 to 0.8.6 worked for me in a webpack based project.
For some reason `npm i --save ng2-tag-input` installed 0.8.5.
Cheers!

**Comment by Gbuomprisco** [comment]
Yeah, it's still under the tag beta as I didn't know if it worked :)
