### ISSUE TITLE
onAdd(item) is returning undefined.

### ISSUE THREAD

**Issue by anvesh48** [Gbuomprisco/ng2-tag-input#111]
Gbu, I am trying to capture the selected item from the autocomplete list by using (onAdd)="onAdd(item)" method and trying to capture the value in the component. But it is returning undefined in the componnent. Can you please add any example in the documentation for it please.

**Comment by Gbuomprisco** [comment]
Hi @anvesh48,

could you try renaming `onAdd(item)` to `onAdd($event)`?

**Comment by anvesh48** [comment]
Thanks Gbu, for your reply. I appreciate that.

**Comment by Gbuomprisco** [comment]
Hi! Please reopen if this is still an issue

**Comment by anvesh48** [comment]
It is working for me after changing to onAdd($event). Can you please add the same thing in the documentaion.
