### ISSUE TITLE
Files not getting put down with npm install

### ISSUE THREAD

**Issue by shermmyy** [Gbuomprisco/ng2-tag-input#113]
I'm trying to install the library via npm install, but it doesn't look like anything is being put down. What are some potential solutions?

![screen shot 2016-12-21 at 10 21 38 pm](https://cloud.githubusercontent.com/assets/5205459/21414329/7617d6e2-c7cc-11e6-9735-6f39d1babfc1.png)

**Comment by Gbuomprisco** [comment]
Hi @shermmyy,

it sounds pretty weird. I see the 'dist' folders are not there...

**Comment by shermmyy** [comment]
I'm now getting some more files, but no /
![screen shot 2016-12-22 at 12 15 24 pm](https://cloud.githubusercontent.com/assets/5205459/21434059/7873b8f6-c840-11e6-8f9c-a34cf3751130.png)
dist

**Comment by Gbuomprisco** [comment]
HI @shermmyy,

so which command are you exactly using when installing this? I must be dependent on the config, cause I can't reproduce, nor I think anyone did so far :)

**Comment by shermmyy** [comment]
Thanks for the help @Gbuomprisco!

<img width="1093" alt="screen shot 2016-12-22 at 12 50 23 pm" src="https://cloud.githubusercontent.com/assets/5205459/21435016/57b6606e-c845-11e6-8f71-0b11b2edf779.png">

**Comment by Gbuomprisco** [comment]
That seems absolutely correct - therefore pretty strange!
