### ISSUE TITLE
Build is breaking

### ISSUE THREAD

**Issue by anvesh48** [Gbuomprisco/ng2-tag-input#115]
/node_modules/ng2-tag-input/dist/node_modules/ng2-material-dropdown/index.d.ts:1:96 
Cannot find module './dist/src/index'.[39m[22m

I am getting this error when we are building our application.

**Comment by Gbuomprisco** [comment]
Sorry,

I should have fixed now. Please notice `ng2-material-dropdown` is a peer dependency and needs to be installed separately (see readme). I'll try to have this optional, as many people don't use the autocomplete option.
