### ISSUE TITLE
Internet explorer support

### ISSUE THREAD

**Issue by AndriiDidkivsky** [Gbuomprisco/ng2-tag-input#117]
Autocomplete dropdown doesn't appear in IE. 
Body tag contains ng2-material-dropdown component, I think it's a style issue. 

Can you help us to resolve that problem? 

Tested in IE 10, 11.

**Comment by AndriiDidkivsky** [comment]
@Gbuomprisco, could you provide workaround for us before issue will be resolved ?

**Comment by AndriiDidkivsky** [comment]
@Gbuomprisco , Oh, I understand.
I'll try to solve this problem and create a pull request. 
Thanks for quick answer.

**Comment by Gbuomprisco** [comment]
@AndriiDidkivsky that would be awesome :)

**Comment by AndriiDidkivsky** [comment]
Fixed in latest versions
