### ISSUE TITLE
NgFormControl Error

### ISSUE THREAD

**Issue by FallenRiteMonk** [Gbuomprisco/ng2-tag-input#12]
Hy,

I have problems trying to implement this component.

The error i get is the following:
```
EXCEPTION: Error: Uncaught (in promise): Template parse errors:
Can't bind to 'ngFormModel' since it isn't a known native property ("

    <!-- form -->
    <form (ngSubmit)="add()" *ngIf="input.isVisible.call(this)" [ERROR ->][ngFormModel]="form">
        <input type="text"
               required
```

I am using the new Angular Form module ```"@angular/forms": "0.1.1"```, but I don't know if that is relevant.

Thanks for your help,
FallenRiteMonk

**Comment by Gbuomprisco** [comment]
HI @FallenRiteMonk, can you please post here which Angular version you're running? This should be working fine with the latest RC3 (and RC1). I know it's going to be deprecated, so I need to change this anyway. Thanks for posting the issue 👍

**Comment by FallenRiteMonk** [comment]
These are my dependencies regarding angular:
```
    "@angular/common": "2.0.0-rc.3",
    "@angular/compiler": "2.0.0-rc.3",
    "@angular/core": "2.0.0-rc.3",
    "@angular/forms": "0.1.1",
    "@angular/http": "2.0.0-rc.3",
    "@angular/platform-browser": "2.0.0-rc.3",
    "@angular/platform-browser-dynamic": "2.0.0-rc.3",
    "@angular/router": "3.0.0-alpha.7",
    "es6-shim": "0.35.1",
    "reflect-metadata": "0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.31",
    "zone.js": "0.6.12"
```
If you need anything else or some help, let me know!

**Comment by Gbuomprisco** [comment]
Your versions seem correct! The problem is that the ng2-input-tag component is using a deprecated version of ngFormModel. Maybe disaling "@angular/forms" in the short term would work but I don't recommend it.

I'll to update the form to use the new version with @angular/forms. By looking at the documentation, it's not a big change, so will do it soon 👍

**Comment by FallenRiteMonk** [comment]
Thank you! :+1:

**Comment by Gbuomprisco** [comment]
Opened a PR https://github.com/Gbuomprisco/ng2-tag-input/pull/13. WIll test and merge

**Comment by Gbuomprisco** [comment]
PR merged to master. Version 0.1.1 on NPM should fix the issue :+1:

**Comment by FallenRiteMonk** [comment]
I retried it and now i get the following error:
```
ORIGINAL EXCEPTION: No provider for FormBuilder!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:4200/vendor/@angular/core/src/facade/exceptions.js:20:23)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:4200/vendor/@angular/core/src/di/reflective_exceptions.js:40:16)
    at new NoProviderError (http://localhost:4200/vendor/@angular/core/src/di/reflective_exceptions.js:77:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:4200/vendor/@angular/core/src/di/reflective_injector.js:777:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/vendor/@angular/core/src/di/reflective_injector.js:805:25)
    at ReflectiveInjector_._getByKey (http://localhost:4200/vendor/@angular/core/src/di/reflective_injector.js:768:25)
    at ReflectiveInjector_.get (http://localhost:4200/vendor/@angular/core/src/di/reflective_injector.js:577:21)
    at ElementInjector.get (http://localhost:4200/vendor/@angular/core/src/linker/element_injector.js:23:48)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:4200/vendor/@angular/core/src/di/reflective_injector.js:802:24)
    at ReflectiveInjector_._getByKey (http://localhost:4200/vendor/@angular/core/src/di/reflective_injector.js:768:25)
```

**Comment by Gbuomprisco** [comment]
Hm very strange, didn't encounter this error. Have you configured the app like described in https://github.com/Gbuomprisco/ng2-tag-input#angular-2-configuration-rc3?

**Comment by FallenRiteMonk** [comment]
Yes

**Comment by Gbuomprisco** [comment]
Would you mind posting here the bootstrap code? I need a bit of context 👍  I wonder if running the demo works on your end?

**Comment by FallenRiteMonk** [comment]
This would be my main.js:
```
import { bootstrap } from '@angular/platform-browser-dynamic';
import { enableProdMode, provide, PLATFORM_DIRECTIVES } from '@angular/core';
import { LocationStrategy, PathLocationStrategy } from '@angular/common';
import { HTTP_PROVIDERS, Http } from '@angular/http';
import { disableDeprecatedForms, provideForms, REACTIVE_FORM_DIRECTIVES } from '@angular/forms';

import { AuthHttp, AuthConfig } from 'angular2-jwt';

import { WEB_ROUTER_PROVIDERS, WebAppComponent, environment } from './app/';

import 'jquery';
import 'bootstrap';
import 'primeui';
import 'rxjs/add/operator/map';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/do';
import 'rxjs/add/operator/share';

if (environment.production) {
  enableProdMode();
}

bootstrap(WebAppComponent, [
  HTTP_PROVIDERS,
  provide(AuthHttp, {
    useFactory: (http) => {
      return new AuthHttp(
          new AuthConfig({
            noJwtError: true,  // Make AuthHttp use default http reqest if no token is stored locally
            tokenName: 'id-token'
          }),
          http);
    },
    deps: [Http]
  }),
  WEB_ROUTER_PROVIDERS,
  { provide: LocationStrategy, useClass: PathLocationStrategy },
  disableDeprecatedForms(),
  provideForms(),
  {
        provide: PLATFORM_DIRECTIVES,
        useValue: [REACTIVE_FORM_DIRECTIVES],
        multi: true
  }
]);
```

Running the demo runs without any problems. 

Since I'm using angular-cli I'll try to rebuild a minimal example and commit it to a github repository so you can try! I'll let you know when I got it done and up! In the main wile if you need any more info, just keep asking.

**Comment by Gbuomprisco** [comment]
Your config seems just fine. But the minimal example would be much help! :)

**Comment by FallenRiteMonk** [comment]
Here my example: https://github.com/FallenRiteMonk/tagInputExample

Just install angular-cli: ```npm install -g angular-cli```
install the packages: ```npm install```
and serve the application: ```ng serve``
then navigating to [localhost:4200](http://localhost:4200) will bring you to the site and display the error!

**Comment by Gbuomprisco** [comment]
I didn't include angular forms in the webpack vendors and therefore the error! Try pulling the latest version (0.1.2). :)

**Comment by FallenRiteMonk** [comment]
Works fine now thanks :+1:

**Comment by Gbuomprisco** [comment]
👍
