### ISSUE TITLE
Problem with non-English characters

### ISSUE THREAD

**Issue by manhlinhnguyen** [Gbuomprisco/ng2-tag-input#120]
Nice component, and I found it suit very well to my need. However I found a small bug with the version I installed with npm.
I get this error when input with non-english characters"
`Error in ./TagInputForm class TagInputForm - inline template:2:4 caused by: Cannot read property 'focus' of undefined`
And it auto-separates the word into many pieces, for example: I type "đất" and it shows 4 tags: d, đa, ât, ất
When I tried your demo on Webpackin, there is no problem.
Thank you very much!

**Comment by manhlinhnguyen** [comment]
Hello,
It appears to be OK when I remove the separatorKeys attribute from <tag-input>
```
<tag-input [ngModel]="entry.tags" 
		separatorKeys="[13, 188]" 
		 formControlName="tags">		   
</tag-input>
```
Is it considered a bug and need to be fixed?

Anyway, thank again!!!

**Comment by Gbuomprisco** [comment]
Hi @manhlinhnguyen,

Hmm, I don't seem able to reproduce it! If you don't need the separatorKeys attribute, I'll close for now, but reopen if needed :)
