### ISSUE TITLE
Custom template loses styles

### ISSUE THREAD

**Issue by PTC-JoshuaMatthews** [Gbuomprisco/ng2-tag-input#124]
For some reason when I attempt to use a custom template, the included styles are no longer applied. I see this working in the demo, but still it is an issue with the css scoping that Angular2 is doing. The _ngContent tag added to the html is not matching the one in the stylesheet. Any ideas what could cause that?

**Comment by Gbuomprisco** [comment]
Hi @PTC-JoshuaMatthews,

Thanks for reporting it. The demo is unfortunately outdated.
I'm working on a fix (PR open) and improve the way to write a custom template using <template>

**Comment by Gbuomprisco** [comment]
Hi! 

The updated version should be live! You'll need to slightly change the way you're defining your template. Have a look at the readme.

Please reopen if you find issues, thanks

**Comment by PTC-JoshuaMatthews** [comment]
That did fix it, thanks!
