### ISSUE TITLE
Not compatible with Angular 2.4.1: trackBy must be a function

### ISSUE THREAD

**Issue by maltehol** [Gbuomprisco/ng2-tag-input#132]
Trying the version 0.6.0 with angluar 2.4.1 I get following error:
> trackBy must be a function, but received undefined

Liklely it's related to this isssue: https://github.com/angular/angular/issues/13641

So the `trackBy: value` in tag-input.template.html has to replaced by a function when I got that correctly.

**Comment by Gbuomprisco** [comment]
Hi @maltehol,

thanks for reporting. The latest version (0.6.1) should take care of that. Reopen if still an issue please :)

**Comment by jonohrt** [comment]
I'm getting this same error with 0.6.1 and angular 2.4.1. Any idea?

**Comment by Gbuomprisco** [comment]
This is the change I added (I did not test with @2.4.1 though):

https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/tag-input.template.html#L10

Very odd :| @maltehol do you also reproduce this?

**Comment by Gbuomprisco** [comment]
Hi @jonohrt,

I temporarily removed the trackBy from there, for some reason an undefined item gets passed probably before the items are passed to the accessor (or some odd reason). Try the new version :)

**Comment by jonohrt** [comment]
Seems to be working now. Thanks!
