### ISSUE TITLE
Can't bind to 'identifyBy' since it isn't a known property of 'tag-input'.

### ISSUE THREAD

**Issue by PTC-JoshuaMatthews** [Gbuomprisco/ng2-tag-input#133]
Using version 0.6.2 but not able to bind to identifyBy. Is there a more recent version that I need?

**Comment by PTC-JoshuaMatthews** [comment]
Also wondering, for the dropdown do I need to explicitly install ng2-material-dropdown or will it be included automatically by installing ng2-tag-input?

**Comment by Gbuomprisco** [comment]
Hi @PTC-JoshuaMatthews,

what Angular version are you using? It's working well on my end (0.6.2 is the latest)

**Comment by PTC-JoshuaMatthews** [comment]
Upgraded to 2.4.1 and this issue went away. Thanks for all the good work!

**Comment by Gbuomprisco** [comment]
@PTC-JoshuaMatthews glad it works :)
