### ISSUE TITLE
Remove tag button doesn't work when ngModel is an array objects, unless display == value

### ISSUE THREAD

**Issue by PTC-JoshuaMatthews** [Gbuomprisco/ng2-tag-input#135]
When the tag control adds an object, it creates the object {display: 'enteredString', value: 'enteredString'}

This object can be removed. But If I initialize the tag control with ngModel like [{display: 'val1', value: '1'}, {display: 'val2', value: '2'}] then those tags cannot be removed. If initial ngModel is  [{display: 'val1', value: 'val1'}, {display: 'val2', value: 'val2'}] then it works as expected, but that is not desireable as it negates the benefit of having seperate display and value properties.

**Comment by Gbuomprisco** [comment]
Hi @PTC-JoshuaMatthews,

I just released a fix :) Please reopen if still an issue
