### ISSUE TITLE
Autocomplete doesn't work

### ISSUE THREAD

**Issue by gooor** [Gbuomprisco/ng2-tag-input#138]
Example from README doesn't work as expected
```
<tag-input [ngModel]="['@item']">
       <tag-input-dropdown [autocompleteItems]="[{display: 'Item1', value: 0}, 'item2', 'item3']">
       </tag-input-dropdown>
</tag-input>
```
Results in `Can't bind to 'autocompleteItems' since it isn't a known property of 'tag-input-dropdown'.` error

**Comment by Gbuomprisco** [comment]
Hi @gooor,

Sorry, the readme refers to another version I have not yet published. Please move [autocompleteItems] to the component `tag-input`. See the webpackbin link for examples :)

**Comment by Gbuomprisco** [comment]
Scratch that - actually. I just published the new version; let me know if you still have issues
