### ISSUE TITLE
Version 0.7.0 not via npm?

### ISSUE THREAD

**Issue by AceTheFace** [Gbuomprisco/ng2-tag-input#140]
Hi,

could you please provide the current version 0.7.0 via npm? I'm currently trying to get autocomplete working, but it seems documentation/demos differs from the implementation in 0.6.* (see #138)
I tried to install the current MASTER with npm but I have no clue how to create a working dist-package :(

Thanks in advance!! @Gbuomprisco

**Comment by Gbuomprisco** [comment]
Hi @AceTheFace,

I published the version 0.7.0 yesterday :) Does it not work for you? The demo is definitely outdated but the examples in the readme should be fine

**Comment by AceTheFace** [comment]
Thanks, now 0.7.0 was installed and everything is working as expected. Thanks for that great component!!
