### ISSUE TITLE
When adding duplicate tag and press enter key it will refresh the page

### ISSUE THREAD

**Issue by 001saraju** [Gbuomprisco/ng2-tag-input#141]
Hello, I have used tag-input inside form tag and when adding duplicate tag and press enter key it will refresh the page.
So how can I stop refreshing the page and validate it ?

**Comment by Gbuomprisco** [comment]
Hi, sorry, must be a bug. Will have a look soon.

**Comment by Gbuomprisco** [comment]
Hi @001saraju,

could you try stop the console on errors and paste the stack trace here? I wasn't able to reproduce the error, so I suspect it's something else happening.

**Comment by 001saraju** [comment]
Sorry for the late replay, here is the image you can see I entered "C#" second time and it throws error in console refresh the whole form because I added "tag-input" inside form tag.

<tag-input [(ngModel)]="SkillList" name="SkillList"></tag-input>

![error](https://cloud.githubusercontent.com/assets/23423146/21715858/f60f9882-d42c-11e6-8cd8-26b9e92611a1.png)

**Comment by Gbuomprisco** [comment]
I believe your browser doesn't support Array.prototype.find() (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find)

What version of Chrome are you running? 

I'd use an es6 polyfill for this, but I believe it would need to be added to the whole application rather than in a single component.

**Comment by 001saraju** [comment]
I am using latest Version 55.0.2883.87 of chrome and I'd use es5 (angular 2).

**Comment by Gbuomprisco** [comment]
Actually - my bad: the method is on QueryList https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/tag-input.ts#L368

The method find() seems to be the latest introduced here: https://github.com/angular/angular/commit/7c16ef942e135ea64a69ce8025c75c140c113d83

What version of Angular are you running?

**Comment by 001saraju** [comment]
I am using angular version 2.1.0

**Comment by Gbuomprisco** [comment]
That's the reason :) the component is supposed to work with the latest versions. At the moment this is the 2.4.1. The find() method was introduced in the version 2.2.0 I suppose.

**Comment by 001saraju** [comment]
Hmmm ok, so how can I handle this error you have any idea ?

**Comment by Gbuomprisco** [comment]
@001saraju the only option i can see is to update your packages
