### ISSUE TITLE
Error with Animation

### ISSUE THREAD

**Issue by JdgaleTorre** [Gbuomprisco/ng2-tag-input#147]
I'm adding ng2 tag input to my project and having the next error:

>  zone.js:388 Unhandled Promise rejection: Animation parse errors:
> - Unable to parse the animation sequence for "flyInOut" on the TagInputComponent component due to the following errors:
> -- the provided :enter is not of a supported format
> -- the provided :leave is not of a supported format ; Zone: <root> ; Task: 

I add in my Module:

> import { TagInputModule } from 'ng2-tag-input';

Also this in my system.js

>  'ng2-tag-input': {
>                 main: 'dist/ng2-tag-input.bundle.js',
>                 format: 'cjs',
>             },
>             'ng2-material-dropdown': {
>                 defaultExtension: 'js',
>                 main: 'dist/ng2-dropdown.bundle.js',
>                 format: 'cjs',
>             },
>             'ng2-tag-input/modules/components/tag-input.template.html': {
>                 defaultJSExtension: false
>             }

Thanks.

**Comment by Gbuomprisco** [comment]
Hi @JdgaleTorre,

I suspect you're using an earlier version of Angular? This component is supposed to work with Angular 2.4.1. :) Which one are you running?

**Comment by webcat12345** [comment]
Same issue on my side.

**Comment by webcat12345** [comment]
Further information : This is my **module**
`import { TagInputModule } from 'ng2-tag-input';`
And this is **ng2-tag-input.module.d.ts**
`import { TagInputForm } from './components/tag-input-form';
import { TagInputComponent } from './components';
import { TagInputDropdown } from './components/dropdown/tag-input-dropdown.component';
export declare class TagInputModule {
}
export { TagInputComponent, TagInputForm, TagInputDropdown };
`
Here first 2 lines are not resolved : 
`import { TagInputForm } from './components/tag-input-form';
import { TagInputComponent } from './components';`

These are not recognized by project.

**Comment by Gbuomprisco** [comment]
Hi @webcat12345,

Are you running Angular 2.4.1 or which version?

**Comment by webcat12345** [comment]
Thanks for your quick response. I am using Angular 2.0.2 and Just updated package.json with 2.4.1 and now updating packages.

**Comment by Gbuomprisco** [comment]
Cool, you may have some things to change in your application, but the following error should disappear. Always a good thing to update anyway :)

**Comment by webcat12345** [comment]
Thank you , I will post questions here if I have some more issues. This component looks amazing and I decided to use this component for our project and I am nearly excited!  Thank you!

**Comment by Gbuomprisco** [comment]
Thanks! More updates are on the way (see PRs). @JdgaleTorre I believe you will fix the issue by updating to Angular 2.4.1. I am closing the issue but please reopen if there are still issues

**Comment by JdgaleTorre** [comment]
Thank you, you're right, it was the angular, I was using 2.0.3.
Thanks for your help.
