### ISSUE TITLE
Flex-wrap issue

### ISSUE THREAD

**Issue by FallenRiteMonk** [Gbuomprisco/ng2-tag-input#15]
Hy,

I have the issue that adding many tags makes them overflow to the right of the screen. This is because for some reason flex is not wrapping in my example (https://github.com/FallenRiteMonk/tagInputExample) as it is in your live demo. I figured out that adding ```flex-wrap: wrap;``` or ```flex-wrap: inherit;``` to the flex class definition in style.scss fixes the problem for me.
Would it be possible that this could be implemented or do I have to work around it somehow using the custom template?

**Comment by Gbuomprisco** [comment]
Hi @FallenRiteMonk,

I am not sure it's going to be fixed, but I pushed a new version which hopefully works!

**Comment by FallenRiteMonk** [comment]
Works like a charm. Thanks for your quick fix! :+1:
