### ISSUE TITLE
Optionally Disable Default Validation

### ISSUE THREAD

**Issue by Soubkia** [Gbuomprisco/ng2-tag-input#150]
If you press enter on an empty input it displays a warning saying "Please fill out this field". I would like to be able disable this so that pressing enter on an empty tag input is mapped to a valid user action (like submitting a form or executing a search).

I think the issue is the `required` [here](https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/tag-input-form/tag-input-form.template.html#L5) but I haven't verified.

Do you have any objections to making this configurable? I think the PR would be pretty straightforward.

**Comment by Gbuomprisco** [comment]
Hi @Soubkia,

I was aware of that and tried to remove the ugly message, but the validity of the Angular form might not work. Unless we just check `input.value.trim()`.

No objections at all, as long as this still pass :) I can try and work on it later today if you'd rather wait

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/151

**Comment by Gbuomprisco** [comment]
Hi @Soubkia ,

can you try the version 0.7.4? Thanks
