### ISSUE TITLE
Error in webpack

### ISSUE THREAD

**Issue by PTC-JoshuaMatthews** [Gbuomprisco/ng2-tag-input#153]
[at-loader] node_modules\ng2-tag-input\dist\node_modules\ng2-material-dropdown\index.d.ts:1:97 
    Cannot find module './dist/src/index'. 

Any idea how to resolve this?

**Comment by tonysparks** [comment]
Update to version 0.7.4.  See #149

**Comment by Gbuomprisco** [comment]
Yeah - that's still under the tag `beta` cause i wasn't sure if it worked for everyone, will later update on NPM

**Comment by PTC-JoshuaMatthews** [comment]
Thanks! Trying that now

**Comment by PTC-JoshuaMatthews** [comment]
That fixed it, thanks!

**Comment by Gbuomprisco** [comment]
Nice :)
