### ISSUE TITLE
tags with spaces block user input when autocomplete displays

### ISSUE THREAD

**Issue by scottwpage** [Gbuomprisco/ng2-tag-input#154]
Angular 2.4.2
- Add a tag with spaces (e.g. 'git workflow')
- Type 'git' in the tag input and note the autocomplete displays showing the existing 'git workflow' tag.
- At that point trying to type a space (for example to create a new 'git merge' tag) will be blocked (i.e. nothing happens).
- The only workaround is to type something else other than a space (e.g. 'gits merge') and then go back and delete the 's'

**Comment by Gbuomprisco** [comment]
Hi @scottwpage,

This issue should have been resolved as of version 0.7.3. Can you check which one you are running?

Thanks

**Comment by scottwpage** [comment]
I was on version 0.7.0. Upgrading to 0.7.3 fixed the issue.  Thanks
