### ISSUE TITLE
Is there a way to prevent user from adding tag to the input?

### ISSUE THREAD

**Issue by thisisgit** [Gbuomprisco/ng2-tag-input#155]
Hi,

I want to let users add the tags from different input component (checkbox in my case) and let ng2-tag-input to only allow search and display those added tags.
I think "validators" is the key to achieve this behavior but it seems like it requires "errorMessages" input to go along with it. I don't want error message to appear since showing it gives impression that it validates and accepts any input.

Is there a way to achieve this?

**Comment by Gbuomprisco** [comment]
Hi @thisisgit,

How about you use the property `hideForm` so that the input will not appear?

**Comment by thisisgit** [comment]
Hi @Gbuomprisco,

I tried using hideForm but this basically disables any input. I'm trying ng2-tag-input to **accept input** for searching/filtering purposes only (search/filter from table column) but refrain it from adding tags with the inputs in it. Probably using validators is the only solution to achieve this, and I guess my question was not that clear for you to answer. Sorry about that.

So what I did was to use a validator that always returns Object to prevent the input to add tag, then applied:
`
>>> .ng2-tag-input--invalid {
  border-bottom: 2px solid #2196F3 ! important;
}
`
style to make input tag look like that it doesn't validate anything.

This works but I hope this component to have a feature that does the same thing since I think this is somehow useful when interacting with other components.

Anyway, thanks for making such a great tag-input component for ng2!

p.s. API for hideForm says [?number] which I think should be [?boolean].

**Comment by Gbuomprisco** [comment]
Hi @thisisgit,

I see. Have you though checked out the `onlyFromAutocomplete` property?https://github.com/Gbuomprisco/ng2-tag-input#autocomplete-optional

If I am not mistaken, it should exactly be what you're looking for?

**Comment by thisisgit** [comment]
Hi again @Gbuomprisco,

I just tried `onlyFromAutocomplete` property and it exactly does the same thing except that it accepts enter/return which clears out the input field. I guess this also needs extra work of preventing the default behavior of return by using (keyup), (onTextChange), [validators], or etc.

But I think that approach is lighter than what I did previously. Thanks a lot!

**Comment by Gbuomprisco** [comment]
I see, I though you still wanted the functionality of adding from an autocomplete: as you said- you probably can make it work with some hacking :)
