### ISSUE TITLE
Safari support

### ISSUE THREAD

**Issue by AndriiDidkivsky** [Gbuomprisco/ng2-tag-input#156]
Hi.
I can't remove tag in safari. Version 0.7.2. 
Any workarounds ? 
safari 10.0.1

**Comment by Gbuomprisco** [comment]
Hi @AndriiDidkivsky, thanks for reporting.

I can see many issues with Safari at the moment, I'm changing the title to "Safari Support".

**Comment by AndriiDidkivsky** [comment]
I've removed ripple effect for workaround at the moment. 
tag-ripple component covers remove button.

**Comment by DerMorb** [comment]
How did you remove the ripple effect?

**Comment by AndriiDidkivsky** [comment]
@DerMorb , hi.

I've added css rule. 

```
tag tag-ripple {
  z-index: -1;
} 
```

**Comment by DerMorb** [comment]
Perfect. Thank you!

**Comment by Gbuomprisco** [comment]
The ripple is now removed in Safari, IE and Firefox for max compatibility
