### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by minuz** [Gbuomprisco/ng2-tag-input#158]
Hi, I've been trying to add this component to my project but I'm getting the following error:

`node_modules/ng2-tag-input/dist/node_modules/ng2-material-dropdown/index.d.ts(1,97): error TS2307: Cannot find module './dist/src/index'.`

When I see the structure from your module, it looks like the following 
![image](https://cloud.githubusercontent.com/assets/818024/22095088/2cacd178-de66-11e6-911b-efc5f85061df.png)

So it looks like your AoT compilation is not bringing all the required files, or am I missing something?

**Comment by Gbuomprisco** [comment]
Hi @minuz,

can you try setting the version of the package to `0.7.4`?

**Comment by minuz** [comment]
Hi @Gbuomprisco,

Now my ts are compiling fine, thanks!
However, 2 things...
My project is using RxJs 5.0.3, I believe you should use the dependency with the ^5.0.1 instead so then npm install wouldn't complain. 
The second is, now with my AoT compilation I get the following error: 

`Unexpected value 'TagInputModule in C:/GitHub/Lumen.Workbench/Lucsan.Workbench/Lucsan.Workbench.WebApp/node_modules/ng2-tag-input/dist/modules/ng2-tag-input.module.d.ts' imported by the module 'CustomTypesModule in C:/GitHub/Lumen.Workbench/Lucsan.Workbench/Lucsan.Workbench.WebApp/wwwroot/ng/customTypes/custom.types.module.ts'`

Thanks for your help.
Cheers

**Comment by Gbuomprisco** [comment]
HI @minuz,

there may be issues with the latest cli (as documented in an another ticket). I'll check out and try to fix these issues :)

**Comment by Gbuomprisco** [comment]
This should be resolved with the latest release
