### ISSUE TITLE
Component inheritance issues

### ISSUE THREAD

**Issue by troelssiggaard** [Gbuomprisco/ng2-tag-input#159]
I've tried to extend the tag-input component to use my own styling, as written in your README file, but whatever I do it seems to give me an error, i.e.:

**When I'm using the "autocompletion"/dropdown version I get:**
`EXCEPTION: Error in ./AppComponent class AppComponent - inline template:6:6 caused by: No provider for TagInputComponent!
`
**When I'm using it without the dropdown and autocompletion I get:**
`Unhandled Promise rejection: Failed to execute 'animate' on 'Element': Partial keyframes are not supported. ; Zone: <root> ; Task: Promise.then ; Value: DOMException: Failed to execute 'animate' on 'Element': Partial keyframes are not supported.
`

Either way I can't get it to work, I think I've tried everything. If you can get it to work with the dropdown and "autocompletion only", could you please update the demo or the README with what you did?

I'm not sure if this has anything to do with the "TagInputModule is not an NgModule" error that I'm still getting, but I don't think so.

**Comment by Gbuomprisco** [comment]
Hi @troelssiggaard,

it must have an issue with the animation. Can you check out https://github.com/Gbuomprisco/ng2-tag-input/blob/master/demo/custom/custom.component.ts and see if there's differences with your implementation?

**Comment by troelssiggaard** [comment]
I've used your _custom.component.ts_ as my implementation, my code:
`import { Component, forwardRef, trigger, state, style, transition, animate, keyframes } from '@angular/core';
import { TagInputComponent } from 'ng2-tag-input';
import { NG_VALUE_ACCESSOR } from '@angular/forms';

// all this boilerplate is needed
@Component({
  selector: 'custom-tag-input', // or whatever you want
  providers: [{
    provide: NG_VALUE_ACCESSOR,
    useExisting: forwardRef(() => CustomComponent),
    multi: true
  }],
  styleUrls: [ './custom-tag-input.component.scss' ],
  templateUrl: '../../../node_modules/ng2-tag-input/dist/modules/components/tag-input.template.html',
  animations: [
  trigger('flyInOut', [
    state('in', style({transform: 'translateX(0)'})),
    transition(':enter', [
      animate(250, keyframes([
        style({opacity: 0, offset: 0, transform: 'translate(0px, 20px)'}),
        style({opacity: 0.3, offset: 0.3, transform: 'translate(0px, -10px)'}),
        style({opacity: 0.5, offset: 0.5, transform: 'translate(0px, 0px)'}),
        style({opacity: 0.75, offset: 0.75, transform: 'translate(0px, 5px)'}),
        style({opacity: 1, offset: 1, transform: 'translate(0px, 0px)'})
      ]))
    ]),
    transition(':leave', [
      animate(150, keyframes([
        style({opacity: 1, transform: 'translateX(0)', offset: 0}),
        style({opacity: 1, transform: 'translateX(-15px)', offset: 0.7}),
        style({opacity: 0, transform: 'translateX(100%)', offset: 1.0})
      ]))
    ])
  ])
]

})
export class CustomComponent extends TagInputComponent { }
`

**Comment by Gbuomprisco** [comment]
According to replies online, it seems that it happens because the element doesn't have an initial size. This is a web-animation issue (not Angular's).

What I'd do:
- check out the custom styles are correctly imported
- try define @flyInOut but leave it without animations

**Comment by troelssiggaard** [comment]
The custom styles are the example you've written in the README and they work fine.

I've removed the animations in "flyInOut", but the error persists. Even cutting down the code to this:

`animations: [
    trigger('flyInOut', [
    // cut everything out and error still persist.
    ])
  ]`

**Comment by Gbuomprisco** [comment]
Mhm I see :| I'll try reproduce, probably in the weekend!

**Comment by troelssiggaard** [comment]
I find that the biggest problem is not the animation but the error I get when using your Github example for Autocomplete Only:  "No provider for TagInputComponent!".
I'll have a go at it again, even though I think I've tried all possible combinations to get it to work.

Thank you!

**Comment by Gbuomprisco** [comment]
Ah that's new! Can you post here your package.json (at least the angular deps and ng2-tag-input versions). It will help me debug :)

**Comment by troelssiggaard** [comment]
I can send you my whole application, that's probably easier for you. I will get back to you later with the app... :)

**Comment by Gbuomprisco** [comment]
that would work :)

**Comment by troelssiggaard** [comment]
I just sent you an e-mail with my app, just unpack the .zip-file, `npm install` and run: `ng serve`.

**Comment by realappie** [comment]
Any updates on this issue?

**Comment by Gbuomprisco** [comment]
Hi @realappie,

extending the component won't work with the autocomplete, but works without. At the moment I haven't had a detailed look at this though
