### ISSUE TITLE
Ability to customize comparison of value and drop down items

### ISSUE THREAD

**Issue by tonysparks** [Gbuomprisco/ng2-tag-input#160]
I have a use case where I need to ignore any leading spaces from the input value when comparing against the drop down values.  The current code does a case insensitive [comparison](https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/dropdown/tag-input-dropdown.component.ts#L226).

It would be nice to be able to define my own comparison rules.

Alternatively, what would solve my issue is if when the `autocompleteObservable` function is defined, don't do any matching; just assume the `autocompleteObservable` already handles it.  This option might be to presumptions on my part.

Thank you!

**Comment by Gbuomprisco** [comment]
@tonysparks Yeah I think maybe the most generic way of doing this is being able to provide a custom matching function, maybe an input called `customMatchingFn`, which given two values returns a boolean. Should be pretty straightforward to implement 👍

**Comment by Gbuomprisco** [comment]
This should be available in the version 0.8.0. let me know if it works OK! :)
