### ISSUE TITLE
Not working with angular universal

### ISSUE THREAD

**Issue by tmedanovic** [Gbuomprisco/ng2-tag-input#161]
Library fails when used with angular universal because KeyboardEvent isn't definded on server side: 

`__metadata('design:paramtypes', [KeyboardEvent]), `

Then animation parser complains about animations:

> The provided :enter is not of a supported format

I got it working with webpack loaders to replace all the stuff that fails on server prepredering, but just to leave this issue here so it can be fixed in the future.

**Comment by Gbuomprisco** [comment]
Hi @tmedanovic,

Thanks for reporting. I can change the first issue, but the second is likely due to the Angular version you are running: :enter and :leave are correct states in some of the latest versions.

**Comment by 4nandP** [comment]
For those of us who need a workaround, what did you do in webpack Tomislav?

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/issues/238#issuecomment-285977810
