### ISSUE TITLE
Position / Size of TagInputDropdownComponent

### ISSUE THREAD

**Issue by pschalk** [Gbuomprisco/ng2-tag-input#162]
Hi,

is there a possibility to change the position and the amount of items of the TagInputDropdownComponent? 

I've problems on mobile device that the dropdown hides the input field so that I'm not able to see what I'm currently typing. (Sometimes I'm also not able to type any new char)
(See attached image)

I have already tried the location attribute like this: 

`<tag-input name="quickSearchTags" [(ngModel)]='quickSearchTags'
                 [placeholder]="quickSearchTagsOptions.placeholder"
                 [secondaryPlaceholder]="quickSearchTagsOptions.secondaryPlaceholder"
                 [separatorKeys]="quickSearchTagsOptions.separatorKeys"
                 [onlyFromAutocomplete]="true">
        <tag-input-dropdown
          [showDropdownIfEmpty]="true"
          [autocompleteItems]="quickSearchTagsAutoComplete"
          [offset]="1 0">
        </tag-input-dropdown>
      </tag-input>`

But I'm getting this error: 

`TypeError: Cannot set property 'stack' of undefined
    at SyntaxError.set [as stack] (http://localhost:3000/vendor.bundle.js:6020:61)
    at assignAll (http://localhost:3000/polyfills.bundle.js:16299:29)
    at SyntaxError.ZoneAwareError (http://localhost:3000/polyfills.bundle.js:16370:16)
    at SyntaxError.BaseError [as constructor] (http://localhost:3000/vendor.bundle.js:5982:1`

![20170122_212242](https://cloud.githubusercontent.com/assets/8512329/22185658/15be5d7a-e0ea-11e6-8772-5cb548ef45d6.png)

**Comment by Gbuomprisco** [comment]
Hi, you should try setting `offset` as a string, therefore [offset]="'1 0'". It might still not be optimal as the component is not optimized/thought for mobile devices at all :) Maybe some food for thought for future work

**Comment by pschalk** [comment]
Thanks regarding the offset hint! :) 

Is it possible to "pipe" the output of the autocomplete list to some other component? e.g. a select list which is located next to the input field?

**Comment by Gbuomprisco** [comment]
Do you mean extract the matching items as the user types? Not at the moment, but probably we could add an Output `@onAutocompleteItemsChanged(items: string[] | yourObject[])`. Does it sound reasonable?

**Comment by pschalk** [comment]
No, I mean that I want to replace the "default" popup which lists all autocomplete values with my own list component. 

E.g. like yelp does it on their mobile side: 

<img width="304" alt="bildschirmfoto 2017-01-23 um 13 44 56" src="https://cloud.githubusercontent.com/assets/8512329/22204420/2eef0d0c-e172-11e6-95c3-3e9eb16387ab.png">

So that it's possible to "control" where the autocomplete list pops up. With this feature it would be much more easy to use this component on mobile devices. :)

Do you know what I mean?

**Comment by Gbuomprisco** [comment]
Yeah I get it now :) 

In theory you could create your sub-component, for example see the `tag-input-dropdown` implementation: ( https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/dropdown/tag-input-dropdown.component.ts).

You can use the public methods of `TagInputComponent` to make it play with your component. I haven't tried it but in theory this should be possible.

In alternative, you could extend `TagInputDropdown` using component inheritance and replace templates/styles with your own. I haven't tried this specific case - but it should be feasible. You could reuse the public methods of `TagInputDropdown` which should make life easier.

**Comment by pschalk** [comment]
Ok thanks, I will try this! :)

**Comment by omprakash9** [comment]
@Gbuomprisco ,

Do you have any property to set the width of the dropdown? same like offset? 

I have tried to override the css by giving important to the styles for dropdown but  it was not responsive.
So can you please suggest me. thanks

**Comment by Gbuomprisco** [comment]
@omprakash9, no sorry. But are you using deep selectors (/deep/ or >>>) to set the styles?, remember that the components use emulated shadow dom, so you need that.

**Comment by vgogov** [comment]
@omprakash9 

You can do something like:

`        <tag-input-dropdown [autocompleteItems]="autocompleteItems"
                            [focusFirstElement]="true"
                            [appendToBody]=false>
        </tag-input-dropdown>`

Then in your .scss file have:

`:host /deep/ ng2-dropdown-menu div {
  width: 750px !important;
}
`

And you should see the width change.
