### ISSUE TITLE
 ng2-tag-input@0.7.5 requires a peer of rxjs@5.0.3 but none was installed

### ISSUE THREAD

**Issue by tomalex0** [Gbuomprisco/ng2-tag-input#164]
I have currently upgraded angular to `2.4.4` which has peer dependency of  `rxjs@5.0.1`.

These conflicts prevents me to generate `shrinkwrap` file .

Should we always use peer dependency what `angular2` supports?

**Comment by Gbuomprisco** [comment]
Good point, I'll lock rx to version 5.0.1 👍

**Comment by Gbuomprisco** [comment]
0.7.6 should be out now :)

**Comment by tomalex0** [comment]
that was quick :)
