### ISSUE TITLE
autocompleteObservable don't work with objects

### ISSUE THREAD

**Issue by sancaruso** [Gbuomprisco/ng2-tag-input#166]
Hi,

I tried to use autocompleteObservable with object-tags but it don't work.
By example, I tried to change the request function in the demo by:

`public requestAutocompleteItems = (text: string) => {`
`    return Observable.of([{display:'hello',value:'hello'}]);`
`};`

but the value 'hello' is ignored.

**Comment by Gbuomprisco** [comment]
Fixed it in master, will be available soon

**Comment by Gbuomprisco** [comment]
Released :) reopen if still not working,  thanks!

**Comment by sancaruso** [comment]
I don't know how to reopen this issue.
The autocompleteObservable seems again not to work with objects, since version 0.8.4.

**Comment by sancaruso** [comment]
More precisely : I get an error
`TypeError: Cannot read property 'toString' of undefined`

**Comment by sancaruso** [comment]
Solved by adding [displayBy] in the tag-input-dropdown.
