### ISSUE TITLE
autocomplete options

### ISSUE THREAD

**Issue by sancaruso** [Gbuomprisco/ng2-tag-input#167]
Hi,

are there possibilities to limit the number of items appearing in autocomplete list, and/or to declare a minimum number of characters to enter before displaying the list?

Thanks,

**Comment by Gbuomprisco** [comment]
Hi, not at this time, but they're good candidate for being options, so I will have a look (maybe at the weekend)

**Comment by Gbuomprisco** [comment]
Both options have been added in the latest release :)
