### ISSUE TITLE
Value: Failed to load tag-input.template.html

### ISSUE THREAD

**Issue by mahmoudkassem92** [Gbuomprisco/ng2-tag-input#168]
I still get this error "Value: Failed to load tag-input.template.html"

even after adding this to packages object

    "ng2-tag-input": {
      "main": "dist/ng2-tag-input.bundle.js",
      "format": "cjs"
    },
    "ng2-material-dropdown": {
      "defaultExtension": "js",
      "main": "dist/ng2-dropdown.bundle.js",
      "format": "cjs"
    },
    "ng2-tag-input/modules/components/tag-input.template.html": {
      "defaultJSExtension": false
    }

**Comment by Gbuomprisco** [comment]
Hi @mahmoudkassem92, can you post more details of your configuration (ex. package.json)?

**Comment by mahmoudkassem92** [comment]
@Gbuomprisco do u mean the versions ?

**Comment by Gbuomprisco** [comment]
the dependencies, yes

**Comment by mahmoudkassem92** [comment]
"dependencies": {
    "@angular/common": "2.4.4",
    "@angular/compiler": "2.4.4",
    "@angular/core": "2.4.4",
    "@angular/forms": "2.4.4",
    "@angular/http": "2.4.4",
    "@angular/platform-browser": "2.4.4",
    "@angular/platform-browser-dynamic": "2.4.4",
    "@angular/platform-server": "2.4.4",
    "@angular/router": "3.4.4",
    "@types/webrtc": "0.0.21",
    "angular-2-local-storage": "1.0.0",
    "angular-confirmation-popover": "^2.1.2",
    "angular2-cookie": "1.2.5",
    "angular2-modal": "2.0.2",
    "angular2-toaster": "2.0.0",
    "bootstrap": "3.3.7",
    "core-js": "2.4.1",
    "jquery": "3.1.0",
    "malihu-custom-scrollbar-plugin": "3.1.5",
    "ng2-bootstrap": "1.1.14",
    "ng2-click-outside": "1.2.0",
    "ng2-tag-input": "^0.7.7",
    "rxjs": "5.0.1",
    "socket.io-client": "1.4.8",
    "ts-helpers": "1.1.1",
    "typings": "1.3.3",
    "webrtc-adapter": "2.1.0",
    "zone.js": "0.7.4"
  },
  "devDependencies": {
    "@angular/compiler-cli": "2.4.4",
    "@types/jasmine": "2.5.40",
    "@types/node": "6.0.42",
    "angular-cli": "1.0.0-beta.24",
    "codelyzer": "2.0.0-beta.4",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-jasmine": "1.0.2",
    "karma-remap-istanbul": "0.2.1",
    "protractor": "4.0.13",
    "ts-node": "1.2.1",
    "tslint": "4.3.1",
    "typescript": "2.0.10"
  }

**Comment by Gbuomprisco** [comment]
I see you are using angular-cli, not SystemJS; how come are you adding that configuration?

**Comment by mahmoudkassem92** [comment]
I am using them in the angular-cli isn't that possible ? and if so what is the alternative?

**Comment by Gbuomprisco** [comment]
angular-cli now works with Webpack (not SystemJS), see https://github.com/angular/angular-cli#webpack-update and https://medium.com/@jeff.boothe/angular-cli-meets-webpack-7c9b1a1e1e89.

**Comment by mahmoudkassem92** [comment]
Yes I do understand this I mean that you specified the problem for SystemJs but I am also having it although I am not using systemjs

**Comment by Gbuomprisco** [comment]
That configuration is only valid for SystemJS, so you can remove it (I don't even understand where you have defined a packages object then).

I started a new angular-cli project, run ng-serve, and this problem doesn't appear, so I assume it's an issue with your configuration (which I can't figure out without accessing all the files in your project)

**Comment by Gbuomprisco** [comment]
You are importing the module wrongly. You need to import this way:

```javascript
import { TagInputModule } from "ng2-tag-input";
```

Please read the readme better :) Closing issue.
