### ISSUE TITLE
Remove don't work with custom template

### ISSUE THREAD

**Issue by sancaruso** [Gbuomprisco/ng2-tag-input#169]
If I try to remove an item in custom template, it doesn't work.
(It is also the case in the demo.)

**Comment by Gbuomprisco** [comment]
True, that's a little outdates, I will update it :) (it will also need some tweak in the code as I need to pass the index to the template context)

**Comment by tonysparks** [comment]
@sancaruso try this:

```typescript
        <template let-item="item">
            <div>
                <span class="tag-label">
                    {{ item.value }}                
                </span>            
                <i class="fa fa-times tag-remove-label ng2-tag__remove-button"
                        (click)="input.removeItem(item, input.items.indexOf(item))">
                </i>
            </div>
        </template>
```

Notice the inclusion of `input.items.indexOf(item)`

**Comment by Gbuomprisco** [comment]
Thanks @tonysparks, that should be good as well. I'll add index to the template context to ease this soon :)

**Comment by Gbuomprisco** [comment]
The new version adds `index` as a variable in the template's context :)
