### ISSUE TITLE
Observable<Response> do not cover all situations

### ISSUE THREAD

**Issue by djleonskennedy** [Gbuomprisco/ng2-tag-input#170]
Hello i'm using service that returns Observable of custom type, due the fact that the library use Response interface drop down is empty.

is it possible to use any ?

Observable<Response> -> Observable<any>

https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/dropdown/tag-input-dropdown.component.ts#L76

**Comment by Gbuomprisco** [comment]
Yep, it makes sense :) I initially thought it for only http responses, but observables are so handy it could work with anything

**Comment by djleonskennedy** [comment]
@Gbuomprisco thank you :)

**Comment by Gbuomprisco** [comment]
Hey @djleonskennedy, the new release is out :)
