### ISSUE TITLE
[clarification] Populate items using an Observable

### ISSUE THREAD

**Issue by djleonskennedy** [Gbuomprisco/ng2-tag-input#171]
Hello @Gbuomprisco Could you clarify, can i use 
`[identifyBy]="'id'" [displayBy]="'name'"`
in this situation ?

```
public requestAutocompleteItems = (text: string): Observable<any> => {
    return this.someService.getData(text)
        .map(data => ({display: data.toDisplay, value: data.toValue}));
};
```
```
<tag-input [ngModel]="['@item']">
    <tag-input-dropdown 
      [autocompleteObservable]='requestAutocompleteItems'>
      </tag-input-dropdown>
</tag-input>
```

**Comment by djleonskennedy** [comment]
Yes it is

**Comment by weglinskit** [comment]
Hi @djleonskennedy, can you provide working example of combining identifyBy/displayBy with autocompleteObservable. I still have problems with observable structure respone (not showing autocomplete or showing but not adding to ngModel array).
Thanks in advance!

**Comment by Gbuomprisco** [comment]
Hi @weglinskit,

the identifyBy/displayBy do not affect the dropdown items (yet). It's in my todo list though :)
