### ISSUE TITLE
Add tags from controller?

### ISSUE THREAD

**Issue by waynechaw** [Gbuomprisco/ng2-tag-input#174]
As of now, tags are added when user interact with the UI. Is it possible to programmatically add tags from controller? For example, if I want to load some default tags in the input box on refresh.

**Comment by Gbuomprisco** [comment]
Hi @waynechaw,

Do you mean that you want to prepopulate the value of the form, or the items inside the input (cause you could just use the model)? Sorry but I don't get very well why :)

By the way, yes, you can use all the methods that `TagInputComponent' implements, here is a basic example:
```
<button (click)="myInput.appendNewTag('MyItem')">Add "MyItem"</button>
<tag-input #myInput></tag-input>
```

Look at https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/tag-input.ts for all the methods available

**Comment by waynechaw** [comment]
Yeah I meant populate input with tags already. Thanks for your suggestion.

**Comment by Gbuomprisco** [comment]
No problem :)
