### ISSUE TITLE
Overflow/scroll in items of dropdown

### ISSUE THREAD

**Issue by sancaruso** [Gbuomprisco/ng2-tag-input#176]
Hi,

As you can see in the picture below:
![image](https://cloud.githubusercontent.com/assets/25367750/22468026/331cbf04-e7c7-11e6-9b7f-a0b6528e71c2.png)
There is a little scroll bar near each item in the autocomplete dropdown. I tried to add some style like this:

`ng2-menu-item {`
`  overflow-y: hidden;`
`}`

but it didn't work.
For information, I use a template:
`        <template let-item="item" let-index="index">`
`          [{{tagTypeTitle(item.tagTypeId)}}] {{item.value}}`
`        </template>`

**Comment by Gbuomprisco** [comment]
Hi @sancaruso,

Yeah, someone raised a similar ticket I recall. What browser and OS are you using? I can't reproduce this on Sierra/Chrome

**Comment by sancaruso** [comment]
This is on Ubuntu, Chromium.

**Comment by Gbuomprisco** [comment]
Hi @sancaruso,

can you check if the latest version is affected? I can't reproduce

**Comment by Ardethian** [comment]
@sancaruso , have you solved it? I'm having the exact same issue.

**Comment by sancaruso** [comment]
Hi,
the problem disappeared, probably after an update but I don't know which... I an sorry that I can't help more...

**Comment by Gbuomprisco** [comment]
Hi @Ardethian,

are you using the latest version? I'd guess so, but who knows
