### ISSUE TITLE
Duplicate items in dropdown

### ISSUE THREAD

**Issue by troelssiggaard** [Gbuomprisco/ng2-tag-input#177]
I'm getting duplicate items in my dropdown when using autoComplete, Observables and a REST API. Not sure why it's not a problem with the GitHub example, but I've tried two different REST APIs and get the same exact results, of several duplicates in the list.

Example 1: Code I use instead of the GitHub example (public api):
```
  public requestAutocompleteItems = (text: string): Observable<Response> => {
    const url = `https://api.magicthegathering.io/v1/cards?name=${text}`;
    return this.http
      .get(url)
      .map(data => data.json().cards.map(item => item.name));
  };
```
I.e. searching for "Howlpack Alpha" in the above resourse should give 2 outputs, but I get 10 items in the dropdown.

Example 2: Code I use for my own site:
```
public requestAutocompleteItems = (text: string): Observable<any> => {
    const url = `http://localhost:1337/nodes/search/?query=${text}`;
    return this.http.get(url)
      .map(data => data.json().map(item => item.diagnose_text));
  };
```

The above examples give me different amounts of duplicates, depending on what I search for. Could you tell me if it's a bug or point me in the right direction?

**Comment by Gbuomprisco** [comment]
Hi @troelssiggaard,

have you tried the latest version? This issue should have been fixed - otherwise I'll have a look :)

**Comment by troelssiggaard** [comment]
Sorry for not trying the latest version and bothering you. This latest version works without duplicates. Thank you! :-)

**Comment by Gbuomprisco** [comment]
No problem :)
