### ISSUE TITLE
More relaxed Angular and RxJS version targeting

### ISSUE THREAD

**Issue by hheexx** [Gbuomprisco/ng2-tag-input#178]
I understand that you don't want to support older builds of angular but please use more relaxed version targeting because now after every patch version of angular we receive warinings in npm:

npm WARN ng2-tag-input@0.7.9 requires a peer of @angular/core@2.4.4 but none was installed.
npm WARN ng2-tag-input@0.7.9 requires a peer of @angular/common@2.4.4 but none was installed.
npm WARN ng2-tag-input@0.7.9 requires a peer of @angular/forms@2.4.4 but none was installed.
npm WARN ng2-tag-input@0.7.9 requires a peer of rxjs@5.0.1 but none was installed.

(we have 2.4.5 and rx 5.0.3 installed)

**Comment by MarkPieszak** [comment]
To go along with what Boris is saying, you don't need to be up'ing a libraries Angular/Rx dependencies unless you're actually **using** those features (related to those fix branches).

So you could very well have it as `^2.0.0` which most libraries do, that avoids all of this. Just trying to help :)

```
"devDependencies": {
    "@angular/core": "^2.0.0",
    "@angular/common": "^2.0.0",
```

**Comment by Gbuomprisco** [comment]
@MarkPieszak @hheexx definitely, sounds fair enough :)

**Comment by MarkPieszak** [comment]
Was just making sure, wasn't sure if you were using some of those features!
:)

**Comment by Gbuomprisco** [comment]
I'll probably have to specify some angular package more strictly as there are some breaking features with the animations, but for rx or other it is then definitely the case.

**Comment by hheexx** [comment]
In that case it may be better to specify that version after that breaking change for all packages. Like ^2.2.0 or ^2.3.0 - for all packages the same.
I'm not sure, maybe @MarkPieszak knows if there is any best practice about this?

**Comment by MarkPieszak** [comment]
Basically just the lowest common denominator 🚀 
Whatever lowest version works without breaking anything lol

**Comment by Gbuomprisco** [comment]
This should be fine with your project now if you use version 0.8.0 :)

**Comment by MarkPieszak** [comment]
Thank you! 🎈🎈
