### ISSUE TITLE
showDropdownIfEmpty seems to not working since the 0.7.8 version

### ISSUE THREAD

**Issue by mikabenali** [Gbuomprisco/ng2-tag-input#179]
Hi,

I've update to 0.7.8 and the showDropdownIfEmpty attribute do not work anymore.

`<tag-input-dropdown [showDropdownIfEmpty]="true" [autocompleteItems]="areaFilterOptions"</tag-input-dropdown>`

Do I missed something ?

**Comment by Gbuomprisco** [comment]
Hi @mikabenali,

No there is a bug indeed. Will be fixed when the PR is merged - but I'll need to complete it :|

**Comment by mikabenali** [comment]
Tanks you :)

**Comment by Gbuomprisco** [comment]
dupe https://github.com/Gbuomprisco/ng2-tag-input/issues/148 :)

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/185

**Comment by mikabenali** [comment]
It's working now, thx :)
