### ISSUE TITLE
UNMET PEER DEPENDENCY

### ISSUE THREAD

**Issue by FallenRiteMonk** [Gbuomprisco/ng2-tag-input#18]
Hy,

you have a UNMET PEER DEPENDENCY error in your current version.
Angular forms 0.1.1 requires angular2 version rc.3, but you have rc.4 as dependency.
Upgrading to forms 0.2.0 fixes the dependency issue, but breaks your test, even though everything seems to be working fine.
Downgrading to rc.3 fixes the issue also, without breaking the tests.

**Comment by Gbuomprisco** [comment]
Hi @FallenRiteMonk, thanks for opening the issue.

Was aware of the problem, I guess the best thing to do will be downgrading Angular for now as I was a bit struck by that tests issues.

**Comment by FallenRiteMonk** [comment]
I just had a look at the tests issue and I'm a bit confused by the test "TagInput should have 2 tags set by ngModel". Could you please tell me why you are looking at component.value, because if I output it to the console i get the following value "['Javascript', 'Typescript']" and I do not understad what that has to do with the amount of tags.
And if you also have a look at the example you can see that the tag-input has got two tags set with using ngModel, shouldn't therefor the test succeed? Can't it be that noting gets broken, but just the test is wrong?

**Comment by Gbuomprisco** [comment]
Actually I did not! Will have a look, thanks a lot :+1:

**Comment by Gbuomprisco** [comment]
Should be fixed with version 0.1.6 :)
