### ISSUE TITLE
Form values are inconsistent (sometimes strings, sometimes objects)

### ISSUE THREAD

**Issue by jooooel** [Gbuomprisco/ng2-tag-input#180]
When a new value is added to a tag-input, it's always added as an object `{ value: string, display: string }`. However, when a tag-input is prepopulated with an array of strings, those are not represented by an object, but by simple strings.

This is illustrated here: http://www.webpackbin.com/NkDu2JhPz
- Add a tag
- Click submit
- Check the logs.

The output (`this.form.value`) contains a mix of strings and objects.

```
{
    tags: [
        "Typescript",
        "Angular2",
        {
             display: "adasdasd",
            value: "adasdasd"
        }
    ]
}
```

Is there a way to get `this.form.value` to always output an array of strings?

Thank you, really like ng2-tag-input otherwise! :)

**Comment by Gbuomprisco** [comment]
Hi @jooooel,

for the sake of maximum customization, I guess I'll leave it as it is now. I understand though that this is an issue, and what I could do is to add an option to map every item once it has been added with only a few lines of code. I can also see many other uses for it.

Something like this:

```javascript
itemsMapper(item: TagModel) {
   return item.display; // or value
}
```

```html
<tag-input [itemsMapper]="itemsMapper"></tag-input>
```

Does it make sense?

**Comment by jooooel** [comment]
That would be great! Thank you :)

**Comment by altschuler** [comment]
While that works it would be super useful to have some sort of `plain` kind of options to force the values to always be plain strings. I'm using the tags input in multiple places so I'm forced to write a mapper function in all use cases.

Thank you very much for an awesome library! Much appreciate your effort :)

**Comment by Gbuomprisco** [comment]
Hi @jooooel and @altschuler,

I added a new option `modelAsStrings` in version 0.8.1 (defaults to `false`). Can you try it out and let me know? Reopen if still an issue :)
