### ISSUE TITLE
Problem with tag selection - onSelect event

### ISSUE THREAD

**Issue by JbAmph** [Gbuomprisco/ng2-tag-input#181]
Hi,

I have an issue with the onSelect event :
It is fired only the first time, but then it doesn't fire anymore when I want to select a tag. 
I had to force the focus on the tag-input in my onSelected event in order to make it work again.

Thanks

**Comment by Gbuomprisco** [comment]
Hi @JbAmph,

two things: which browser are you using? are you trying to select an item already selected? (cause it wouldn't fire). If you could paste some of the code would be helpful :)

**Comment by JbAmph** [comment]
Hi @Gbuomprisco,

I'm using Chrome. To be give you a simple example,  here's a sequence :

1. Click on [Tag]
2. Event onSelect is fired
3. Click somewhere else on <body> 
4. [Tag] loses focus
5. Click on (the same) [Tag]
6. Event onSelect is not fired

Here's the code :

**.html file**
`
<tag-input #input [(ngModel)]="listTags"
class="avr-grid-10 custom-tags"
[addOnBlur]="true"
[addOnPaste]="true"
[pasteSplitPattern]="' '"
[validators]="tagValidators"
[errorMessages]="errorMessages"
[placeholder]="'Tags'" [secondaryPlaceholder]="'Tags'"
[identifyBy]="'tag'"
(onSelect)="tagSelected($event)">
</tag-input>
`

**.ts file**
`tagSelected($event: Tag) {
this.selectedTag = $event;
console.log(this.selectedTag);
}` 

However, this sequence works

1. Click on [Tag]
2. Event onSelect is fired
3. Click on tag-input
4. [Tag] loses focus
5. Click on (the same) [Tag]
6. Event onSelect is fired

Thank you

**Comment by Gbuomprisco** [comment]
Will be fixed by https://github.com/Gbuomprisco/ng2-tag-input/pull/187

**Comment by Gbuomprisco** [comment]
Release is out, please reopen if still not OK :)

**Comment by JbAmph** [comment]
It works fine with v0.8.3 !

Thanks
