### ISSUE TITLE
AoT issue

### ISSUE THREAD

**Issue by altschuler** [Gbuomprisco/ng2-tag-input#182]
I'm using v0.7.9 and getting this error when compiling with AoT (using angular cli).

```
ERROR in Template parse errors:
Can't bind to 'index' since it isn't a known property of 'tag'. ("own)="handleKeydown($event, item)"
             (onTagEdited)="onTagEdited.emit(item)"
             [ERROR ->][index]="i"
             [attr.tabindex]="readonly ? -1 : 0"
             [class.readonly]="readonly""): TagInputComponent@16:13

```

It's weird because `TagComponent` _does_ have an `index` input (https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/tag/tag.component.ts#L60).

**Comment by l2fprod** [comment]
It compiles with `"angular-cli": "1.0.0-beta.28.3"` but fails with `"@angular/cli": "1.0.0-beta.30"`.

**Comment by Gbuomprisco** [comment]
Hi everyone, 

can you try the version 0.8.0? It is not under the tag `latest`, so you need to specify it :)

It is working on my local, not sure why that error, I just tried adding the modifier!

**Comment by l2fprod** [comment]
0.8.0 works `"@angular/cli": "1.0.0-beta.30"`
