### ISSUE TITLE
Feature Request: Custom class in custom items template

### ISSUE THREAD

**Issue by shyamal890** [Gbuomprisco/ng2-tag-input#183]
Depending on a property value in tag model would like to change the background of tag. 

Example:
```
<tag-input [ngModel]="['@item']" #input>
    <template let-item="item" [ngClass]="{'blue-background': true}"> <!-- ngClass HERE -->
        <span>
            <!-- YOU MAY ACTUALLY DISPLAY WHATEVER YOU WANT IF YOU PASS AN OBJECT AS ITEM -->
            item: {{ item.display }}
        </span>
        <span (click)="input.removeItem(item)" class="ng2-tag__remove-button">
            x
        </span>
    </template>
</tag-input>
```

**Comment by shyamal890** [comment]
Is there a hacky way I can achieve this currently @Gbuomprisco ?

**Comment by Gbuomprisco** [comment]
Hi @shyamal890,

No sorry, the current structure doesn't allow for it cause the styles are defined on the `tag` component

**Comment by shyamal890** [comment]
Any plans on adding this in near future?

**Comment by Gbuomprisco** [comment]
Possibly, yes, but am unable to give you a timeline at the moment :|

**Comment by Gbuomprisco** [comment]
This should now be possible by following the instructions at https://github.com/gbuomprisco/ng2-tag-input/blob/master/docs/custom-themes.md

**Comment by simonaberry** [comment]
I am not sure I follow how the custom-themes helps with 'conditional' formatting (i.e. ngClass / ngStyle) ??

**Comment by Gbuomprisco** [comment]
The custom theme can be used to add styles to a specific property. The custom template is responsible for adding your dynamic property to the tag. As I said, this is a hack, so might be far from perfect.
