### ISSUE TITLE
Add option to default tags trimming

### ISSUE THREAD

**Issue by Gbuomprisco** [Gbuomprisco/ng2-tag-input#186]
Asked by a user by email, I think it makes sense to add an option for this and have as default the current behaviour

**Comment by Access-Denied-IT** [comment]
+

**Comment by Gbuomprisco** [comment]
Hi @Access-Denied-IT,

I noticed that the model is not trimmed, it's just a visual thing: by default the browser does not show whitespaces (see http://www.w3schools.com/cssref/pr_text_white-space.asp).

I am sorry but I think I am not going to hack the CSS for showing the whitespaces: I even tried but really it was painful to look at. Maybe submit a PR if you know a good way of doing it?

**Comment by Gbuomprisco** [comment]
Update: I misunderstood the request - tags are not trimmed, but maybe they should be by default

**Comment by Gbuomprisco** [comment]
This should have been added :)
