### ISSUE TITLE
Bootstrap theme?

### ISSUE THREAD

**Issue by z--aszlo** [Gbuomprisco/ng2-tag-input#193]
I have built my project with bootstrap theme, can I remove the material styling / replace it with bootstrap?

**Comment by Gbuomprisco** [comment]
Hi @z--aszlo,

not at this time unfortunately. The only way would be extending the tag-input component, but I found it buggy in a few situations, so I cannot recommend it.

**Comment by Gbuomprisco** [comment]
Added a theme which contains the standard bootstrap colors :)
