### ISSUE TITLE
How to add same tags in one input dropdown?

### ISSUE THREAD

**Issue by Access-Denied-IT** [Gbuomprisco/ng2-tag-input#194]
Hello! 
Is there a function where you can add the same tags in the input? I have input and dropdown and how to make the same tags added.

**Comment by Access-Denied-IT** [comment]
Added tags don't disappear from the dropdown lists, when clicking again added the same tag.

are there any ideas ?

**Comment by Gbuomprisco** [comment]
Hi @Access-Denied-IT,

I will try find some time to look into this sometime this week

**Comment by Access-Denied-IT** [comment]
@Gbuomprisco, ok!

**Comment by Gbuomprisco** [comment]
Hi @Access-Denied-IT,

values in the autocomplete are now compared by value (so if you specify a different value - they'll be visible, they won't otherwise).

Please reopen if still an issue
