### ISSUE TITLE
Issues in IE browser

### ISSUE THREAD

**Issue by omprakash9** [Gbuomprisco/ng2-tag-input#195]
Hi,

Issue-1:

having an issue in IE browser, where the selected tags from the autocomplete dropdown
are not deleting on hitting the backspace, instead it changing the route of the application

Seems this scenario is working fine in chrome browser. Can you please check with the IE, we are having a lot issues.

Issue-2:(For both IE and chrome browser)

Css styles from the plugin for the autocomplete dropdown are not responsive, upon searching for the items the
autocomplete dropdown is not populating below the search box, even if I try to over ride the styles, 
the plug-in is not accepting them.

versions I'm using:
Angular 2.4.5,
ng2-tag-input 0.7.4
IE browser 11

**Comment by Gbuomprisco** [comment]
Hi @omprakash9,

Thanks for reporting, but unfortunately I cannot be of much help here: I don't have a Windows machine to get IE or Spark done well (but honestly, I pretty much focused on Chrome mostly and also support for other browsers is not the best, but I plan on improving this).

PRs would be greatly appreciated :)

**Comment by omprakash9** [comment]
Thanks for replying on my comment @Gbuomprisco ,

Our application is completely specific to IE browser
and we have to push our app to production in less than two months, So may I know is there a time frame 
that I can expect this two issues could be fixed?

**Comment by Gbuomprisco** [comment]
I see @omprakash9, but I am afraid I won't get ahold of a Window machine very soon. Would you be able to provide some PRs for these issues?

About the second issue, anyway, be aware that the components use Angular's emulated shadow DOM, and therefore your styles won't work - but it's not a bug - it's supposed to be like that. :)

**Comment by omprakash9** [comment]
I don't have any PRs at the moment.

For my second issue- is there away to override the CSS styles?

**Comment by Gbuomprisco** [comment]
No, there is not

**Comment by Gbuomprisco** [comment]
No, there is not

**Comment by omprakash9** [comment]
Okay, I will get in touch with you later, if I come up with any new issues.
Thank you @Gbuomprisco

**Comment by osahner** [comment]
Edge/IE11 Error

```
EXCEPTION: Error in ./*** class *** - inline template:1:0 caused by: Object doesn't support property or method 'doSave'
error_handler.js (54,1)
ORIGINAL EXCEPTION: Object doesn't support property or method 'doSave'
error_handler.js (56,1)
ORIGINAL STACKTRACE:
error_handler.js (59,1)
TypeError: Object doesn't support property or method 'doSave'
   at View_***.prototype.handleEvent_0 (Function code:1424:5)
   at Anonymous function (http://10.0.1.4:4200/vendor.bundle.js:117037:17)
   at Anonymous function (http://10.0.1.4:4200/vendor.bundle.js:19507:36)
   at SafeSubscriber.prototype.__tryOrUnsub (http://10.0.1.4:4200/vendor.bundle.js:9356:13)
   at SafeSubscriber.prototype.next (http://10.0.1.4:4200/vendor.bundle.js:9305:17)
   at Subscriber.prototype._next (http://10.0.1.4:4200/vendor.bundle.js:9247:9)
   at Subscriber.prototype.next (http://10.0.1.4:4200/vendor.bundle.js:9211:13)
   at Subject.prototype.next (http://10.0.1.4:4200/vendor.bundle.js:13697:17)
   at EventEmitter.prototype.emit (http://10.0.1.4:4200/vendor.bundle.js:19481:54)
   at NgForm.prototype.onSubmit (http://10.0.1.4:4200/vendor.bundle.js:26548:9)
   at Wrapper_NgForm.prototype.handleEvent (Function code:29:5)
   at View_EventDetailComponent2.prototype.handleEvent_0 (Function code:1422:3)
   at Anonymous function (http://10.0.1.4:4200/vendor.bundle.js:117037:17)
   at Anonymous function (http://10.0.1.4:4200/vendor.bundle.js:51797:9)
   at ZoneDelegate.prototype.invokeTask (http://10.0.1.4:4200/polyfills.bundle.js:643:13)
error_handler.js (60,1)
ERROR CONTEXT:
error_handler.js (63,1)
[object Object]
error_handler.js (64,1)
   {
      [functions]: ,
      __proto__: { },
      _nodeIndex: 0,
      _staticNodeInfo: { },
      _tplCol: 0,
      _tplRow: 1,
      _view: { },
      component: null,
      componentRenderElement: { },
      context: { },
      injector: { },
      providerTokens: [ ],
      references: { },
      renderNode: { },
      source: "./*** class *** - inline template:1:0"
   }

SCRIPT5022: Error: Error in ./*** class *** - inline template:1:0 caused by: Object doesn't support property or method 'doSave'
Subscriber.js (238,1)

```

**Comment by djleonskennedy** [comment]
hello, https://www.browserstack.com/accounts/subscriptions has free plan for open source.
you can contact with them and get free license for testing in all browsers

**Comment by omprakash9** [comment]
@Gbuomprisco 

Issue solved in latest version you can close this. Thanks!
