### ISSUE TITLE
can`t display list objects from remote api

### ISSUE THREAD

**Issue by OdaiTu** [Gbuomprisco/ng2-tag-input#196]
thank you
im facing a problem which is my json here from the server and im storing it in my app using observable like this

**my service :**

`getAllTags(): Observable <NewsGB[]> {
    return this._http.get('http://www.watania.info/getAllTags')
      .map((res: Response) => res.json());
  }`

**and here is my component :**

![image](https://cloud.githubusercontent.com/assets/12837840/22909581/7b3b316c-f25d-11e6-8b7d-734ad6ce70cb.png)

**and my html** 

`<tag-input [(ngModel)]="news.tags"
                                          name="tags">
                                          <tag-input-dropdown [autocompleteObservable]="tags">
                                          </tag-input-dropdown>
                                        </tag-input>`

![image](https://cloud.githubusercontent.com/assets/12837840/22909489/0cb16ebe-f25d-11e6-9b34-7a7e5c19c4b8.png)

no error but no dropdown menu shows up ?

**Comment by Gbuomprisco** [comment]
Hi @OdaiTu,

this won't work cause is wrongly written.

You're not paasing an observable, but a subscription. You'll need to omit the subscription, use a scoped method (so you need to use an arrow function) and pass to the input if the components getAllTags, and not tags.

Check out the examples carefully :)
