### ISSUE TITLE
Not Compiling for production in ionic2

### ISSUE THREAD

**Issue by himars3290** [Gbuomprisco/ng2-tag-input#199]
I implemented ng2-tag-plugin in my ionic project....i runs fine while i run in development mode....but when i try to run it in production mode it gives me  "Cannot read property 'DeleteIconComponent' of undefined, resolving symbol TagInputModule " error.

How can i solve this error....Please help....

**Comment by Gbuomprisco** [comment]
Hi @himars3290,

I'm closing this issue as others have been able to compile, please check out the related issues :) (or let me know if you have other issues)
