### ISSUE TITLE
webpack: Failed to compile. (angular-cli latest version)

### ISSUE THREAD

**Issue by osahner** [Gbuomprisco/ng2-tag-input#200]
```
angular-cli@1.0.0-beta.28.3
ng2-tag-input@0.8.5
typescript@2.1.6
zone.js@0.7.7
```

> ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is needed by the template compiler (position 5:22 in the original .ts file), resolving symbol Ng2DropdownModule in ***/node_modules/ng2-tag-input/dist/node_modules/ng2-material-dropdown/index.d.ts, resolving symbol TagInputModule in ***/node_modules/ng2-tag-input/dist/modules/ng2-tag-input.module.d.ts, resolving symbol TagInputModule in ***/node_modules/ng2-tag-input/dist/modules/ng2-tag-input.module.d.ts

**Comment by Gbuomprisco** [comment]
every angular-cli update breaks everything :( I will have a look soon :)

**Comment by zeus999** [comment]
@osahner For now you can use older version of ng2-tag-input. I am using version(0.4.4) and its working fine.

**Comment by Gbuomprisco** [comment]
Hi everyone,

could you try version 0.8.6? I have got it working with angular-cli 1.0.0-beta.32.3, and webpack 2.2.1.

**Comment by choYM** [comment]
version 0.8.6 works fine for me...
0.8.5 still have that error msg

**Comment by Gbuomprisco** [comment]
Use 0.8.6 :) Closing
