### ISSUE TITLE
npmjs.com latest package is 0.8.5

### ISSUE THREAD

**Issue by sichida** [Gbuomprisco/ng2-tag-input#205]
Hi,

It seems latest packager version on npmjs registery is `0.8.5`(which causes error with angular-cli) : https://www.npmjs.com/package/ng2-tag-input
You may want to update the latest version of your library.

I had an error with `0.8.5` which seems to be resolved in `0.8.6` : http://stackoverflow.com/questions/42368360/how-to-use-gbuomprisco-ng2-tag-input-with-angular-cli

Hope this can help you

**Comment by Gbuomprisco** [comment]
Added 0.8.7 to NPM :)
