### ISSUE TITLE
Bind a string from autocomplete

### ISSUE THREAD

**Issue by dharveshmydeen** [Gbuomprisco/ng2-tag-input#211]
I have pass array of items to autocomplete
after select the item it will bind as array of string like [{display:"",value:""}]
i need to bind it as a single string into [(ngModel)]......????

**Comment by Gbuomprisco** [comment]
Hi @dharveshmydeen,

checkout `modelAsStrings`. set it to `true` and you will be getting strings as model (if this is what you mean, otherwise please explain a little bit better)

**Comment by dharveshmydeen** [comment]
ya superbbbbb i have already Done it...! Thank you
