### ISSUE TITLE
Should work with latest Angular CLI (1.0.0-Beta.26)?

### ISSUE THREAD

**Issue by obosha** [Gbuomprisco/ng2-tag-input#213]
Trying to use with vanilla project created by Angular-CLI (1.0.0-beta.26) and I get the following error once I have imported TagInputModule -- any thoughts?

ERROR in Error encountered resolving symbol values statically. Only initialized variables and constants can be referenced because the value of this variable is
needed by the template compiler (position 5:22 in the original .ts file), resolving symbol Ng2DropdownModule in C:/git-vsonline/AngularCliStarter/node_modules/n
g2-tag-input/dist/node_modules/ng2-material-dropdown/index.d.ts, resolving symbol TagInputModule in C:/git-vsonline/AngularCliStarter/node_modules/ng2-tag-input
/dist/modules/ng2-tag-input.module.d.ts, resolving symbol TagInputModule in C:/git-vsonline/AngularCliStarter/node_modules/ng2-tag-input/dist/modules/ng2-tag-in
put.module.d.ts

**Comment by Gbuomprisco** [comment]
Hi @obosha,

is that Angular's version, or Angular cli's?

**Comment by obosha** [comment]
My apologies...   that was the version of NPM I am using.

The version of Angular-CLI I'm using is:  1.0.0-beta.26

**Comment by Gbuomprisco** [comment]
can you try version 0.8.6?

**Comment by obosha** [comment]
This works.  So...  apparently I had to specify 0.8.6 explicitly to get that version??  When I installed it an hour ago it gave me 0.8.5.  Did you just update it?

And thank you!  :)   Excited to use your component.

**Comment by Gbuomprisco** [comment]
it's not under the tag latest so it gives you an older version (as it was not sure if it worked) :)

**Comment by obosha** [comment]
Ha...   well, it got me past my problem anyway!  Thanks Giancarlo!
