### ISSUE TITLE
Keyboard codes for separator keys

### ISSUE THREAD

**Issue by obosha** [Gbuomprisco/ng2-tag-input#215]
In my testing, I can assign TAB, SPACE as a separator key, but I am not having success adding comma [44] or semi-colon [59]...  is there a known limitation there on those keys specifically?

**Comment by Gbuomprisco** [comment]
Hi @obosha,

no - there is not limitation really. Can you check the codes are right? I can see that comma is not 44, but 188.

**Comment by obosha** [comment]
Interesting, I will check.  The chart I got off Google said 44 for comma.
Do you have a link to the codes you're looking at?

**Comment by Gbuomprisco** [comment]
using https://css-tricks.com/snippets/javascript/javascript-keycodes

**Comment by obosha** [comment]
I was assuming ASCII codes, my bad!  Thanks Giancarlo, it works great!
