### ISSUE TITLE
Bug: Angular + webpack

### ISSUE THREAD

**Issue by NicolasHumann** [Gbuomprisco/ng2-tag-input#216]
Hi, I have the following issue.
Any tips ?

Unhandled Promise rejection: Animation parse errors:
- Unable to parse the animation sequence for "flyInOut" on the TagInputComponent component due to the following errors:
-- the provided :enter is not of a supported format
-- the provided :leave is not of a supported format ; Zone: <root> ; Task: Promise.then ; Value: Error: Animation parse errors:
- Unable to parse the animation sequence for "flyInOut" on the TagInputComponent component due to the following errors:
-- the provided :enter is not of a supported format
-- the provided :leave is not of a supported format

**Comment by Gbuomprisco** [comment]
Hi @NicolasHumann,

It's possible you're running an outdated version. Check the version the package.json.
