### ISSUE TITLE
How to add tag-input in to angular cli?

### ISSUE THREAD

**Issue by karthikkavin** [Gbuomprisco/ng2-tag-input#22]
I am new in angular 2 and i used angular cli. Can you advise how to build tag-input.
Thanks.

**Comment by Gbuomprisco** [comment]
Hi @karthikkavin! Honestly, I have never used angular-cli, but I will give it a try and let you know :)

**Comment by karthikkavin** [comment]
ok man thanks.

**Comment by karthikkavin** [comment]
i am new in angular 2 and start to learn.
you use autocomplete text box input?

**Comment by Gbuomprisco** [comment]
No, it has not been implemented yet but it will soon

**Comment by FallenRiteMonk** [comment]
I have it running using angular-cli beta 10, here is what I did after installing using npm:
add ```'ng2-tag-input/**/**.js'``` to the file `angular-cli-build.js` under vendorNpmFiles.
In the file `system-config.js` add ```'ng2-tag-input':'vendor/ng2-tag-input/index.js'``` to the `const map` and ```'ng2-tag-input': {
    format: 'cjs'
  }``` to the `const packages`
Then just import it as ```import { TagInput } from 'ng2-tag-input';``` in the components where its needed.

The rest should be clear and if you have more questions, just let me know and I'll try to help.
