### ISSUE TITLE
Keycodes bug & design issue

### ISSUE THREAD

**Issue by Ignasimg** [Gbuomprisco/ng2-tag-input#223]
On adding the comma keycode: 188 as a separator.
Hitting backspace also triggers the entrance.

This is probably a bug that'll be very nice to solve.

But as a sidenote and I feel that this might be even more important than the mentioned bug, using keycode as the parameter to choose whether to split or not is a bad design.
Since for the first it is system dependant and for the second (and this is my opinion though I feel will be shared by everyone) we are trying to split based on the character, not on the phisical key being pressed.

**Comment by Gbuomprisco** [comment]
Hi @Ignasimg,

the first is definitely a bug, will look into it.

About the second point, I understand why you disagree with the design. In principle, I basically inspired all the API from md-chips https://material.angularjs.org/latest/api/directive/mdChips.
I will look into this too, but in terms of priority it's not on the top of my list (as no one has complained yet except in this instance). Hope you understand.

**Comment by Gbuomprisco** [comment]
Hm, I don't seem able to reproduce anymore the first issue

**Comment by netopolit** [comment]
I can confirm and reproduce the backspace bug. The strange thing is if I put [separatorKeys] property in square brackets the bug disappears.

**Comment by Gbuomprisco** [comment]
Hi @netopolit,

it's actually wrong in the examples: you do need the brackets. Also, please notice that the behaviour recently changed: you can now choose separatorKeys or separatorKeyCodes. The first is not fully supported by all browsers I guess - so up to you which one to choose :)
