### ISSUE TITLE
demo doesn't work

### ISSUE THREAD

**Issue by sergot** [Gbuomprisco/ng2-tag-input#227]
looks like the demo doesn't work

`The reason you see this page is that the route is invalid. You have probably clicked an old Webpackbin link. Please notify the author about moving their BIN to the new version of Webpackbin. In the meantime you can continue to the old version.`

can't really reach the old version tho :(

**Comment by Gbuomprisco** [comment]
https://github.com/christianalfoni/webpack-bin/issues/226 Hopefully gets solved soon

**Comment by sergot** [comment]
Oh, didn't notice this one!

**Comment by Gbuomprisco** [comment]
Reopening for reference :)

**Comment by tfont** [comment]
+1 for this. Would be nice if fixed!

**Comment by SystemDisc** [comment]
Another +1 from me. What's the correct link? I can put in a PR if necessary

**Comment by Gbuomprisco** [comment]
Basically I need to put the code on the new webpackbin version: I've already spoken to its creator and the old links won't work. When I tried to create a new bin though I put webpackbin down. Maybe I'll need to put a demo elsewhere.

**Comment by SystemDisc** [comment]
Perhaps we can create a ng2-tag-input-demo repo, setup webpack, and use the [gh-pages-webpack-plugin](https://www.npmjs.com/package/gh-pages-webpack-plugin) plugin - or something similar.

**Comment by Gbuomprisco** [comment]
Long term yes, will definitely make sense. for now I re-created the bin here https://www.webpackbin.com/bins/-KeezCRlhoyASSV6j_oB. At the moment it is not working, I think it's still extracting the packages...let's see

**Comment by Gbuomprisco** [comment]
I retried today, no luck. For the time being a demo with limited options is here http://www.buompris.co/ng2-tag-input/
