### ISSUE TITLE
Autocomplete - don't show selected items

### ISSUE THREAD

**Issue by dougludlow** [Gbuomprisco/ng2-tag-input#229]
Is is possible under the current api to limit the autocomplete items by only those that are not currently selected? For example, if I populate the autocomplete items with a list of "apple", "orange" and "banana" and then choose "apple", the autocomplete list should only show "orange" and "banana".

**Comment by Gbuomprisco** [comment]
Hi @dougludlow,

no, not yet. :)

**Comment by dougludlow** [comment]
@Gbuomprisco thanks. I was able to come up with a workaround. I simply filter the autocomplete list based on the selected values before passing it into the `tag-input-dropdown`. Something like the following:

```html
<tag-input formControlName="tagInput" [modelAsStrings]="true" >
    <tag-input-dropdown [autocompleteItems]="autocompleteValues"></tag-input-dropdown>
</tag-input>
```

```typescript
import { reduce, includes } from 'lodash';
...
    protected tagInputControl: FormControl;

    protected get autocompleteValues(): string[] {
        return reduce(this.values, (result, value) => {
            let isUnique = !includes(this.tagInputControl.value, value);
            if (isUnique) result.push(value);
            return result;
        }, []);
    }
...
```
