### ISSUE TITLE
this._onChangeCallback is not a function

### ISSUE THREAD

**Issue by sh4ddow** [Gbuomprisco/ng2-tag-input#230]
Everything works great until I select item. Then it throw exception `this._onChangeCallback is not a function`.

Basic example doesnt work for me:

    <tag-input>
        <tag-input-dropdown
                [autocompleteItems]="['iTem1', 'item2', 'item3']"
                [appendToBody]="false">
        </tag-input-dropdown>
    </tag-input>

package.json:

    {
      "name": "blog",
      "version": "0.0.0",
      "license": "MIT",
      "angular-cli": {},
      "scripts": {
        "ng": "ng",
        "start": "ng serve",
        "test": "ng test",
        "pree2e": "webdriver-manager update --standalone false --gecko false",
        "e2e": "protractor"
      },
      "private": true,
      "dependencies": {
        "@angular/common": "^2.3.1",
        "@angular/compiler": "^2.3.1",
        "@angular/core": "^2.3.1",
        "@angular/forms": "^2.3.1",
        "@angular/http": "^2.3.1",
        "@angular/platform-browser": "^2.3.1",
        "@angular/platform-browser-dynamic": "^2.3.1",
        "@angular/router": "^3.3.1",
        "core-js": "^2.4.1",
        "ng2-auto-complete": "^0.10.9",
        "ng2-tag-input": "^0.8.8",
        "rxjs": "^5.0.1",
        "ts-helpers": "^1.1.1",
        "zone.js": "^0.7.2"
      },
      "devDependencies": {
        "@angular/compiler-cli": "^2.3.1",
        "@types/jasmine": "2.5.38",
        "@types/node": "^6.0.42",
        "angular-cli": "1.0.0-beta.28.3",
        "codelyzer": "~2.0.0-beta.1",
        "jasmine-core": "2.5.2",
        "jasmine-spec-reporter": "2.5.0",
        "karma": "1.2.0",
        "karma-chrome-launcher": "^2.0.0",
        "karma-cli": "^1.0.1",
        "karma-jasmine": "^1.0.2",
        "karma-remap-istanbul": "^0.2.1",
        "protractor": "~4.0.13",
        "ts-node": "1.2.1",
        "tslint": "^4.3.0",
        "typescript": "~2.0.3"
      }
    }

![exception](https://cloud.githubusercontent.com/assets/17151020/23626902/d8560c8a-02ae-11e7-9f77-e3aa3b5c1d25.png)

**Comment by Gbuomprisco** [comment]
Hi @sh4ddow,

you need to define a model.
