### ISSUE TITLE
Angular universal prerendering fails due to dependencies on KeyboardEvent

### ISSUE THREAD

**Issue by markphillips100** [Gbuomprisco/ng2-tag-input#238]
I have an angular 2 universal project similar to [https://github.com/MarkPieszak/aspnetcore-angular2-universal](https://github.com/MarkPieszak/aspnetcore-angular2-universal).  I've added the module which works fine with universal disabled.  When I enable the universal behaviour the pre-rendering is failing with the following error:

"Prerendering failed because of error: ReferenceError: KeyboardEvent is not defined"

The type is defined in lib.dom.d.ts which I assume is unavailable to the node compilation on the server.  Any ideas how to get the module to play nice when rendering server-side?

**Comment by Gbuomprisco** [comment]
I should implement DI swapping as described here https://github.com/angular/universal/blob/master/DOCUMENTATION.md#diswap -  I am afraid there is not much doable on your side at the moment

**Comment by Gbuomprisco** [comment]
Hi @markphillips100,

I hacked the issue a little. I am afraid some event might still be in `ng2-material-dropdown`. Can you check version 0.9.5 and see if it works?

**Comment by markphillips100** [comment]
That worked fine for me.  Thank you very much.

**Comment by Gbuomprisco** [comment]
cool :) closing issue
