### ISSUE TITLE
Cannot pass data to tag-input-dropdown

### ISSUE THREAD

**Issue by ygamretuta** [Gbuomprisco/ng2-tag-input#239]
probably a thing on scopes. how exactly do you do this:

> "Make sure you retain the scope of your class or function when using this property. It can be used to popuplate the autocomplete with items coming from an async request."

I need some data from the parent component. How do I access them from the `autocompleteObservable` callback  of the `tag-input-dropdown` ?

**Comment by Gbuomprisco** [comment]
Hi @ygamretuta,
do you have some code that can help me understand what you mean better?
