### ISSUE TITLE
Dropdown positioning acting weird

### ISSUE THREAD

**Issue by arturocr** [Gbuomprisco/ng2-tag-input#244]
I've noticed a weird issue with the positioning of the dropdown when there are autocomplete items, I start typing and it starts to filter the items, but at a specific point the dropdown stays away of the input field even when there are just two options, if I hover the dropdown with the mouse or continue typing the position gets fixed.
Here is an example of the problem:
![screen recording 2017-03-12 at 01 19 am](https://cloud.githubusercontent.com/assets/390770/23829886/7f23a11e-06c2-11e7-9119-b05dcf5cf6c1.gif)

**Comment by Gbuomprisco** [comment]
Publishing a new version soon for this

**Comment by arturocr** [comment]
Great, thanks @Gbuomprisco
