### ISSUE TITLE
addOnBlur breaks autocomplete selection

### ISSUE THREAD

**Issue by neilharding** [Gbuomprisco/ng2-tag-input#248]
Tested this with version 0.9.5

When setting addOnBlur to true and with autocomplete options supplied ... when I start typing and it matches one or more autocomplete and I either move the mouse cursor down to select one or I use the down arrow keys to select one, the autocomplete dropdown disappears and my input it cleared.

Looking at the code it seems like the this.inputForm.onBlur is firing because focus is placed on the autocomplete dropdown? I'm seeing similar behavior with clearOnBlur (input it wiped out when I try to select an autocomplete item - but in this case the autocomplete dropdown stays open)

**Comment by Gbuomprisco** [comment]
Hi @neilharding,

Thanks for reporting - I will have a look!

**Comment by Gbuomprisco** [comment]
Hi @neilharding,

I changed it so if the autocomplete is open, the two events above won't fire. It's the only reasonable way I'd found. Let me know if works with you.

**Comment by neilharding** [comment]
Works perfect now! Thanks for all your work on this component... it's pretty awesome.

**Comment by Gbuomprisco** [comment]
Thanks :)

**Comment by AkanshaS** [comment]
Hi,

I am facing the same issue.
When i move the cursor away from the input field , the drop down disappears.
