### ISSUE TITLE
[Bug] [Seems-fixed] One-way bound '[ngModel]' changes when adding a new tag

### ISSUE THREAD

**Issue by djrr94** [Gbuomprisco/ng2-tag-input#25]
Hello, I think I found a bug.

Imagine that you have tag-input in your form with one-way bound `[ngModel]=myarray`.

Case 1:
Load the page and add a new tag, this tag adds to this one-way bound model. That's not correct behavior. The correct behavior is that tag should only add to form's.value.name, but ngModel should stay unchanged.

Case 2:
Load the page and delete some tag, the ng-model stays unchanged (that's correct) and that tag is removed in the form's array only (that's correct too).

After one tag is removed, you can add a new tag and that new tag won't add to the ngModel (that's correct) and only adds to the form's model (that's correct too).

So I think there could be a little bug in your code, with ngModel binding to a tag's input text input. It's fixed when you delete some tag and then add new, so I think somewhere in that delete function is declared something that's missing initially.

You can see the problem [here](http://www.webpackbin.com/4yQjk1RD-).

Thank you so much for your help!

**Comment by djrr94** [comment]
I think I found a fix, I wanted to PR but I haven't found `/dist/ng2-tag-input.bundle.js` file, so I can paste my solution here.

In this file, replace `TagInput.prototype.addItem` function with this:


`TagInput.prototype.addItem = function (isFromAutocomplete) {
	        if (isFromAutocomplete === void 0) { isFromAutocomplete = false; }
	        var item = this.setInputValue(this.form.value.item);
	        var isDupe = this.items.indexOf(item) !== -1;
	        var isValid = this.form.valid &&
	            isDupe === false &&
	            !this.maxItemsReached &&
	            ((isFromAutocomplete && this.onlyFromAutocomplete === true) || this.onlyFromAutocomplete === false);
	        if (isValid) {
	            this.items = this.items.filter(function (_item) { return _item });
	            this.items.push(item);
	            this.onAdd.emit(item);
	        }
	        this.setInputValue('');
	    };`


The trick is in this filtering array function on item add:

`this.items = this.items.filter(function (_item) { return _item });`


With my not so much experience with javascript I assume that it can be problem with some reference, this should filter the array and delete the reference.

I tested it and it seems it works like a charm now.

**Comment by Gbuomprisco** [comment]
Hi! I see the issue, If you want to submit a PR, have a look at ./components/tag-input.ts. That is the source file. Otherwise I'll release a fix soon :)

**Comment by Gbuomprisco** [comment]
PR https://github.com/Gbuomprisco/ng2-tag-input/pull/26

**Comment by Gbuomprisco** [comment]
Published a version that should fix this! Let me know :)
