### ISSUE TITLE
Cannot read property 'trim' of undefined

### ISSUE THREAD

**Issue by ventouris** [Gbuomprisco/ng2-tag-input#250]
```
<div class="col-md-8">
      <tag-input name="partners" [(ngModel)]=addFormProductPartners theme='bootstrap' [onlyFromAutocomplete]="true">
              <tag-input-dropdown [showDropdownIfEmpty]="true" [autocompleteItems]=partners [displayBy]="'name'">
             </tag-input-dropdown>
      </tag-input>
</div>
```

`partners` is a list of objects with "id" and "name" as keys and `addFormProductPartners` is an empty list of the same projects as Partner[].

Dropdown with the available partners are show ok, but when I click on one of them, I have the above error.

**Comment by Gbuomprisco** [comment]
Hi @ventouris,

are you running by any chance the latest version released yesterday? (I thought I'd fixed this) :)

**Comment by ventouris** [comment]
@Gbuomprisco Changelog file has 0.7.0 as the latest. I installed it earlier today via npm..

If I add [trimTags]="false" on tag-input, the problem solved, but then I can add only one item from the dropdown. Second click doesn't make anything at all@Gbuomprisco Changelog file has 0.7.0 as the latest. I installed it earlier today via npm..

**Comment by Gbuomprisco** [comment]
Try
```
<tag-input name="partners" [(ngModel)]="addFormProductPartners" theme='bootstrap' [onlyFromAutocomplete]="true">
              <tag-input-dropdown [showDropdownIfEmpty]="true" [autocompleteItems]="partners" [displayBy]="'name'" [identifyBy]="'id'">
             </tag-input-dropdown>
      </tag-input>
```

Not sure if you need `showDropdownIfEmpty`?

**Comment by ventouris** [comment]
EXCEPTION: Error in ./Ng2MenuItem class Ng2MenuItem - inline template:0:0 caused by: tag[this.identifyBy].trim is not a function

Now I have the above error

**Comment by Gbuomprisco** [comment]
Can you stringify the id?

**Comment by ventouris** [comment]
The Id is just an increment integer from the db, that I need to update later the object. Here is an example of the Partner object:
```
{ "id": 1, "name": "Matilda Fay", "email": "elwin.goodwin@gmail.com", "phone": "917.616.4930 x442", "address": "25987 Lamar Square Apt. 075\nLittelberg, FL 48864-3428", "created_at": "1973-12-22 07:04:24", "updated_at": "1971-11-04 13:59:36" }
```

Data are fake through Faker in Laravel.

**Comment by Gbuomprisco** [comment]
I don't seem able to track down this specific code - as the fix deployed it should prevent from trimming ints. If you could debug the line, and maybe check out what is the runtime value of `tag[this.identifyBy]` it would be great. I'll probably have a look this evening. :)

**Comment by ventouris** [comment]
Will try to do it later today or tomorrow. Would be nice if you just keep this issue open until then :)

**Comment by Gbuomprisco** [comment]
Sure :) Just to be sure, can you check you are running version 0.9.5? (check package.json). That code does seem like coming from 0.9.4 (buggy)

**Comment by ventouris** [comment]
I have this on package.json 

```
"_from": "ng2-tag-input@latest",
  "_id": "ng2-tag-input@0.9.2",
  "_inCache": true,
  "_location": "/ng2-tag-input",
  "_nodeVersion": "7.5.0",
```

It seems npm has a far older version than I thought.

**Comment by Gbuomprisco** [comment]
https://www.npmjs.com/package/ng2-tag-input marks 0.8.5 as latest. Maybe try force the version :)
