### ISSUE TITLE
Autocomplete dropdown doesn't hide

### ISSUE THREAD

**Issue by xuko** [Gbuomprisco/ng2-tag-input#253]
Hello I'm trying to add a tag input with autocomplete, and I want to show dropdown clicking the input. I tried set showDropdownIfEmpty to 'true'.
But when I click outside the dropdown it doesn't hide. I don't know if it's bug or a new feature, but I think this must be the default Behavior.
There's any way to get this.

Thanks

**Comment by Gbuomprisco** [comment]
Hi @xuko,

mhm, I am just trying it out and it does hide. What browser are you using?

**Comment by xuko** [comment]
@Gbuomprisco Google chrome Versión 56.0.2924.76 (64-bit)
Maybe could be because It is inside a modal
I tried outside and it works

**Comment by Gbuomprisco** [comment]
Oh yeah, very much possible

**Comment by xuko** [comment]
Oh thank you very much it worked. very useful. I close it
