### ISSUE TITLE
Tags are editable in IE 11.0

### ISSUE THREAD

**Issue by ui9** [Gbuomprisco/ng2-tag-input#256]
HI,

I was trying to prevent tags being editable on clicking the tags, by setting editable to false like:

        [editable]='false'
        (onTagEdited)="onTagEdited($event)"

and method has:

  public onTagEdited(event: any) {
   event.stopPropagation();
  }

can you please recommend me with some example/suggestion?

**Comment by Gbuomprisco** [comment]
By default, it is false, so just don't define it (nor the event)

**Comment by ui9** [comment]
I tried by not defining it as well, it did work though! that's why I tried like mentioned above

**Comment by omprakash9** [comment]
Hi @Gbuomprisco ,

In your demo link, the basic component tags are not editable in IE and I know that by default event is false.
So do you have an example for the one which you used for in demo?

**Comment by Gbuomprisco** [comment]
Hi @omprakash9,

which example are you talking about?

**Comment by omprakash9** [comment]
url: http://www.buompris.co/ng2-tag-input/
In the above url check the first one (Basic component)

**Comment by Gbuomprisco** [comment]
I'm sorry I don't understand the issue here :) If you need to set the tags as editable, use [editable]='true' (just like in the examples).

**Comment by omprakash9** [comment]
In IE tags are editable by default, I want tags to not editable on double click. so can you please provide me some suggestions on that

**Comment by Gbuomprisco** [comment]
@omprakash9 it's a big - but it's not fixed - I am not aware of a workaround. Not running a Windows machine makes it more difficult.

**Comment by omprakash9** [comment]
@Gbuomprisco 
Oh okay! Thanks for your reply :)

**Comment by omprakash9** [comment]
Hi @Gbuomprisco,

I found that in IE 11, when we double/single click on the tag "contenteditable" is becoming true, where it was allowing the user to edit the tags on double clicking.

Also there was an additional class is adding, which is class="tag--editing"

Please see my attached pics, one is before clicking the the tag other one is after clicking the tag.
So, i think if we can able to prevent on adding these two things. we can fix this issue and I'm not sure though!
![eee](https://cloud.githubusercontent.com/assets/25313812/24217738/38c651c8-0f17-11e7-82e7-2d370b104e4f.JPG)
![eeeeee](https://cloud.githubusercontent.com/assets/25313812/24217739/38dba564-0f17-11e7-904c-290e89786261.JPG)

**Comment by Gbuomprisco** [comment]
@omprakash9,

I'm not sure but it's possible that IE doesn't care the value given to contenteditable, if it is set to anything, it becomes editable. I'll explore this a bit more

**Comment by omprakash9** [comment]
@Gbuomprisco ,

When I did changed the span class to div in DOM Explorer in IE then it was working fine, But I'm not sure whether it's a right way of doing it, If Yes I'm not sure where exactly need to change it in plugin or in my HTML code. However I tried either way of changing it, but no luck from my end

**Comment by Gbuomprisco** [comment]
Probably in the plugin, I'll try changing to a div :)

**Comment by omprakash9** [comment]
Okay thanks!

**Comment by omprakash9** [comment]
Hi @Gbuomprisco ,

I updated to 1.0.0-beta version like you mentioned in my other issue #290, but this issue is still exists.

**Comment by Gbuomprisco** [comment]
The element is definitely a div now, so must not have been the issue

**Comment by Gbuomprisco** [comment]
version 1.0.1 should address this - but also updates the package to angular 4. Not sure you'll be able to run it right away?

**Comment by omprakash9** [comment]
I'm still in 1.0.0-beta version, i saw that this issue is now fixed. Thanks

**Comment by Gbuomprisco** [comment]
ok :)
