### ISSUE TITLE
Cannot press enter to add new tag when autocomplete opens

### ISSUE THREAD

**Issue by SystemDisc** [Gbuomprisco/ng2-tag-input#257]
If for example, you have a tag input with autocomplete enable, one of the autocomplete strings is `Ruby`, and the user wants to add the tag `Rub`, they cannot. If you type `Rub`, the autocomplete dropdown will open, and pressing enter does nothing. Also, if you select something in the autocomplete dropdown (down arrow), there's no way to unselect everything (up arrow past top or escape, for example).

**Comment by Gbuomprisco** [comment]
@SystemDisc did you set the option [onlyFromAutocomplete] to true?

**Comment by SystemDisc** [comment]
No, feel free to try it on your demo page: http://www.buompris.co/ng2-tag-input/

<img src="http://i.imgur.com/ixXHIpj.gif">

**Comment by SystemDisc** [comment]
You also cannot type `Ruby` and press enter. You have to have to option in the autocomplete dropdown selected to add the tag.

**Comment by Gbuomprisco** [comment]
True - I can reproduce. Very strange, I'll have a look soon

**Comment by SystemDisc** [comment]
I'm assuming the dropdown gets focus in some way when it appears. I think the input box should remain focused and that pressing up past the first item or escape should deselect anything in the dropdown and return focus to the input.

**Comment by Gbuomprisco** [comment]
I thought the same but the input isn't losing its focus (you can indeed move the cursor) so it may be something else. I noticed the submit event isn't being fired from the input.

**Comment by SystemDisc** [comment]
Probably this: https://github.com/Gbuomprisco/ng2-material-dropdown/blob/78f30347b00baff901ac2aaa0896cfbce1c69460/src/modules/components/menu/ng2-dropdown-menu.ts#L157

**Comment by Gbuomprisco** [comment]
Exactly! :| had just tracked it down

**Comment by SystemDisc** [comment]
Also, the way your binding to things like `keydown` don't really fall inline with the "best practices" for Angular2. You should probably use `(keypress)="doSomething($event)"` instead of messing with `nativeElement`.

http://angularjs.blogspot.com/2016/04/5-rookie-mistakes-to-avoid-with-angular.html

**Comment by Gbuomprisco** [comment]
The issue isn't nativeElement, but calling the DOM functions directly. If you use the Renderer, then you should be fine. Also, those events are called on window and document, not DOM elements the component defines. I mean - the code can be improved, by no means. Just I don't think the case you mention is applicable in this specific situation (or is it and I am misunderstanding)

**Comment by SystemDisc** [comment]
No, I just mean that in general there are better ways to do this stuff that more closely follows the "best practices" of how people code in Angular2. If I have time, I'll help with some PRs.

**Comment by Gbuomprisco** [comment]
that'd be awesome :)

**Comment by Gbuomprisco** [comment]
Hi @SystemDisc ,

version 0.9.8 should address this. Let me know :)
