### ISSUE TITLE
Not working in Separate template file(.html) 

### ISSUE THREAD

**Issue by yug95** [Gbuomprisco/ng2-tag-input#258]
while we shift the code in some external reference html file it throwing exception .
"**EXCEPTION: Error in ./Ng2MenuItem class Ng2MenuItem - inline template:0:0 caused by: this._onChangeCallback is not a function"**

**ORIGINAL EXCEPTION: this._onChangeCallback is not a function.**

**Comment by Gbuomprisco** [comment]
The function suggests you aren't defining an ngModel. Please maybe attach some code
