### ISSUE TITLE
Add classnames and/or remove generated attribute CSS selectors to simplify re-styling

### ISSUE THREAD

**Issue by saschwarz** [Gbuomprisco/ng2-tag-input#259]
An enhancement rough idea... I needed to make some simple styling changes for my application and it felt like subclassing (and the inability to use that to style the dropdown) was a "big hammer".

I started playing around with styling via CSS (Sass specifically) and it looks like if a few classes where added and generated attributes weren't used in the current style selectors most changes could be made with a global (or local) stylesheet.

Here's an existing selector:

    .default.ng2-tag-input--focused[_ngcontent-bqi-45] {
        border-bottom: 2px solid #2196F3;
    }

To get enough specificity to override the existing styles here is an example selector I created:

    tag-input .ng2-tag-input.default.ng2-tag-input--focused[tabindex] {
        border-bottom: 2px solid color($colors, primary);
    }

I had to add the outer element and replace the generated attribute with the `tabindex` attribute to make it more specific. If a class name was in the original selector I believe adding only the outer element would have been sufficient for application overrides.

Just a thought.

**Comment by Gbuomprisco** [comment]
Hi @saschwarz,

the reason why some attrs are generated is due to Angular's emulation of Shadow DOM. It is there for good reasons :) I am not yet aware of any nice ways that allow custom styling unfortunately, I expect Angular to make it possible soon.

**Comment by Gbuomprisco** [comment]
This will likely be possible soon https://github.com/Gbuomprisco/ng2-tag-input/pull/281

**Comment by Gbuomprisco** [comment]
This should now be possible by using mixins
