### ISSUE TITLE
"404 template" not found when you use _ng_ instead of _SystemJS_

### ISSUE THREAD

**Issue by aleixmorgadas** [Gbuomprisco/ng2-tag-input#260]
The library has a strange behavior when I use `ng 1.0.0-rc.1`.

The application cannot figure it out where the templates are located and browser returns this error log.
```
GET domain.dev/tag-input.template.html [HTTP/1.1 404 Not Found 4ms]
GET domain.dev/icon.html [HTTP/1.1 404 Not Found 23ms]
GET domain.dev/tag-input-form.template.html [HTTP/1.1 404 Not Found 19ms]
GET domain.dev/tag.template.html [HTTP/1.1 404 Not Found 14ms]
GET domain.dev/tag-input-dropdown.template.html [HTTP/1.1 404 Not Found 14ms]
```

Inspecting the library implementation, I think that it could be due a missing field at `@Component()`.

I will make a Pull request in case that it solves the issue

**Comment by aleixmorgadas** [comment]
Therefore, when compiling with `ng build --prod --aot` it returns
```
ERROR in Template parse errors:
'tag-input' is not a known element:
1. If 'tag-input' is an Angular component, then verify that it is part of this module.
2. If 'tag-input' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message
```
How could I help?

**Comment by StickNitro** [comment]
I am getting this error also, does anyone know how to fix please?

I am using "ngx-chips": "^1.5.0", if that helps

**Comment by Gbuomprisco** [comment]
are you using system js? If so, it's not supported
