### ISSUE TITLE
how to use Angularfire2 list as autocomplete 

### ISSUE THREAD

**Issue by juntaforce** [Gbuomprisco/ng2-tag-input#265]
How to use angularfire2 observable list instead of http observable to using itemsAsObjects array  ??

**Comment by Gbuomprisco** [comment]
@juntaforce,

the component works with any kind of observable. Map the items accordingly before subscribing - define your keys and values (identifyBy and displayBy) and your list will render.

**Comment by juntaforce** [comment]
`import { Component } from '@angular/core';
// import { NgForm } from '@angular/forms';
import { Observable } from 'rxjs';
import 'rxjs/add/operator/mergeMap';
import { Http, Response } from '@angular/http';
import { NavController } from 'ionic-angular';
import { FormControl } from '@angular/forms';
import { UserData } from '../../providers/user-data';
import * as firebase from 'firebase';
import { FileUploader } from 'ng2-file-upload';
import { UploadImagesService } from '../../providers/upload-images.service';
import {Validators, FormBuilder, FormGroup } from '@angular/forms';
import {AngularFire, FirebaseListObservable} from 'angularfire2';

@Component({
  selector: 'page-user',
  templateUrl: 'signup.html'
})
export class SignupPage {
  

  uploader:FileUploader;
  isDropZoneOver:boolean = false;
  isEnabledUpload: boolean = true;

  private CreatePost : FormGroup;
 
  items: FirebaseListObservable<any>;

  Date: String = new Date().toLocaleString();
  constructor(
    public navCtrl: NavController,
    public userData: UserData,
    public uploadImagesService: UploadImagesService,
    public formBuilder: FormBuilder,
    public af: AngularFire
    
  ) {
    this.uploader = new FileUploader({url: URL+"/VARTOBEPASSEDWITHFILE"});

    this.CreatePost = this.formBuilder.group({
      title: ['', Validators.required],
      content: ['', Validators.required],
      category: ['Array<any>', Validators.required],
      tags: [''],
    });
  }

  filtered = ['Array<any>'];

    itemsAsObjects = [{id: 0, name: 'Angular'}, {id: 1, name: 'React'}];

    // autocompleteItems = ['Item1', 'item2', 'item3'];

    autocompleteItems = [
        {name: 'Item1', $key: '0'},
        {name: 'item2', $key: '1'}
    ];

  public requestAutocompleteItems = (text: string) : Observable<Response> => {
     var tags =  this.af.database.list('/Tag')
    .flatMap(snaps => snaps.json().items.map((item:any) => item.full_name));
    
    return serkan;
    }`
