### ISSUE TITLE
[HELP]: Is there any property that is used for data-binding to the element's text.

### ISSUE THREAD

**Issue by anrepppp** [Gbuomprisco/ng2-tag-input#267]
@Gbuomprisco 
This is such a great plugin, with angular2 work. Thanks for your great work. I have a requirement to update the tagsinput box with a string. Note, this value is not a token it's just a string that i need to update from a different component. Is there any property similar to 
**text** from ngTagsInput https://github.com/mbenford/ngTagsInput/blob/master/src/tags-input.js plugin.
I know we have displayBy but it's only used for displaying the value that we are getting from response.

**Comment by Gbuomprisco** [comment]
Hi @anrepppp, thanks.

If I understand correctly, you want to bind a value to the input text. If so, at this time there's nothing that allows it. But I can see the use-case and I guess it's candidate for another property :) Can't give you a timeline though - so many bugs that have priority

**Comment by anrepppp** [comment]
Yeah, you are right and thanks for your quick response.  No problem.

**Comment by anrepppp** [comment]
Any thing that helps from this reference:

https://github.com/mbenford/ngTagsInput/blob/master/src/tags-input.js

**Comment by anrepppp** [comment]
@Gbuomprisco 

I am sorry to interrupt you

**Comment by Gbuomprisco** [comment]
Will be added in https://github.com/Gbuomprisco/ng2-tag-input/pull/275

**Comment by Gbuomprisco** [comment]
Hi @anrepppp,

version 0.9.8 should address this (the property is [inputText]). Let me know :)

**Comment by anrepppp** [comment]
Excellent, i updated to the latest version and trying now.

**Comment by anrepppp** [comment]
Awesome, it's working. Thank you so much,  @Gbuomprisco  it helps me. Thanks for taking your time to add this feature. Please let me know if you need any help in future.

**Comment by Gbuomprisco** [comment]
Glad it works :+1:
