### ISSUE TITLE
ng2-tag-input (dropdown) not working on bootstrap modal !

### ISSUE THREAD

**Issue by Access-Denied-IT** [Gbuomprisco/ng2-tag-input#268]
ng2-tag-input (dropdown) not working on bootstrap [modal](https://valor-software.com/ng2-bootstrap/#/modals)

Ps:When the modal window is open, the (ng2-tag-input) dropdown list is displayed in the background of the modal! 
Psss:I think the problem is in the dropdown styles

**Comment by Gbuomprisco** [comment]
Sorry this is a dupe https://github.com/Gbuomprisco/ng2-tag-input/issues/172
