### ISSUE TITLE
Invalid icon.html markup

### ISSUE THREAD

**Issue by altschuler** [Gbuomprisco/ng2-tag-input#270]
I believe the extra `</g>` tags at [icon.html#L2](https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/icon/icon.html#L2) are faulty?

Whenever I try to add a tag I get the following error:
```
DeleteIconComponent.html:2 ERROR DOMException: Failed to execute 'setAttributeNS' on 'Element': '' is an invalid namespace for attributes.
View_DeleteIconComponent_0 @ DeleteIconComponent.html:2proxyClass
...
```

Note that I'm using Angular 4.0.0-rc.4

**Comment by Gbuomprisco** [comment]
Hi @altschuler,

will be fixed soon :) (it's in PR, I just need to test more)

**Comment by Gbuomprisco** [comment]
Hi @altschuler,

version 0.9.8 should address this. Let me know :)

**Comment by altschuler** [comment]
@Gbuomprisco Thanks so much! Unfortunately I'm still getting an error, though slightly different:

```
"Error: Failed to execute 'setAttributeNS' on 'Element': '' is an invalid namespace for attributes.
    at Error (native)
    at EmulatedEncapsulationDomRenderer2.webpackJsonp../node_modules/@angular/platform-browser/@angular/platform-browser.es5.js.DefaultDomRenderer2.setAttribute (http://localhost:4200/vendor.bundle.js:56734:16)
    at DebugRenderer2.webpackJsonp../node_modules/@angular/core/@angular/core.es5.js.DebugRenderer2.setAttribute (http://localhost:4200/vendor.bundle.js:45211:23)
...
```

It's not very informative, I'll let you know if I get it narrowed down, but it's probably an Angular 4 thing since the error happens in the new `DefaultDomRenderer2`.

**Comment by Gbuomprisco** [comment]
Hi @altschuler,

I removed all the dodgy attrs from the svg, maybe retry :)

**Comment by calhemp** [comment]
yesterday not worked for me, and I had the same issue of setAttributeNs and I cannot do some test with my simple project
but I tried now and  it works 
thanks @Gbuomprisco ,

**Comment by Gbuomprisco** [comment]
Cool! Closing issue

**Comment by altschuler** [comment]
Can confirm it works in `0.9.10`. Thank you so much @Gbuomprisco!
