### ISSUE TITLE
Feature Request: Drag-n-Drop Tags.

### ISSUE THREAD

**Issue by vgogov** [Gbuomprisco/ng2-tag-input#272]
Hello 

Would it be possible to have a predefined set of tags that exist on the page and the user can just drag and drop the tags they would like into the "tag box". 

Cheers!

**Comment by Gbuomprisco** [comment]
Possibly - but personally I'll try to flush out all the bugs/compatibility issues first. PRs are very welcome though!

**Comment by Gbuomprisco** [comment]
Added in ng2-tag-input@1.1.5-beta.0
