### ISSUE TITLE
NGC + Rollup compilation fails

### ISSUE THREAD

**Issue by peterbartha** [Gbuomprisco/ng2-tag-input#273]
Hey Gbuomprisco,

I have tried to compile my project with the latest ngc+rollup, but rollup fails with the following output:
```
'TagInputModule' is not exported by 'node_modules\ng2-tag-input\dist\modules\ng2-tag-input.module.js'
'TagInputModule' is not exported by 'node_modules\ng2-tag-input\dist\modules\ng2-tag-input.module.js'
🚨   'TagInputModule' is not exported by node_modules\ng2-tag-input\dist\ng2-tag-input.bundle.js
https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
app\ts\app.module.js (9:9)

7: import { NgModule } from '@angular/core';
8: import { BrowserModule } from '@angular/platform-browser';
9: import { TagInputModule } from 'ng2-tag-input';
             ^
10: import { FormsModule } from '@angular/forms';
11: import { AppComponent } from './app.component';
```

Then I have added the following lines to the rollup configuration file:
```
      namedExports: {
        'node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js': [ 'TagInputModule' ]
      }
```

Unfortunately, after all it does not work for me.
Here is my tsconfig.json (Angular 2 AoT example tsconfig.json):

```
{
  "compilerOptions": {
    "target": "esnext",
    "module": "es2015",
    "moduleResolution": "node",
    "sourceMap": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es2015", "dom"],
    "noImplicitAny": true,
    "suppressImplicitAnyIndexErrors": true
  },

  "files": [
    "app/ts/app.module.ts",
    "app/ts/main.ts"
  ],

  "angularCompilerOptions": {
    "genDir": "app/aot",
    "skipMetadataEmit" : true
  }
}
```

and rollup.config.js:
```
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

export default {
  entry: 'app/ts/main.js',
  dest: 'app/lib/build.js', // output a single application bundle
  sourceMap: false,
  format: 'iife',
  onwarn: function(warning) {
    // Skip certain warnings
    // should intercept ... but doesn't in some rollup versions
    if ( warning.code === 'THIS_IS_UNDEFINED' ) { return; }
    // intercepts in some rollup versions
    if ( typeof warning === 'string' && warning.indexOf("The 'this' keyword is equivalent to 'undefined'") > -1 ) { return; }
    // console.warn everything else
    console.warn( warning.message );
  },
  plugins: [
    nodeResolve({
      jsnext: true,
      module: true
    }),
    commonjs({
      include: 'node_modules/rxjs/**',
      namedExports: {
        'node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js': [ 'TagInputModule' ]
      }
    })
  ]
}
```

Could you help me how should I add your library?
Thank you! :)

**Comment by Gbuomprisco** [comment]
Hi @peterbartha,

the config seems fine as it is, and am pretty sure this should work with angular 2.4.9. Which version are you exactly running?

**Comment by peterbartha** [comment]
First, I have tried with 2.4.8, now with 2.4.10, but it does not work.
Here is a sample app which is using your library and producing the errors above:
https://github.com/peterbartha/angular2-aot/tree/tag-input

Please fork it and run compilation with:
```npm run compile```

**Comment by Gbuomprisco** [comment]
The question is: is it ngc failing, or rollup? By reading the message, it does look like it is rollup. I am not experienced with it honestly

**Comment by peterbartha** [comment]
Hmm... I've put "+rollup" into the first message, because it looks like rollup fails.

**Comment by Gbuomprisco** [comment]
I think there must be something to make rollup work with UMD files. As I said - I am not knowledgeable enough for helping with that, but I'd suggest you to look up more about that (i.e. UMD + Rollup). I'll change the title to Rollup, as I think it's where the issue lies :)

**Comment by peterbartha** [comment]
**Finally I solved this issue with the following rollup configuration for CommonJS plugin:**
```
import nodeResolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

export default {
  entry: 'app/ts/main.js',
  dest: 'app/lib/build.js',
  sourceMap: false,
  format: 'iife',
  onwarn: function(warning) {
    console.warn( warning);
  },
  plugins: [
    nodeResolve({
      jsnext: true,
      module: true
    }),
    commonjs({
      include: [
        'node_modules/rxjs/**',
        'node_modules/ng2-tag-input/**',
        'node_modules/ng2-material-dropdown/**'
      ],
      namedExports: {
        'ng2-tag-input': ['TagInputModule']
      }
    })
  ]
}
```
Rollup will bundle your code without any problem. However, there is another problem with dependency injection. Looks like bundled code cannot resolve DI forwardRef-s. For example, here is a piece of your bundled UMD module:
```
TagInputDropdown = __decorate([
    core_1.Component({
        selector: 'tag-input-dropdown',
        template: __webpack_require__(25)
    }),
    __param(0, core_1.Inject(core_1.forwardRef(function () { return tag_input_1.TagInputComponent; }))),
    __metadata("design:paramtypes", [tag_input_1.TagInputComponent])
], TagInputDropdown);
```
In AoT case, `tag_input_1` is undefined when script execution reaches `__param...`, therefore I get undefined exception:
`Uncaught TypeError: Cannot read property 'TagInputComponent' of undefined`

In SystemJS case, same line, `tag_input_1` is already defined as empty object, and it works. I've tried to execute TagInputComponent before TagInputDropdown, but in this case I got:
`Uncaught TypeError: Cannot read property 'TagInputDropdown' of undefined`

Do you have any idea?

It looks like bundled code cannot resolve circular dependency injection between TagInputDropdown <-> TagInputComponent.

**Comment by Gbuomprisco** [comment]
I don't honestly - as I have never used it. Have you ever checked https://medium.com/@jonnysamps/angular-2-bundling-with-rollup-4738d0148a2c#.ngl6p3ab8?

**Comment by peterbartha** [comment]
Yeah, but it is outdated. I think I found the answer, we must change the type of injected tagInput variable to "any".

From:
`constructor(@Inject(forwardRef(() => TagInputComponent)) private tagInput: TagInputComponent) {}`,
to
`constructor(@Inject(forwardRef(() => TagInputComponent)) private tagInput: any) {}`.

I know it is not a perfect change... but it will works fine, I have tested on my previous example. Could you create a separated branch for that modification? I really like to use your library, but I do not want to create another npm package.

**Comment by Gbuomprisco** [comment]
Sorry but that doesn't sound like a package's issue: the types are there for good reason.

What I'd do:
- try https://github.com/ezolenko/rollup-plugin-typescript2 if you're not already
- play with rollup config + typescript (as I think it's where the issue is)
- last resort - fork and install the component using your fork (I don't think you need to publish to NPM for that)
- very last resort: use webpack :)
