### ISSUE TITLE
Adding tags to a string array

### ISSUE THREAD

**Issue by DevInstinct** [Gbuomprisco/ng2-tag-input#274]
Hi, I'm using a string array as a model.
However, if I add new tags, the new array items end up being { display, value } pairs instead of new strings in the array.
Not sure if it's a bug or if I have an option missing.
Thanks,
Martin

**Comment by Gbuomprisco** [comment]
Hi @DevInstinct,

Are you using the option [modelAsStrings]?

**Comment by oliwin** [comment]
I have the same bug, Who knows?

**Comment by DevInstinct** [comment]
[modelAsStrings]="true"

**Comment by iCRG** [comment]
Hi,
I have been used [modelAsStrings]="true" in tag-input tag &[autocompleteItems]="['qwerty','mani']" in tag-input-dropdown tag. if value is adding from autocompletitems, it is storing as array of objects([{display:"qwerty",value:'qwerty'}]). if value is new , it is storing as array of string(['qwerty'])
