### ISSUE TITLE
Rendering thousands of items crashes browser

### ISSUE THREAD

**Issue by wilfredmifsud** [Gbuomprisco/ng2-tag-input#28]
I am trying to load 50,000 items via the Model in a for loop to the TAG Input. However this is crashing the browser.

Is there a way how to add bulk items without doing re-bind, re-drawing etc..

I was thinking something like 

1. Unbind the model from the TAG
2. Edit the model information (add 50k rows)
3. Re-bind the model to the TAG .. will redraw just once like this.

Please Help

**Comment by Gbuomprisco** [comment]
Hi @wilfredmifsud!

Honestly I think that rendering that amount of data would crash any component.

You could try to approach the issue differently, though:
- if you update the model's array using a timeout, and progressively add items to to it, the browser should not freeze. Also, for the user it is impossible to actually see 50k items.

**Comment by wilfredmifsud** [comment]
Thanks for your feedback, I will see if I can do a workaround as you said.

The 50k items will be displayed by means of scrolling :) .. This is the worst case scenario so usually i have 1k rows or so

**Comment by Gbuomprisco** [comment]
A similar issue (and workaround): http://stackoverflow.com/questions/10344498/best-way-to-iterate-over-an-array-without-blocking-the-ui.

Let me know :)
