### ISSUE TITLE
how can I set value to input display and restrict max value

### ISSUE THREAD

**Issue by nellyigiebor** [Gbuomprisco/ng2-tag-input#280]
Hi,

I'm need to be able to set and show display text on the screen right along with value input like so 
  objects :- 1.) display = (L)   value     = 36
                 2.) display = (XL) value     = 60
                 3.) display = (XXL) value   = 20
                 4.) display = (XXXL) value = 28

Where display stands for size and value = quantity; more like "Tags with a custom template". sample

Thanks in advance.

**Comment by Gbuomprisco** [comment]
Hi @nellyigiebor,

you need to define the data to be displayed in the theme defined by yourself

**Comment by nellyigiebor** [comment]
can you please help?

I need to dynamically create tags with my own display-text and allow the users to enter value .ie.
a user select "SIZE-SET" from a select-component for example "WOMAN SHOES" I'm getting data from http services that returns a size list like : 36, 37, 38, 39 and 40; so for each sizes I want to allow the user to enter quantity for example for size 36  qty = 10, size 37 qty=4 etc etc... and for this to work I need to show text in  displayText of ng2-tag-input. like the "Tags custom template" demo.

Thanks in advance

**Comment by Gbuomprisco** [comment]
If you use the value as the index, you can pass the objects and then define the display value of your template based on the object passed.

See
https://github.com/Gbuomprisco/ng2-tag-input/blob/master/demo/home/home.html#L77

**Comment by nellyigiebor** [comment]
this I have tried already; and this doesn't allowed user to enter value.

<tag-input formControlName="sizeId" name="sizeId" [transform]="transform"     [onlyFromAutocomplete]="true"  theme='dark'>
<tag-input-dropdown [showDropdownIfEmpty]="true" [focusFirstElement]="true" [displayBy]="'label'" [identifyBy]="'value'" [autocompleteItems]="sizeList">
                                                                                        <template let-item="item" let-index="item.value">
                                                                                            ({{ item.value }}) {{ item.id }}: {{ item.label }}
                                                                                        </template>
                                                                                    </tag-input-dropdown>
</tag-input>

I just need to allow user to enter value while selecting display from the dropdown..

**Comment by Gbuomprisco** [comment]
Sorry, I have a bit a hard time understanding.

Can you explain in details this part "I just need to allow user to enter value while selecting display from the dropdown"?

**Comment by nellyigiebor** [comment]
tag-input component have display and value, right!
can I possibly bind from "tag-input-dropdown" to the "display"  and let user input value. i.e
from dropdown select "BIG SIZE" and enter 38 as quantity
PLS FIND SAMPLE JSON DATA.

 "modelDetail": [
    {
      "modelName": "MAN BIG SIZES",
      "price": 70,
      "exchange": "USD",
      "sizeSet": 11,
      "modelArray": [
        {
          "colorId": 4,
          "sizeId": [
            {
              "display": "5XL",
              "value": 10
            },
            {
              "display": "6XL",
              "value": 10
            },
            {
              "display": "7XL",
              "value": 20
            },
            {
              "display": "8XL",
              "value": 15
            },
            {
              "display": "9XL",
              "value": 10
            },
            {
              "display": "12XL",
              "value": 8
            }
          ] 
        }
      ]
    },
    {
      "modelName": "LADY'S SHOES",
      "price": 80,
      "exchange": "USD",
      "sizeSet": 5,
      "modelArray": [
        {
          "colorId": 19,
          "sizeId": [
            {
              "display": "36",
              "value": 20
            },
            {
              "display": "37",
              "value": 12
            }
          ]
        }
      ]
    }

Please I need soıme help....

**Comment by Gbuomprisco** [comment]
Hi @nellyigiebor,

all you can do with the components is in the examples defined - they are valid for almost all possible situations. I can't visualise myself what you are trying to do. Sorry, but I am not able to help in this case.. maybe someone will read and help :)

**Comment by nellyigiebor** [comment]
ok thanks.
