### ISSUE TITLE
With dropdown, add a tag that is not in the dropdown but whose value is included in one of the dropdown [Windows]

### ISSUE THREAD

**Issue by sancaruso** [Gbuomprisco/ng2-tag-input#284]
I use the dropdown but I also accept tags that are not in the dropdown. But there is a problem if I want to add a tag that is not in the dropdown but whose value open the dropdown.

For example if the dropdown accepts "Hello", "World", "foo", "bar" and if I want to add "hell" as a tag, the dropdown will open and show "Hello" and I won't be able to add "hell" as a tag :
- if the dropdown is open, I can only add a tag from the dropdown,
- if it is closed, the input has not the focus and I can't add the tag.

**Comment by Gbuomprisco** [comment]
Hi @sancaruso,

what version are you using?

**Comment by sancaruso** [comment]
Hi,
I am using 0.8.4.
I observe the same problem in the demo http://www.buompris.co/ng2-tag-input/ (for example in the "Tags within an autocomplete component" I am not able to add "Script" as a tag because it is part of "Typescript"...)

**Comment by sancaruso** [comment]
Do you have an updated changelog, or can you tell me if I risk of having to change my code if I update the version ? (It happend last time I updated the package, the way of dealing with object-tags had changed and I had to change my code a lot.)

**Comment by Gbuomprisco** [comment]
Most should be compatible, with the exception of separatorKeys (now accets strings) and separatorKeyCodes (basically the old separatorKeys). 

Obviously I cannot be 100% sure, but the best shot you have is to always update.

**Comment by sancaruso** [comment]
Ok, so after updating I confirm the same problem.

**Comment by Gbuomprisco** [comment]
Not sure i'm reproducing correctly, but it works on my end (Chrome/OSX)

**Comment by sancaruso** [comment]
So I made the test on several browsers/OS with the demo http://www.buompris.co/ng2-tag-input/, but it never worked.
What I exactly do: in the "Tags within an autocomplete component", I tried to add the tag "Script" without adding the tag "Typescript".

I tried on Windows : Chrome, Chromium and Firefox,
on Ubuntu : Chrome, Chromim and Firefox,
on OSX : Chrome and Firefox.

**Comment by Gbuomprisco** [comment]
the demo is outdated - try 0.9.10 locally

**Comment by sancaruso** [comment]
Well, it works on Ubuntu, but it doesn't work on Windows. (With Chrome/Chromium)

**Comment by Gbuomprisco** [comment]
ah I see - never tried on that unfortunately (usually Ubuntu or Mac).

**Comment by sancaruso** [comment]
I am sorry! Actually it works: I didn't build the dll so I actually was using the old version...
You can close the issue.

**Comment by Gbuomprisco** [comment]
cool :)
