### ISSUE TITLE
Building with AOT

### ISSUE THREAD

**Issue by jvielrco** [Gbuomprisco/ng2-tag-input#285]
Hi,
I am trying to compile my app with AOT with the latest version (0.9.9), but I'm getting this error :
> Property 'inputTextChange' is private and only accessible within class 'TagInputForm'.

**Comment by Gbuomprisco** [comment]
Hi @jvielrco,


try 0.9.10?

**Comment by jvielrco** [comment]
It's working. Thank you very much for your quick fix, it's greatly appreciated! :)
