### ISSUE TITLE
Not able to map bundle.js correctly

### ISSUE THREAD

**Issue by Harri92** [Gbuomprisco/ng2-tag-input#288]
I'm trying to use ng-tag-input but when I run the npm install ng2-tag-input --save, it does not fetch all file, e.g ng2-tag-input.module.ts in modules. 

I have updated all dependencies for npm, rxjs etc to match the requirements for ng2-tag-input and also added the systemJS instructions mentioned in the readme. When trying to import the TagInputModule it does not seem to find the path. I've made sure that the it is pointing to it and also copied missing files manually to test. 

What is the correct mapping set up and how to refer in app.module as well as systemJS in relation to folder structure.

Best regards

**Comment by Gbuomprisco** [comment]
Hi @Harri92,

can you post here what the folder in node_modules looks like?

**Comment by Harri92** [comment]
Hi,
Not sure if this is enough.
![node_modules-ng2](https://cloud.githubusercontent.com/assets/6523923/24197472/0c672da6-0f02-11e7-8c7d-0023e7a02861.PNG)

**Comment by Gbuomprisco** [comment]
Hi @Harri92,

all the files look like are there. The important stuff is in `dist`. Can you post here the exact error you're being returned?

**Comment by Harri92** [comment]
Hi @Gbuomprisco 

![errorlist](https://cloud.githubusercontent.com/assets/6523923/24198163/f391ce5a-0f04-11e7-9d0c-e4d6d04760eb.PNG)

I've also imported TagInputModule to my app.module

**Comment by Gbuomprisco** [comment]
I think it's something to do with the build process. A bit difficult to say _what_ without more information, sorry

**Comment by Harri92** [comment]
@Gbuomprisco 

Ok, because I seem to get that under NgModule, imports that TagInputModule is not resolved and probably located in inaccessible location. As you can see in my previous picture it is not even present in any folder. Where should it be copied to?

Also the following code:
  'ng2-tag-input': {
        main: 'dist/ng2-tag-input.bundle.js',
        format: 'cjs',
    },
    'ng2-material-dropdown': {
        defaultExtension: 'js',
        main: 'dist/ng2-dropdown.bundle.js',
        format: 'cjs',
    },
    'ng2-tag-input/modules/components/tag-input.template.html': {
        defaultJSExtension: false
    }
Should it be modified in any way?

Thanks.

**Comment by Gbuomprisco** [comment]
```
import { TagInputModule } from 'ng2-tag-input'; // will look for it in node_modules/ng2-tag-input/dist/ng2-tag-input.bundle.js
```

That part of the config needs to be added to your existing packages object

**Comment by Harri92** [comment]
Ok that is already added but it is not resolved.

Do I need to add 
> ng2-tag-input.module.ts 
and where should I put it so the bundle.js can locate it?

**Comment by Gbuomprisco** [comment]
No, you don't need that file. `ng2-tag-input.bundle.js` is the actual file that will be loaded. But to do so, you need to set it in the systemjs config. Can you paste here your systemjs config?

**Comment by Harri92** [comment]
`/**
 * System configuration for Angular samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
    System.config({
        paths: {
            // paths serve as alias
            'npm:': 'node_modules/'
        },
        // map tells the System loader where to look for things
        map: {
            // our app is within the app folder
            app: 'app',

            // angular bundles
            '@angular/core': 'npm:@angular/core/bundles/core.umd.js',
            '@angular/common': 'npm:@angular/common/bundles/common.umd.js',
            '@angular/compiler': 'npm:@angular/compiler/bundles/compiler.umd.js',
            '@angular/platform-browser': 'npm:@angular/platform-browser/bundles/platform-browser.umd.js',
            '@angular/platform-browser-dynamic': 'npm:@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js',
            '@angular/http': 'npm:@angular/http/bundles/http.umd.js',
            '@angular/router': 'npm:@angular/router/bundles/router.umd.js',
            '@angular/router/upgrade': 'npm:@angular/router/bundles/router-upgrade.umd.js',
            '@angular/forms': 'npm:@angular/forms/bundles/forms.umd.js',
            '@angular/upgrade': 'npm:@angular/upgrade/bundles/upgrade.umd.js',
            '@angular/upgrade/static': 'npm:@angular/upgrade/bundles/upgrade-static.umd.js',
            '@ng-bootstrap/ng-bootstrap': 'npm:@ng-bootstrap/ng-bootstrap/bundles/ng-bootstrap.js',

            // other libraries
            'rxjs': 'npm:rxjs',
            'angular-in-memory-web-api': 'npm:angular-in-memory-web-api/bundles/in-memory-web-api.umd.js',
            'dropzone': 'npm:dropzone/dist/min/dropzone.min.js'
            //'tag': 'npm:ng2-tag-input/dist/ng2-tag-input.bundle.js'
        },
        // packages tells the System loader how to load when no filename and/or no extension
        packages: {
            app: {
                main: './main.js',
                defaultExtension: 'js'
            },
            rxjs: {
                defaultExtension: 'js'
            },

            'ng2-tag-input': {
                main: 'dist/ng2-tag-input.bundle.js',
                format: 'cjs',
            },
            'ng2-material-dropdown': {
                defaultExtension: 'js',
                main: 'dist/ng2-dropdown.bundle.js',
                format: 'cjs',
            },
            'ng2-tag-input/modules/components/tag-input.template.html': {
                defaultJSExtension: false
            }

          }


    });
})(this);
`

**Comment by Gbuomprisco** [comment]
You need to add `ng2-tag-input` to the map object. So:

```
'ng2-tag-input': 'npm:ng2-tag-input' OR 'ng2-tag-input': 'node_modules/ng2-tag-input' // not 'tag'
```

Can you try?

**Comment by Harri92** [comment]
@Gbuomprisco 

It is still not able to build. I tried both ng2-tag-input and  'ng2-tag-input': 'npm:ng2-tag-input/dist/ng2-tag-input.bundle.js' but still no success.

any other ideas what it might be?

**Comment by Gbuomprisco** [comment]
no that won't work cause you're specifying it in the packages. As last try i would do, in the map object:

```
 'ng2-tag-input': '/node_modules/ng2-tag-input'
```
