### ISSUE TITLE
Issue on upgrading to 0.9.10

### ISSUE THREAD

**Issue by omprakash9** [Gbuomprisco/ng2-tag-input#290]
Hi, previously when I'm using version 0.7.4. I use to get the Item object from onItemAdded() as shown below , But when I upgraded the version to 0.9.10, I'm getting only two properties ie. ItemId and display value as mentioned below. I need the whole object to be returned similar to 0.7.4 in 0.9.10 version.

**version 0.7.4:**
apexUniqueId:"BRAND-1122"
confidence:"UNSCORED"
core:"BRAND"
displayHTML:"Refresh Your <b>car</b>"
displayValue:"Refresh Your Car"
itemId:1111
pla:"RYC"
productLine:"Refresh Your Car"
score:1.1094004

**version 0.9.10:**

displayValue:"Refresh Your Car"
itemId:1111

**Comment by omprakash9** [comment]
Hi @Gbuomprisco ,

I'm just wondering!, How soon it will get fixed?, because our project need to go in production

**Comment by Gbuomprisco** [comment]
Hi @omprakash9,

sorry - not before the weekend

**Comment by omprakash9** [comment]
Okay @Gbuomprisco ,
Please let me know once it get fixed. Thankyou!

**Comment by Gbuomprisco** [comment]
Hi @omprakash9,

if you could pull https://github.com/Gbuomprisco/ng2-tag-input/pull/293 and try it out to see if it fixes you issues (this and IE related), it would be great! I can't test IE/Spark unfortunately

**Comment by omprakash9** [comment]
@Gbuomprisco ,
Can you please publish it with new version, So that I will update my plugin and will check it in my local

**Comment by Gbuomprisco** [comment]
@omprakash9 
I'll probably publish under the tag beta, in case there are any bugs

**Comment by Gbuomprisco** [comment]
Hi @omprakash9,

I release under the tag beta, so you need to specify the version (1.0.0 -  🎉 ). Let me know! :)

**Comment by omprakash9** [comment]
@Gbuomprisco 

It is now fixed, returning the whole object, Thanks
