### ISSUE TITLE
Should it work with cli?

### ISSUE THREAD

**Issue by itspers** [Gbuomprisco/ng2-tag-input#291]
Tried different versions of library with different versions of cli – all crashing with same:
`Can't bind to 'ngModel' since it isn't a known property of 'tag-input'.`

And in source there is no ngModel in TagInputComponent, where is a trick?

**Comment by Gbuomprisco** [comment]
Hi @itspers,

I need to see some code to understand - but it would appear the module is not registered?

**Comment by itspers** [comment]
@Gbuomprisco hi, sorry for disturbing – it was not bug.

While was writing full description of problem, realize, that im trying to use it in submodule and here was no default 'FormsModule' import like in root 'app' module...

At same time material and primeng components are working fine without FormsModule.

**Comment by Gbuomprisco** [comment]
Cool :)
