### ISSUE TITLE
Disable native browser autocomplete

### ISSUE THREAD

**Issue by DevInstinct** [Gbuomprisco/ng2-tag-input#292]
Some browsers (ex: Edge) show their native autocomplete dropdown on the input focus.

Would be good to add the autocomplete="off" attribute on either the form or the input of the tag-input to fix that.

**Comment by Gbuomprisco** [comment]
Hi @DevInstinct,

I released under the tag beta, so you need to specify the version (1.0.0 -  🎉 ). Let me know! :)

Also, let me know if Edge has any other bugs - I never checked it out. Thanks :)

**Comment by DevInstinct** [comment]
Hi Giancarlo, thanks for the quick fix. Just installed the beta and it
works well with Edge now.

We however have a more major issue that happens in all the browsers (I
think it would match part of
https://github.com/Gbuomprisco/ng2-tag-input/issues/75 ). If the control is
close to the bottom of the page, the autocomplete moves up and hides the
input - and when you accept values that are not in the list the user is
stuck not seeing his input anymore. It may be a bit hard to fix, but if
there was an option (in @beta maybe) to prevent the autocomplete to move up
and just to stay where it is, that would temporarily fix the problem.

This issue is easy to reproduce on the demo page if you position an
autocomplete input at the bottom of your browser window or if you open it
on a mobile phone.

Thanks,
Martin

**Comment by Gbuomprisco** [comment]
Yeah - the issue is that the dropdown tries hard to stay in the page if its element overflows the screen. I'll see if I can come up with a better way
