### ISSUE TITLE
Integration with Angular-cli project

### ISSUE THREAD

**Issue by Iraecio** [Gbuomprisco/ng2-tag-input#295]
how i can use this project in a angular cli?

i make npm install and add in module but when i run ng server dont found input.template.html

**Comment by Gbuomprisco** [comment]
Hi @Iraecio,

what exact version of the cli are you running?

**Comment by Iraecio** [comment]
@angular/cli to 1.0.0-rc.1

**Comment by Gbuomprisco** [comment]
Hi @Iraecio,

Just tried and can't reproduce really. Need more information to be able to help
