### ISSUE TITLE
Template parse warnings after migrating project to Angular4

### ISSUE THREAD

**Issue by okachynskyy** [Gbuomprisco/ng2-tag-input#297]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Warning in browser console
```
Template parse warnings:
The <template> element is deprecated. Use <ng-template> instead ("tchCase="true" [attr.contenteditable]="editModeActivated">
        <!-- CUSTOM TEMPLATE -->
        [WARNING ->]<template
            [ngOutletContext]="{ item: model, index: index }"
            [ngTemplateOutlet"): ng:///TagInputModule/TagComponent.html@10:8
```

**Expected behavior**
No warnings in browser console.

**Minimal reproduction of the problem with instructions**
I have migrated my project to Angular4.0.0 and I get this warning in browser console.

**What do you use to build your app? (SystemJS, Webpack). Please specify the version**
Angular CLI 1.0.0

* **Angular version:** 4.0.0

* **Browser:** [ Chrome XX | Firefox XX |  Safari XX | Opera XX ]

**Comment by Gbuomprisco** [comment]
Hi @okachynskyy,

this should now be solved - try the latest version :)

**Comment by okachynskyy** [comment]
@Gbuomprisco thanks for reply :)
After updating to 1.0.1 I have the same issue:
https://github.com/Gbuomprisco/ng2-tag-input/issues/300

**Comment by Gbuomprisco** [comment]
1.0.0 won't change
