### ISSUE TITLE
Case Insensitive for autocomplete tags

### ISSUE THREAD

**Issue by igordeoliveirasa** [Gbuomprisco/ng2-tag-input#30]
First of all: Congratulations! It's a really precious project!!!
And,.. how could I disable case sensitive for autocomplete tags?

Thanks.
Igor

**Comment by igordeoliveirasa** [comment]
Do you have any trick so as to do right now in order to release to my customer? Or, do you know when could you guys solve it? Thanks!

**Comment by Gbuomprisco** [comment]
Hi @igordeoliveirasa, thanks for the congratulations!

Unfortunately right now there is no option for doing that.

Most likely there will be no option for doing it in the future, but I may add an output for when a key is pressed in the input, so that you could transform the value of the value entered. Example:
- transform all keys entered to uppercase
- enter items in uppercase

so that they will match

**Comment by igordeoliveirasa** [comment]
I'm anxious for that!! Thanks!

**Comment by Gbuomprisco** [comment]
Hi @igordeoliveirasa,

I published the version 0.2.2 and now case it is case insensitive :)

**Comment by simoazzo** [comment]
Hi Gbuomprisco,

I have updated to the latest version and case is still sensitive:

  <tag-input  [(ngModel)]="_job.JobClients"
                       [autocompleteItems]="_clientsNames"
                       [onlyFromAutocomplete]="true"
                       placeholder="Client"
                       secondaryPlaceholder = "Choose Client"
                       [autocomplete]="true" ngControl="jobClients" name="jobClients" #jobClients="ngForm">
            </tag-input>

How can Enable it please?

**Comment by reachnana** [comment]
Is there an update on this? The latest version is still case sensitive.

**Comment by jlamarr22** [comment]
@Gbuomprisco is right in that the `tag-input` component is case sensitive, but it doesn't check the autocomplete for case sensitivity when someone is typing a value into the input.

You can do this yourself in a somewhat roundabout way. You have to use the `[onAdding]` hook and check for case sensitivity there. If your user enters "abc" and you have an item in your auto complete for "ABC", then you'd return the item from your auto complete. Here's an example:

```
<tag-input
    [onAdding]="checkTagReference()"
    ...
  >
    <tag-input-dropdown
      [autocompleteItems]="values"
      [displayBy]="'itemValue'"
      [identifyBy]="'itemValue'"
      ...
    >
      <ng-template let-item="item">
        {{ item.itemValue }}
      </ng-template>
    </tag-input-dropdown>
  </tag-input>
```

```
  // Necessary to retain the reference to 'this'
  checkTagReference() {
    let comp = this;
    return function(itemValue: string) {
      return comp.checkTag(itemValue);
    };
  }

  checkTag(itemValue: string): Observable<string> {
    let comp = this;
    return of(comp.getAutocompleteItemIfExists(itemValue));
  }

  // '_' is lodash: https://lodash.com/docs/4.17.11
  getAutocompleteItemIfExists(itemValue: string): string {
    let comp = this;
    let currentItem = _.find(comp.values, function(value: SomeType) {
      return value.itemValue.toLowerCase() === itemValue.toLowerCase();
    });

    return currentItem ? currentItem.itemValue : itemValue;
  }
```
