### ISSUE TITLE
Template Deprecation warning With Angular 4.x.x

### ISSUE THREAD

**Issue by madhudskumar** [Gbuomprisco/ng2-tag-input#315]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**

![image](https://cloud.githubusercontent.com/assets/8987882/24459659/fdc0e6d0-1450-11e7-874d-8015df16d9d4.png)
depracation warning

**Expected behavior**

**Minimal reproduction of the problem with instructions**

Using angular@latest with ng2-tag-input@latest

**What is the motivation / use case for changing the behavior?**

**What do you use to build your app? (SystemJS, Webpack). Please specify the version**

OS 10 , webstorm, Angular Cli

* **Angular version:** 4.x.x

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by Gbuomprisco** [comment]
As you can see, the template uses ng-template, you may need to reinstall your modules:

https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/tag/tag.template.html#L12

**Comment by madhudskumar** [comment]
Thanks a lot.
