### ISSUE TITLE
Custom object class with properties other than value and display

### ISSUE THREAD

**Issue by paddyfink** [Gbuomprisco/ng2-tag-input#318]
**I'm submitting a **  
```
[ x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
When we use a custom class object, the taginput component doesn't keep all properties of the object

**Expected behavior**
I should have the whole object selected by the user in my event (onAdd, onRemove) or get through the dropdown

**Minimal reproduction of the problem with instructions**
<tag-input [ngModel]="followers"
                          [onlyFromAutocomplete]="true"
			  [displayBy]="'fullName'"
                          [identifyBy]="'id'"
			  placeholder="+ add follower"
                          (onAdd)="onFollowerAdded($event)"
                          (onRemove)="onFollowerRemoved($event)" #input>
					<template let-item="item" let-index="index">
						<img [src]="item.picture" alt="sender profile image" class="message-avatar"> 
					</template>
                <tag-input-dropdown [showDropdownIfEmpty]="true"
                                    [focusFirstElement]="true"
                                    [displayBy]="'fullName'"
                                    [identifyBy]="'id'"
                                    [autocompleteItems]="users | async">
                    <template let-item="item" let-index="index">
                       <img [src]="item.picture" alt="sender profile image" class="message-avatar"> {{ item.fullName }}
                    </template>
                </tag-input-dropdown>
            </tag-input>
When I select an item on the dropdown list, the picture picture is null in my tag input template and the picture doesn't diplay. But as you can see, the picture is well displayed for other items already in the model:
![image](https://cloud.githubusercontent.com/assets/12916378/24509002/2d0dfaee-1533-11e7-8798-b3bff79fb869.png)

An also, on my onAdd event, I only received the object with only the id and name property ( the ones binded to [displayBy] and [identifyBy]).

**What do you use to build your app? (SystemJS, Webpack). Please specify the version**
Webpack

* **Angular version:** 2.0.X
2.2.4

* **ng2-tag-input version:**
latest as today

**Comment by Gbuomprisco** [comment]
Hi @paddyfink,

I assume this should have been fixed?
