### ISSUE TITLE
Dropdown is not getting hide

### ISSUE THREAD

**Issue by igordeoliveirasa** [Gbuomprisco/ng2-tag-input#32]
Whenever it displays a dropdown and I press tab key so as to loose current field focus, dropdown keeps on being displayed...

**Comment by igordeoliveirasa** [comment]
It also happens whenever I press "enter key", so as to insert new tag. It keeps on showing..

**Comment by igordeoliveirasa** [comment]
Do you have any trick so as to do right now in order to release to my customer? Or, do you know when could you guys solve it? Thanks!

**Comment by igordeoliveirasa** [comment]
same happens when I backspace clearing the tags. drop down menu keeps on showing..

**Comment by Gbuomprisco** [comment]
Hi @igordeoliveirasa. Thanks for opening this. I will probably fix it this weekend.

**Comment by igordeoliveirasa** [comment]
I thank you so much for the answer!! And congratulations again! Awesome project! It will be the top  of the angular 2 tag input components. You want to bet?

**Comment by Gbuomprisco** [comment]
Hi @igordeoliveirasa,

I published the version 0.2.2 and should fix this :)
