### ISSUE TITLE
Caps letter search

### ISSUE THREAD

**Issue by dharveshmydeen** [Gbuomprisco/ng2-tag-input#321]
Hi how could i search using CAPS letters in autocomplete
for lowercase it will list the autocomplete list
if i typed in CAPS letters it will not showing any list

**Comment by Gbuomprisco** [comment]
The autocomplete is not case-sensitive, unless you're using an outdated version. Please fill out the template next time.

**Comment by dharveshmydeen** [comment]
I am using ng2tag-input : 0.8.4
my  angular version is 2.3.1
it is worked for this angular version?

**Comment by Gbuomprisco** [comment]
that's too outdated  - you need to update it

**Comment by dharveshmydeen** [comment]
What  is the latest version of ng2-tag-input

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/blob/master/package.json

**Comment by Gbuomprisco** [comment]
you'll also need to update your angular version - so maybe update to 1.0.0

**Comment by dharveshmydeen** [comment]
Thank you..!
