### ISSUE TITLE
[Question] Are remote async validators supported?

### ISSUE THREAD

**Issue by bastienJS** [Gbuomprisco/ng2-tag-input#322]
**Current behavior**

As the documentation says I can use validators thus I declared this:

```
  public schoolclassValidators = [Validators.required, this.schoolclassNumberValidator.bind(this)];
    public schoolclassErrorMessages = { 
        'schoolclassExists': 'Schulklasse existiert bereits.',
        'required': 'Schulklasse darf nicht leer sein.'
    };
```
```
                <tag-input  [errorMessages]="schoolclassErrorMessages" [validators]="schoolclassValidators" placeholder="Neue Schulklasse" secondaryPlaceholder="Es wird mind. 1 Schulklasse benötigt"  [ngModel]="schoolclasses" [identifyBy]="'id'" [displayBy]="'schoolclassNumber'"></tag-input>
```

I am using a remote validator which checks on the server wether the schoolclassnumber already exists.
That code works fine with my own 'tags/chips' implementation:

```
    schoolclassNumberValidator(c: AbstractControl) {
        return this._administrationService.schoolclassExists(c.value, this.schoolyearId).map(response => {
            if (response == true) {
                return { "schoolclassExists": true };
            }
            else {
                return null;
            }
        });
    }
```

But using your tags component that _administration service method is called but the server is never hit and therefore validation fails always.

It seems your component is not supporting remote validators ?

**Comment by Gbuomprisco** [comment]
Probably not, but I never tried. I'll have to get back to you on this. 

Please do fill the template next time :)

**Comment by bastienJS** [comment]
I wanted to fill the whole template, but then I thought that this simple question has actually nothing to do with any version/reproduce bug behavior. Asking such questions on SO nobody will answer only the author knows :-)

**Comment by Gbuomprisco** [comment]
I see the issue: right now the component uses Validators.compose, but I also need to add Validators.composeAsync. It will probably be in a different property, like `asyncValidators`.

**Comment by bastienJS** [comment]
Fine! And I continue creating issues in a correct manner!

**Comment by Gbuomprisco** [comment]
There is a "loading state" already :) you can try it by using the autocompleteObservable example

**Comment by Gbuomprisco** [comment]
Added aysncValidators some version back
