### ISSUE TITLE
[Feature Request] add async [onAdding] and [onRemoving] hooks

### ISSUE THREAD

**Issue by bastienJS** [Gbuomprisco/ng2-tag-input#323]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
[ X ] question request
```

**Current behavior**
When my user deletes a tag, that tag is immediately deleted!

**Expected behavior**

When my user deletes a tag and the bound entity has a foreign key constraint, I want to intercept the onRemove event where I return true/false and THEN YOUR internal onRemove method is called or not depending on the true/false value. 

**Use Case**

I want this because by intercepting the removal I can show the user a small dialog with a yes / no button saying do you really want to delete this entity with its related data? Depending on the users answer I return true/false.

I would therefore need an onRemoving hook.

**What do you use to build your app? (SystemJS, Webpack). Please specify the version**

angular cli (webpack)

* **Angular version:** 2.0.X

angular 4.0.1

* **ng2-tag-input version:**

v1.0.5

**Comment by Gbuomprisco** [comment]
Have you tried already the output (onRemove)?

**Comment by bastienJS** [comment]
Actually I would also need to intercept the onAdd method. I know that other tags/chips like ngJS 1.x just work like your component work, but I want that the tag is ONLY added in the UI when the server request returns an Ok. All your functions like Add/Delete are executed inmemory immediately.

Just imagine, the user could add a tag in the UI, meanwhile server request is going on, but the user leaves the page. 2 seconds later the server request returns with a 400 bad data state or another error state. This can´t be handled anymore , because the user moved away from the page.

I can hardly believe that I am the first mentioning this problem... am I?

Or do you think I misuse your tags component?

**Comment by Gbuomprisco** [comment]
The first could be implemented using an async validator (when the new attribute [asyncValidators] will be added). The second yeah could make use of the hook.

What you're trying to do is a little unconventional and maybe advanced, but I wouldn't really say "misuse" :)

**Comment by bastienJS** [comment]
Ok then I have this onAddingTag and onRemovingTag feature request, shall I still make 2 extra feature request for them so you can label and track them correctly? Or do you think this feature is nowhere going to be implemented :P

**Comment by Gbuomprisco** [comment]
Don't worry, I'll just edit the title of this issue :) I think it's worthwhile doing, but I can't really say about a timeline for it being implemented :|

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/377/files

**Comment by Gbuomprisco** [comment]
Just published version 1.2.3

**Comment by neilharding** [comment]
thanks for adding this feature - I also find it useful for what I'm doing ... I did notice that onAdding only gets called when you press Enter to add a tag. If you click on or a tag in the autocomplete list or use separatorKeyCodes to define additional keys that will cause the tag to be added ... it doesn't call onAdding.

Thanks again for all your work on this!

**Comment by Gbuomprisco** [comment]
Hi @neilharding,

I created a new issue https://github.com/Gbuomprisco/ng2-tag-input/issues/398 :)
