### ISSUE TITLE
ng2-tag-input versioning angular@2.4.10

### ISSUE THREAD

**Issue by marcpursals** [Gbuomprisco/ng2-tag-input#324]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ X] support request
```

**Current behavior**

I'm trying to install ng2-tag-input with angular@2.4.10 but I'm not able to find the version that fits my angular project. Where can I find the list of versions related to angular compatibilities?

Thanks in advance

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**What do you use to build your app? (SystemJS, Webpack). Please specify the version**

* **Angular version:** 2.0.X

* **ng2-tag-input version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi @marcpursals,

I don't have a list for that, but version 1.0.1 should work fine with your project
