### ISSUE TITLE
Requires BrowserAnimationsModule but does not detail this in documentation

### ISSUE THREAD

**Issue by DBosley** [Gbuomprisco/ng2-tag-input#325]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```

**Current behavior**
Tags do not work at all.
Error in console related to fade animation.

**Expected behavior**
Tags should display.

**Minimal reproduction of the problem with instructions**
Clone ng2-tag-input, run the dev server, navigate to localhost:3000

**What is the motivation / use case for changing the behavior?**
it's broken otherwise

**What do you use to build your app? (SystemJS, Webpack). Please specify the version**
visible in ng2-tag-input demo in project

* **Angular version:** 4.0.X

* **ng2-tag-input version:**
latest

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

Solution:
App needs to import 
`import { BrowserAnimationsModule } from '@angular/platform-browser/animations';`
and import it into the main AppModule instead of BrowserModule

**Comment by hackash** [comment]
Can anyone explain why it is labeled as enhancement, this is a bug I dare to say HOTFIX, nothing works so far, because of this .

**Comment by Gbuomprisco** [comment]
@hackash what? Just add BrowserAnimationsModule mate

**Comment by hackash** [comment]
Thank you for your fast response, everything works now.

**Comment by mebibou** [comment]
Came upon this, and actually when using Angular `4.0.0` you also need to add `@angular/animations` in your `package.json`

**Comment by halben** [comment]
I was about to open a new support request but my question is relevant to this post.

Is there a way to disable the animation? Even if I imported the BrowserAnimationModule, my universal app is complaining that "browser module" is already loaded.

**Comment by DBosley** [comment]
You have to replace the BrowserModule import with the
BrowserAnimationModule, you can't use both at once

**Comment by webcat12345** [comment]
Thanks all. @Gbuomprisco , If you can write about this on ReadMe.md then it would be great.

**Comment by Gbuomprisco** [comment]
Added to the readme
