### ISSUE TITLE
ng2-tag-input appendToBody not working from npm.

### ISSUE THREAD

**Issue by zakonsx** [Gbuomprisco/ng2-tag-input#327]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**What do you use to build your app? (SystemJS, Webpack). Please specify the version**

* **Angular version:** 2.0.X

* **ng2-tag-input version:**

* **Browser:** [all]

**Comment by Gbuomprisco** [comment]
Hi @zakonsx,

can you please complete the template and add the errors you're getting, any stacktrace that can help? versions as well
