### ISSUE TITLE
Error: No value accessor for ''

### ISSUE THREAD

**Issue by simoazzo** [Gbuomprisco/ng2-tag-input#33]
Hi guys,

I am trying to get ng2-tag-input working but is giving me the following error:
`platform-browser.umd.js:2306 Error: No value accessor for ''`

I have done exactly step by step as explained in github.

this is my code:

```
<div>
        <h3>Input tag that allows max 3 tags</h3>
        <tag-input [ngModel]="['Javascript', 'Typescript']"
                   [maxItems]="3"
                   placeholder="Insert a new item"></tag-input>
    </div>
```

```
@Component({
    moduleId: module.id,
    selector: 'jobform',
    directives: [FILE_UPLOAD_DIRECTIVES, TagInput],
    templateUrl: 'jobform.component.html'
})
```

Any ideas and help will be much appreciated, thanks.

Kind Regards

**Comment by Gbuomprisco** [comment]
Hi @simoazzo!

A few questions:
- which Angular version are you running?
- did you configure Angular like this https://github.com/Gbuomprisco/ng2-tag-input#angular-2-configuration-rc3?

Thanks

**Comment by Gbuomprisco** [comment]
Hi @simoazzo, did you solve this?
