### ISSUE TITLE
AoT compilation error in TagInputDropdown

### ISSUE THREAD

**Issue by aralroca** [Gbuomprisco/ng2-tag-input#330]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request
```
Similar issue: https://github.com/Gbuomprisco/ng2-tag-input/issues/224

**Current **

Is an AoT compilation issue similar that #224, but at this time instead of TagComponent is happening in TagInputDropdown:

```
Property 'scrollListener' is private and only accessible within class 'TagInputDropdown'.
```

**Expected behavior**

Compile in AoT without console errors.

**Minimal reproduction of the problem with instructions**

 `ng build --aot`

**What is the motivation / use case for changing the behavior?**

Fix the issue that is happening recently in my app.

**What do you use to build your app? (SystemJS, Webpack). Please specify the version**

Webpack, mac os, visual studio code, npm

* **Angular version:** 2.0.X

 
2.4

* **ng2-tag-input version:**

0.9.2

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Not browsers, just the console.

**Comment by Gbuomprisco** [comment]
The current version is 1.0.5, the only thing you can do is upgrade to 1.0.0 or 1.0.5 if you run Angular 4.0.0.
