### ISSUE TITLE
Failed to load tag-input.template.html

### ISSUE THREAD

**Issue by firatkucuk** [Gbuomprisco/ng2-tag-input#332]
I do not know this component supports Angular 4. But My Angular 4 project doesn't start after adding ng2-tag-input component. I added ng2-tag-input dependency and import statement to my module.

**Comment by Gbuomprisco** [comment]
Complete the template please

**Comment by MmtBkn** [comment]
What does that mean? Do I need to define template before start using app?

**Comment by Gbuomprisco** [comment]
@MmtBkn I meant the issue's template, it helps me understand what's wrong

**Comment by MmtBkn** [comment]
I was getting following error, but I realized that import satatement wasn't same. Webstorm imported as `import {TagInputModule} from "ngx-chips/dist/modules";`, and I replaced it with `import {TagInputModule} from "ngx-chips";`, and It works now.
