### ISSUE TITLE
cli not supporting

### ISSUE THREAD

**Issue by amitgaur208** [Gbuomprisco/ng2-tag-input#335]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

I have  run the command:
npm install ng2-tag-input --save

imported module
import { TagInputModule } from 'ng2-tag-input';

@NgModule({
   imports: [ TagInputModule ]
})
export class MyModule {}

But gives me the error even i doesn't use this anywhere, it gives instant error when importing this.

**What is the motivation / use case for changing the behavior? (if applicable)**

Unhandled Promise rejection: Template parse errors:
'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. ("tchCase="true" [attr.contenteditable]="editModeActivated">
        
        [ERROR ->]<ng-template
            [ngOutletContext]="{ item: model, index: index }"
            [ngTemplateOut"): TagComponent@11:8 ; Zone: <root> ; Task: Promise.then ; Value: 

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

angular-cli

**Angular version:** 

Angular 2 Cli
"@angular/common": "^2.4.0",
    "@angular/compiler": "^2.4.0",
    "@angular/core": "^2.4.0",
    "@angular/forms": "^2.4.0",
    "@angular/http": "^2.4.0",

**ng2-tag-input version:**

"ng2-tag-input": "^1.0.5"

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome
Mozilla
IE 10, 11

**Comment by Gbuomprisco** [comment]
You need to upgrade your Angular version, or use version 1.0.0 of this component

**Comment by amitgaur208** [comment]
Cant install previous version

**Comment by Gbuomprisco** [comment]
then you need to upgrade - or use a different component
