### ISSUE TITLE
not working in ionic 2

### ISSUE THREAD

**Issue by ajaysaini95700** [Gbuomprisco/ng2-tag-input#336]
i am using ionic2. but whenever is deploy app it is showing error "'ng-template' is not a known element:
1. If 'ng-template' is an Angular component, then verify that it is part of this module.
2. If 'ng-template' is a Web Component then add "CUSTOM_ELEMENTS_SCHEMA" to the '@NgModule.schemas' of this component to suppress this message. "

**Comment by Gbuomprisco** [comment]
no template, no investigation :) (you probably need to upgrade to v4, anyway)
