### ISSUE TITLE
Placeholder property don't consider on load

### ISSUE THREAD

**Issue by anikets43** [Gbuomprisco/ng2-tag-input#338]
Placeholder is not considered at first entry. Thereafter, it works perfectly fine.

`<tag-input [ngModel]="[]" [onlyFromAutocomplete]="true" theme='dark' [ngModelOptions]="{standalone: true}" [onlyFromAutocomplete]="true" [placeholder]="'Add Items'">
                      <tag-input-dropdown [showDropdownIfEmpty]="true" [autocompleteItems]="capabilities">
                      </tag-input-dropdown>
                    </tag-input>`
Initially, taking default placeholder "Enter a new tag"
<img width="968" alt="screen shot 2017-04-12 at 5 54 32 pm" src="https://cloud.githubusercontent.com/assets/7136799/24957555/b66629c6-1fa9-11e7-813e-453efa8f340e.png">

Later, considering the custom placeholder.
![screen shot 2017-04-12 at 5 58 20 pm](https://cloud.githubusercontent.com/assets/7136799/24957533/a347338a-1fa9-11e7-863a-307e382b37bd.png)

Thanks,
Aniket

**Comment by saschwarz** [comment]
Change `placeholder` to `secondaryPlaceholder`. I got confused the first time too.

**Comment by amitgaur208** [comment]
Thanks. But this module have many issues in devices.

**Comment by sangwin** [comment]
I need to change "Enter a new tag" to "Add people"  and "+ Tag" to "+ People", can you please tell me the solution for this?
