### ISSUE TITLE
Exception on a tag is edited by press the enter

### ISSUE THREAD

**Issue by VVildVVolf** [Gbuomprisco/ng2-tag-input#339]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**
When I try to use editable tags - I catch an exception, you can see it at the live example site (http://www.buompris.co/ng2-tag-input/). I double click to a tag, adit it and press the enter.
In the case when I do not press the enter after editing (just live the focus from this input) - I do not see any changes on the model (but when I add new tags - I see the added tags in the model).

**Expected behavior**
I would like to have a way to edit my tags. Or at least a way to move tags from their places (It is ok to delete the first tag, create a new one and move the to the begin of list, or just create a new tag on the required place).

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
angular-cli

**Angular version:** 

  "_from": "@angular/common@>=2.3.1 <3.0.0",
  "_id": "@angular/common@2.4.3",

**ng2-tag-input version:**

  "_from": "ng2-tag-input@latest",
  "_id": "ng2-tag-input@0.8.1",

**Browser:** Chrome  57.0.2987.133 (64-bit)

**Comment by Gbuomprisco** [comment]
Hi @VVildVVolf,

I will check it out.

**Comment by VVildVVolf** [comment]
I have just found a couple of bugs, I will try to fix them.
