### ISSUE TITLE
Validation required on ng2-tag-input

### ISSUE THREAD

**Issue by simoazzo** [Gbuomprisco/ng2-tag-input#34]
Hi guys,

How can I set a required validation on the ng2-tag input field please? I mean that when user tries to submit the form and nothing has been selected, form will not be submitted.

Thank you for your help.

Kind Regards

**Comment by Gbuomprisco** [comment]
Hi, I'll add an example to the Demo soon :)

**Comment by simoazzo** [comment]
Thank you. Let me know the link then please.

Thanks

**Comment by Gbuomprisco** [comment]
Hi @simoazzo,

I added a demo to show validation using the component http://www.webpackbin.com/Vy7PtkdYW.

In reality, it does not much change compared to any other component in Angular 2. You may always want to use Model driven forms as ng2-tag-input as of now returns an empty array when no tags are entered, and therefore 'required' won't work as expected.

The example mimics a required functionality, but obviously you can add all the validations you want :)

**Comment by simoazzo** [comment]
Hi Gbuomprisco,

Thank you

Do you mind asking that if I want remove the disabled button feature,  does the form still not alllowed to be submitted?

**Comment by Gbuomprisco** [comment]
Hi @simoazzo,

Yes, normally the submit() function would still not fire :)

**Comment by simoazzo** [comment]
Hi @Gbuomprisco,

Thank you for your help.

Apart from this, regarding something related to Angular 2, may I ask you how I can accomplish a submit form with three buttons? How can I know which button was submitted? I have this form as a child component and need to know which button was submitted in the parent component?

I am asking because I cannot find help regarding this :/

Thank you in advance for your help @Gbuomprisco

**Comment by Gbuomprisco** [comment]
Hi @simoazzo,

You can still listen to (click) events on your buttons. For example (this might not be fully functioning, but it gives you a rough idea). 


`
class MyComponent {
   submit() {
   // action after submit
   //
   }
   
   click(event) {
      this.clickedButton = event.target;
      // event.target is the button clicked
      // do some action and then reset
      this.clickedButton = undefined;
   }
}
`

`
<form (submit)="submit()">
  <button (click)='click($event)'>Button 1</button>
  <button (click)='click($event)'>Button 2</button>
</form>
`

**Comment by simoazzo** [comment]
Hi @Gbuomprisco 

I tried like this.. but the value set in the click event does not restored on the submit event.

First the click event fired and then the submit but the button name for example does restored to be sent eventually to the parent component. :/

**Comment by Gbuomprisco** [comment]
Hi @simoazzo,

I thought that, unfortunately. It's not the greatest thing to do, but you could wrap your submit function in a timeout and push it next into the event loop. Hopefully it will work.

**Comment by simoazzo** [comment]
Hi @Gbuomprisco 

Mm. I did not understand you exactly what are you suggesting. Can you please take patience and explain it to me by showing me an example pls @Gbuomprisco ? And its the only solution?

Thank you in advance

Kind Regards

**Comment by Gbuomprisco** [comment]
Something like this. I have not tried yet so I am not sure it will work, but give it a try:

```typescript
class MyComponent {
   submit() {
      setTimeout(() => {
         // action after submit
         //  
         console.log(this.clickedButton);
        
         this.clickedButton = undefined;
      }, 0); // 0 or > than 0

   click(event) {
      this.clickedButton = event.target;
      // event.target is the button clicked  
   }
}
```

**Comment by simoazzo** [comment]
I will try it out and let you know tomorrow.

Thank you @Gbuomprisco

**Comment by simoazzo** [comment]
Thanks. It worked :)

**Comment by simoazzo** [comment]
Hi @Gbuomprisco 

I am trying like this:

```
click(event){
        var target = event.target;
        console.log(target.attributes.name);
        var buttonName = target.attributes.name.value;
        this._job.ButtonClicked = buttonName;

        console.log(buttonName);
        console.log(this._job.ButtonClicked);
    }
```
But the event.target is sometimes working but sometimes, the even.target will be undefined... :/

```
<button type="submit" class="btn btn-large waves-effect waves-light" name="saveAndAddJobInstruction" (click)='click($event)'>
            <span class="glyphicon glyphicon-floppy-disk"></span>
            <span class="button-text">Save & Add Job Instruction</span></button>
```

Any idea why pleasE?

Kind Regards

**Comment by kenhernando** [comment]
Hi, can I request for a re-upload of the demo for validation? Link above seems to be empty. I have a model-driven form and I'm clueless as to how to validate the input tag field with at least 1 item present on the array. Thanks

**Comment by Gbuomprisco** [comment]
Hi @kenhernando,

just look at the angular forms documentation, it is going to be just the same procedure

**Comment by jcbowyer** [comment]
Hello, if anyone has example of the required that is still available I would love to see it.  I can get required to work if I don't set a default value with ngmodel but if I set a default value, it shows invalid despite having a value.
