### ISSUE TITLE
can't change Default Placeholder "Enter a new tag"

### ISSUE THREAD

**Issue by amitgaur208** [Gbuomprisco/ng2-tag-input#340]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

Its not changing default place holder on initial load though it changed after selecting one tag. But I want to change this on initial load

**Expected behavior**

I want to have default custom place holder and when one tag selected i need to remove that placeholder

**Minimal reproduction of the problem with instructions (if applicable)**

Added tag input in html added property placeholder but not changing default placeholde of input tag

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

angular-cli

**Angular version:** 

4.0.0

**ng2-tag-input version:**

latest

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Have you checked this https://github.com/Gbuomprisco/ng2-tag-input/issues/338?
