### ISSUE TITLE
Tags in modals. Dropdown problem

### ISSUE THREAD

**Issue by ionutztamas** [Gbuomprisco/ng2-tag-input#342]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x ] support request/question
``` 

**Current behavior**

I set [showDropdownIfEmpty] to true. I focus the tag component, autocomplete dropdown appears. I click somewhere else, the dropdown is still displayed. Even i close the modal (hide it), the dropdown is still there. 

How would i go about hiding this dropdown ?
I have figured out a way to tell if the user clicked anywhere else except the component itself, but i can't seem to be able to find a way to hide the dropdown through an event or something. ( i was able to hide it by setting "display" to "none", but that's not a solution since after i focus the component the next time, it considers as it was already open and closes it,  resulting in nothing happening for the user )

**Comment by Gbuomprisco** [comment]
I see the issue. Can you try setting [appendToBody]=false? Check out the doc

**Comment by ionutztamas** [comment]
Thank, this solved the issue.

**Comment by omprakash9** [comment]
@Gbuomprisco 

Do you have property load-on-down-arrow like ng tag input to show the drop down on hitting down arrow?

**Comment by Gbuomprisco** [comment]
Hi @omprakash9,

no there is not (it would be in the readme for sure if it were :)

**Comment by omprakash9** [comment]
Hi @Gbuomprisco 

Can you try to implement that property in ng2-tag-input under V1.0.0,
If yes can you please provide me workaround on it?

**Comment by Gbuomprisco** [comment]
@omprakash9 if you maually register an event on the input and then call the dropdown API by referencing a variable (say #tagInput), you may achieve what you need.

**Comment by omprakash9** [comment]
okay thanks @Gbuomprisco
