### ISSUE TITLE
Interleave free text (non-tags) among auto-complete tags

### ISSUE THREAD

**Issue by vivian7169** [Gbuomprisco/ng2-tag-input#344]
**I'm submitting a  feature request.**

**Expected behavior**

I have a special use case where I need to interleave free text (non-tags) among auto-complete tags. Is this possible? Please advise.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

angular-cli

**Angular version:** 

angular 4
angular material 2

**Comment by Gbuomprisco** [comment]
Sorry @vivian7169,

I don't understand what you mean. Do you have an example? thanks

**Comment by vivian7169** [comment]
Which means, I can use it as textarea, some text are non-tags, then when I enter some keyword, the keyword can be seen as tags to be detected and auto-complete.

Enclosed an image as example:


Please advise, thanks.

**Comment by Gbuomprisco** [comment]
Hi @vivian7169,

can you post the image? it would help

**Comment by vivian7169** [comment]
Image for your reference:
![example](https://cloud.githubusercontent.com/assets/5425198/25110566/a042e522-2417-11e7-81c7-709894e0f112.png)

Thanks!

**Comment by Gbuomprisco** [comment]
Hi @vivian7169,

this is surely not possible. It does look like your use case would require a select, rather than input tags?

**Comment by Gbuomprisco** [comment]
In general UX terms - a select would be more appropriate for what you are trying to do. Obviously, I do not know your requirements, but if you need the user to select the option for each "box", a select is definitely best (or, maybe, an autocomplete select that allows free text).

`ng2-material-select` is just a list of options you can use, doesn't allow free text if you need it. I am sure though there will be components out there that will allow it :)
