### ISSUE TITLE
Can't import ng2-tag-input to Angular Cli project

### ISSUE THREAD

**Issue by krooshua** [Gbuomprisco/ng2-tag-input#345]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

ERROR in ../ngModules/shared/src/app/app.module.ts
Module not found: Error: Can't resolve 'ng2-tag-input'

**Expected behavior**

app works

**Minimal reproduction of the problem with instructions (if applicable)**

Start new project via angular cli ("@angular/cli": "1.0.0",), and try to add ng2-tags-input to it.

Imported in app.module.ts

import { TagInputModule } from 'ng2-tag-input';
 imports: [
    TagInputModule
  ],

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

 angular cli ("@angular/cli": "1.0.0",)

**Angular version:** 

4.0.0

**ng2-tag-input version:**

1.05

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by krooshua** [comment]
Hi there.

I'm trying to add ng2-tag-input to new Angular Cli project, and receive an error:

`ERROR in ../ngModules/shared/src/app/app.module.ts
Module not found: Error: Can't resolve 'ng2-tag-input'`

Any advice here?

**Comment by Gbuomprisco** [comment]
Have you installed the module with npm?

**Comment by krooshua** [comment]
Hi Gbuomprisco!

Yes, module installed. Tried with versions 1.0.4 and 1.0.5

`"dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "core-js": "^2.4.1",
    "ng2-tag-input": "1.0.5",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },`

I think issue in imports, maybe I need to define typings for it, in some angular cli config?

**Comment by Gbuomprisco** [comment]
No you shouldn't need it.

Can you post here the content of app.module.ts and the complete stacktrace? cheers

**Comment by krooshua** [comment]
`import { CommonModule } from '@angular/common';
//import { BrowserAnimationsModule } from '@angular/platform-browser';
import { NgModule, ModuleWithProviders } from '@angular/core';

import { SharedComponent } from './app.component';

//pipes
import { SafeHtmlPipe } from './pipes/safe-html.pipe';
import { TagUserPipe } from './pipes/tag-user.pipe';
import { CheckIframePipe } from './pipes/check-iframe.pipe';
import { TagsInputComponent } from './tags-input/tags-input.component';

import { TagInputModule } from 'ng2-tag-input';


@NgModule({
  declarations: [
    SharedComponent,
    SafeHtmlPipe,
    TagUserPipe,
    CheckIframePipe,
    TagsInputComponent
  ],
  imports: [
    CommonModule,
    TagInputModule
  ],
  providers: [],
  bootstrap: [SharedComponent],
  exports: [
    SharedComponent,
    SafeHtmlPipe,
    TagUserPipe,
    CheckIframePipe,
    TagsInputComponent
  ]
})
export class SharedModule {
  public static forRoot(): ModuleWithProviders {
    return {
      ngModule: SharedModule,
      providers: [

      ]
    };
  }
}
`

`ERROR in ../ngModules/shared/src/app/app.module.ts
Module not found: Error: Can't resolve 'ng2-tag-input' in 'ngModules\shared\src\app'
 @ ../ngModules/shared/src/app/app.module.ts 16:0-47
 @ ../ngModules/shared.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts`

**Comment by Gbuomprisco** [comment]
`BrowserAnimationsModule` needs to be imported - but I don't think it's the issue really. Try see if the module is in node_modules, and also if the intellisense of your IDE catches it. The rest looks just fine..

**Comment by VVildVVolf** [comment]
I have added the BrowserAnimationsModule (from '@angular/platform-browser/animations') to the ng2-tag-input.module.ts - without this importing I cannot run the project. Would it be better to commit it?

**Comment by krooshua** [comment]
Hey, I'm found the issue.
Maybe it will helps someone else. 
If you are using tag-input inside separated-shared ngModule, then you need also add dependencies to main app.

E.g. run `npm install ng2-tag-input --save` from main app folder, and from separated folder with Shared ngModule.

**Comment by Gbuomprisco** [comment]
Cool - thanks! (this should apply for all modules)

**Comment by rochapablo** [comment]
I'm having quite the same problem;

When I run locally it works but when I deploy into Heroku it fail.

```
ERROR in ./src/$$_gendir/app/app.module.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/ng2-tag-input.module' in '/tmp/build_.../src/$$_gendir/app'
@ ./src/$$_gendir/app/app.module.ngfactory.ts 39:0-68
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/app/.../component.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/components/tag-input' in '/tmp/build_.../src/$$_gendir/app/component'
@ ./src/$$_gendir/app/.../component.ngfactory.ts 12:0-67
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/app/.../component.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/components/dropdown/tag-input-dropdown.component' in '/tmp/build_.../src/$$_gendir/app/component'
@ ./src/$$_gendir/app/.../component.ngfactory.ts 14:0-95
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/components/tag-input' in '/tmp/build_.../src/$$_gendir/node_modules/ng2-tag-input/dist/components'
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input.ngfactory.ts 12:0-67
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/~/ng2-tag-input/dist/components/dropdown/tag-input-dropdown.component.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/components/tag-input' in '/tmp/build_.../src/$$_gendir/node_modules/ng2-tag-input/dist/components/dropdown'
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/dropdown/tag-input-dropdown.component.ngfactory.ts 18:0-68
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/~/ng2-tag-input/dist/components/dropdown/tag-input-dropdown.component.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/components/dropdown/tag-input-dropdown.component' in '/tmp/build_.../src/$$_gendir/node_modules/ng2-tag-input/dist/components/dropdown'
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/dropdown/tag-input-dropdown.component.ngfactory.ts 17:0-96
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/components/tag/tag.component' in '/tmp/build_.../src/$$_gendir/node_modules/ng2-tag-input/dist/components'
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input.ngfactory.ts 10:0-75
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/~/ng2-tag-input/dist/components/tag/tag.component.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/components/tag/tag.component' in '/tmp/build_.../src/$$_gendir/node_modules/ng2-tag-input/dist/components/tag'
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag/tag.component.ngfactory.ts 14:0-75
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/components/tag-input-form/tag-input-form.component' in '/tmp/build_.../src/$$_gendir/node_modules/ng2-tag-input/dist/components'
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input.ngfactory.ts 14:0-97
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input-form/tag-input-form.component.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/components/tag-input-form/tag-input-form.component' in '/tmp/build_.../src/$$_gendir/node_modules/ng2-tag-input/dist/components/tag-input-form'
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input-form/tag-input-form.component.ngfactory.ts 9:0-97
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/~/ng2-tag-input/dist/components/dropdown/tag-input-dropdown.component.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/core/pipes/highlight.pipe' in '/tmp/build_.../src/$$_gendir/node_modules/ng2-tag-input/dist/components/dropdown'
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/dropdown/tag-input-dropdown.component.ngfactory.ts 12:0-72
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/~/ng2-tag-input/dist/components/tag/tag.component.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/components/tag/tag-ripple.component' in '/tmp/build_.../src/$$_gendir/node_modules/ng2-tag-input/dist/components/tag'
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag/tag.component.ngfactory.ts 13:0-82
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/~/ng2-tag-input/dist/components/tag/tag-ripple.component.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/components/tag/tag-ripple.component' in '/tmp/build_.../src/$$_gendir/node_modules/ng2-tag-input/dist/components/tag'
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag/tag-ripple.component.ngfactory.ts 8:0-82
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag/tag.component.ngfactory.ts
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/~/ng2-tag-input/dist/components/tag/tag.component.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/components/icon/icon' in '/tmp/build_.../src/$$_gendir/node_modules/ng2-tag-input/dist/components/tag'
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag/tag.component.ngfactory.ts 11:0-67
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts

ERROR in ./src/$$_gendir/~/ng2-tag-input/dist/components/icon/icon.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/components/icon/icon' in '/tmp/build_.../src/$$_gendir/node_modules/ng2-tag-input/dist/components/icon'
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/icon/icon.ngfactory.ts 9:0-67
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag/tag.component.ngfactory.ts
@ ./src/$$_gendir/~/ng2-tag-input/dist/components/tag-input.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/.../component.ngfactory.ts
@ ./src/$$_gendir/app/app.module.ngfactory.ts
@ ./src/main.ts
@ multi ./src/main.ts
```

The angular-cli.json

```
"packages": {
   ...
    "ng2-tag-input": {
      "defaultExtension": "js"
    }
  },
```

The package.json

```
"@angular/core": "^4.0.3",
"ng2-tag-input": "^1.0.5",
```

My app.module

```
import { TagInputModule } from 'ng2-tag-input';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';

imports: [
   ...
   TagInputModule,
   BrowserAnimationsModule
]
```

So, what could I be missing?

**Comment by Gbuomprisco** [comment]
Hi @rochapablo,

yours seems an issue with AOT. Can you please post the versions for the cli and the component? Also, I assume if you run the AOT compilation locally, you'll encounter the same error. Please confirm the latter as it would narrow down the issue a bit :)

**Comment by rochapablo** [comment]
Hello @Gbuomprisco,

Here's the versions:

```
angular/cli : 1.0.1
angular: 4.0.3
ng2-tag-input: 1.0.5
```

If I run ```ng build --prod``` locally (which is the same command at Heoku) I don't get those errors.

**Comment by Gbuomprisco** [comment]
Check out carefully the ng2-tag-input version as the caret is prepended to the version in you package.son (so you'll need to manually check the package.son in your node modules)

**Comment by rochapablo** [comment]
Okay, here's the package.json from *node_modules\ng2-tag-input*

```
{
  "_args": [
    [
      {
        "raw": "ng2-tag-input",
        "scope": null,
        "escapedName": "ng2-tag-input",
        "name": "ng2-tag-input",
        "rawSpec": "",
        "spec": "latest",
        "type": "tag"
      }
    ]
  ],
  "_from": "ng2-tag-input@latest",
  "_id": "ng2-tag-input@1.0.5",
  "_resolved": "https://registry.npmjs.org/ng2-tag-input/-/ng2-tag-input-1.0.5.tgz",
  "dist": {
    "tarball": "https://registry.npmjs.org/ng2-tag-input/-/ng2-tag-input-1.0.5.tgz"
  },
  "version": "1.0.5"
}
```

**Comment by Gbuomprisco** [comment]
The config is not needed, that's only with SystemJS. 

Sorry i am not experienced with Heroku, but where is the build process being run? Are using a CI that then deploys to Heroku?

**Comment by rochapablo** [comment]
No problem,

Yes heroku capture the ```git push``` and build the package.

It run in these sequence:

```
1. npm install @angular/cli

2. npm install

3. ng build --prod --aot
```

Then 

```
11% building modules 16/17 modules 1 active ...
       Hash: 30bfe8fa2f7283046123
       Time: 86208ms
       chunk    {0} main.ebdb02bf9146a9291512.bundle.js (main) 2.46 MB {2} [initial] [rendered]
       chunk    {1} styles.c4fc5af94dc1171ea8ca.bundle.css (styles) 228 bytes {3} [initial] [rendered]
       chunk    {2} vendor.3cbc52550762f6ded67b.bundle.js (vendor) 3.7 MB [initial] [rendered]
       chunk    {3} inline.df43b248373c4a8e4a6d.bundle.js (inline) 0 bytes [entry] [rendered]
       
       ERROR in ./src/$$_gendir/app/app.module.ngfactory.ts
       ...
```

**Comment by rochapablo** [comment]
@Gbuomprisco, could this (https://github.com/angular/angular-cli/issues/5733#issuecomment-290484606) mean something?

**Comment by Gbuomprisco** [comment]
All points should be respected as far as I know

**Comment by webcat12345** [comment]
@rochapablo , actually I created that issue , and that is not related with Heroku deploy at all.
Any info that I can reproduce that error?

**Comment by Gbuomprisco** [comment]
@webcat12345 I think the issue was in this component, not Heroku nor the cli :)

**Comment by webcat12345** [comment]
Thanks for your info @Gbuomprisco . I am going to create repository for test deploy with heroku. After doing that will post comment here.

**Comment by webcat12345** [comment]
https://github.com/webcat12345/heroku-ng2-tag-input-test

This is repository url. Travis and Heroku integrated.

AoT build fails. Actually on local. 

ng2-tag-input package version is : 1.2.5
angular & angular-cli version is : 4.1.0

Build progress is here.
https://travis-ci.org/webcat12345/heroku-ng2-tag-input-test

I think problem is : 
Path : `node_modules/ng2-tag-input/dist/modules/components/tag/tag.template.html`
Template : `(dblclick)="editable ? toggleEditMode($event) : undefined"`
Component : `TagComponent.prototype.toggleEditMode = function () {`

Component Code should contains parameter.
https://github.com/angular/angular-cli/issues/5733#issuecomment-291089841

**Comment by Gbuomprisco** [comment]
Strange the repo's version doesn't catch that, I'll try updating Angular (sorry, I won't be able right away)

**Comment by webcat12345** [comment]
Thanks @Gbuomprisco  Take your time, Will wait your update.

**Comment by webcat12345** [comment]
Thanks, Its working.
