### ISSUE TITLE
Scroll through limited number of autocomplete tags

### ISSUE THREAD

**Issue by ionutztamas** [Gbuomprisco/ng2-tag-input#346]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request/question
```

**Current behavior**

If i have 10 items in autocomplete dropdown, the components limits them to 8 and allows me to scroll through all of them. If i set the [limitItemsTo] property to 5, it only displays 5 and doesn't allow me to scroll trough them ( which works as intended )

**Expected behavior**

Shoudn't there be an option to set "limitDisplayedItemsTo" or something like that ? 

I want to limit the items displayed to 5, but still scroll to the entire list dropdown list ( like the default behaviour, but less items)

**Comment by Gbuomprisco** [comment]
Sorry that's a bit problematic. You may want to just override the css and set the max-height for the dropdown. Remember that you need to use >>> as the styles are encapsulated
