### ISSUE TITLE
Is there a way to disable animations altogether?

### ISSUE THREAD

**Issue by sylvaingi** [Gbuomprisco/ng2-tag-input#347]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request/question
```

**Current behavior**
Component uses animations for tag entry, exit, etc. I'm wondering if there's a way to disable those.

**Comment by Gbuomprisco** [comment]
not at this time, sorry

**Comment by sylvaingi** [comment]
If I were to make a PR, do you have any pointers for where I should start? Is it even possible at all?

**Comment by Gbuomprisco** [comment]
@sylvaingi,

while I was implementing it and was looking for the same exact thing (e.g. an @input property to enable it optionally), but I do not thing Angular makes it possible at this moment.

**Comment by sylvaingi** [comment]
Well that's a bummer. Thanks anyway 👍

**Comment by Gbuomprisco** [comment]
@sylvaingi,

Out of curiosity, is it a requirement to remove the animations or do you just not like them at all? :)

**Comment by Gbuomprisco** [comment]
If you were to fork it is just going to be a bunch of lines to be removed anyway

**Comment by sylvaingi** [comment]
Well, I have a settings page with many tags-input that can hold a lot tags, and whenever I refresh the backing data, I lose the scroll position because of the animation. It's also quite distracting with that many elements.

**Comment by sylvaingi** [comment]
It's entierely possible I am not using the component the way it was designed though.

**Comment by Gbuomprisco** [comment]
I see - thanks!

**Comment by k10der** [comment]
Not quite sure when exactly it was added, but It looks like now it's possible to control animations disabled state by defining `[@.disabled]="isDiabled"` binding on `<tag-input>` component https://angular.io/api/animations/trigger#disabling-animations
