### ISSUE TITLE
Issues with ng2-tag-input 1.0.5 and angular-cli 1.0.0

### ISSUE THREAD

**Issue by transparentech** [Gbuomprisco/ng2-tag-input#349]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**
With an ng2 app created with angular-cli v1.0.0, tag-inputs don't display existing tags nor is it possible to add new tags.

**Expected behavior**
Tags should be displayed and adding tags should be possible with an angular-cli generated app.

**Minimal reproduction of the problem with instructions (if applicable)**
I've created a stock angular-cli app. Then added the ng2-tag-input package. Then added the module to app.modules.ts. Then added the tag-input and model to app.

I've uploaded the project here:  https://github.com/transparentech/tag-ng2-input-test

Clone the project, then run `npm install`, then `ng serve`, then try at `localhost:4200`.

**What is the motivation / use case for changing the behavior? (if applicable)**
I would like to use ng2-tag-input in my angular-cli generated app.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
angular-cli v1.0.0
osx 10.12.4
node 7.7.4

**Angular version:** 
@angular/cli: 1.0.0
node: 7.7.4
os: darwin x64
@angular/common: 4.0.2
@angular/compiler: 4.0.2
@angular/core: 4.0.2
@angular/forms: 4.0.2
@angular/http: 4.0.2
@angular/platform-browser: 4.0.2
@angular/platform-browser-dynamic: 4.0.2
@angular/router: 4.0.2
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.2

**ng2-tag-input version:**
^1.0.5

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
chrome 58, firefox 52.0.1, safari 10.1

**Comment by Gbuomprisco** [comment]
Hi @transparentech,

have you added BrowserAnimationsModule?

**Comment by transparentech** [comment]
Just tried that and yes, adding @angular/animations dependency and BrowserAnimationsModule makes it work as expected. 

I might suggest also updating the doc to note that "@angular/animations" dependency is required for BrowserAnimationsModule.

Thanks for the help.

**Comment by Gbuomprisco** [comment]
done :)
