### ISSUE TITLE
angular2 rc5 integration

### ISSUE THREAD

**Issue by sbahmani** [Gbuomprisco/ng2-tag-input#35]
How to use in angular2 rc5? bootstrap model has been changed. 
How to use with NgModule?

**Comment by Gbuomprisco** [comment]
Hi @sbahmani, I still need to update this to Angular RC5, I hope to do it soon

**Comment by sbahmani** [comment]
Hi @Gbuomprisco , Thank You. I hope you do it soon :)

**Comment by Gbuomprisco** [comment]
HI @sbahmani,

I published the version 0.2.2, with examples on integration with RC.5. From your point of view it doesn't change much, you only need to bootstrap the app in the new way and import the component in the container component. 

The files in /demo show how to do it anyway, or the demo on Webpack Bin you find in the README.md 👍

**Comment by sbahmani** [comment]
Hi @Gbuomprisco , Thank you very much.

**Comment by sbahmani** [comment]
> animation trigger expressions within the template that are assigned as an element attribute (e.g. @prop) are deprecated. Please use the Angular2 property binding syntax (e.g. [@prop]) when assigning properties.
```
// this is now deprecated
<div @trigger="expression"></div>

// do this instead
<div [@trigger]="expression"></div>
```

**Comment by Gbuomprisco** [comment]
Hi, that should be fixed now :)

**Comment by sbahmani** [comment]
Thank you @Gbuomprisco , The warning disappear but still there is a error:
```
EXCEPTION: Error: Uncaught (in promise): Cannot read property 'toString' of null
platform-browser.umd.js:937 EXCEPTION: Error: Uncaught (in promise): Cannot read property 'toString' of nullBrowserDomAdapter.logError @ platform-browser.umd.js:937
platform-browser.umd.js:937 STACKTRACE:BrowserDomAdapter.logError @ platform-browser.umd.js:937
platform-browser.umd.js:937 Error: Uncaught (in promise): Cannot read property 'toString' of null
    at resolvePromise (zone.js:538)
    at resolvePromise (zone.js:523)
    at zone.js:571
    at ZoneDelegate.invokeTask (zone.js:356)
    at Object.onInvokeTask (core.umd.js:9236)
    at ZoneDelegate.invokeTask (zone.js:355)
    at Zone.runTask (zone.js:256)
    at drainMicroTaskQueue (zone.js:474)
    at XMLHttpRequest.ZoneTask.invoke (zone.js:426)BrowserDomAdapter.logError @ platform-browser.umd.js:937
zone.js:461 Unhandled Promise rejection: Cannot read property 'toString' of null ; Zone: angular ; Task: Promise.then ; Value: Cannot read property 'toString' of nullconsoleError @ zone.js:461
zone.js:463 Error: Uncaught (in promise): Cannot read property 'toString' of null(…)
``` 

I think in `ng2-dropdown.bundle.js` at this code ` [@fade]=\"state.toString()\"` state is null.

**Comment by Gbuomprisco** [comment]
Thanks @sbahmani, I'll have a look soon. Hopefully this doesn't block you?

**Comment by sbahmani** [comment]
Thanks @Gbuomprisco , No it's OK but I confused with my errors and the error.

**Comment by sbahmani** [comment]
Sorry, It's not your bug, the bug occurred for  other RC5 change.
Thanks.

**Comment by Gbuomprisco** [comment]
Cool, no worries 👍
