### ISSUE TITLE
 array is long enough

### ISSUE THREAD

**Issue by MIAOMIAOUP** [Gbuomprisco/ng2-tag-input#351]
When the initial array is long enough，It will be an exception occurs。
suchlike
 <tag-input   [ngModel]="['asdasdasdass', 'aaaaaaaaaaaaa', 'cccccccccccccc', 'sssssssss', 'dddddddd', 'sdsadsadsadas', '80', '90', '95ssssssssss','ssad','sssssssssswww']" [readonly]="true"></tag-input>
Maybe when it is built, and there is no word wrap。

**Comment by Gbuomprisco** [comment]
Please complete the template, add a stracktrace or any other helpful information.
