### ISSUE TITLE
Add items by space not working

### ISSUE THREAD

**Issue by florianbuehlmann** [Gbuomprisco/ng2-tag-input#359]
**I'm submitting a**
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**
On your demo website (http://www.buompris.co/ng2-tag-input/) the "An input which allows adding items by pressing the key "space" of your keyboard" doesn't work. It doesn't add the tag when pressing "space". One has to hit "Enter" still instead. Tested on Chrome 58 and Edge.

**Expected behavior**
Add the tag when pressing space.

**Minimal reproduction of the problem with instructions (if applicable)**
Check demo website.

**Browser:** 
Chrome 58, Edge

**Comment by Gbuomprisco** [comment]
Hi @florianbuehlmann,

are you using separatorKey or separatorKeyCodes? (demo is outdated, sorry)

**Comment by florianbuehlmann** [comment]
Hi @Gbuomprisco 

Thanks for the quick reply.
Indeed the demo looks outdated, but no need to be sorry. I am thankful for even have access to a demo page.

It looks like the following code on your tutorial doesn't work:
Under **Additional keys to separate tags** there is:
`<tag-input [(ngModel)]='items' [separatorKeys]="[32]"></tag-input>`

However some lines above it says that separatorKeys is an "Array of input characters with which is possible to define the key for separating terms". So I should probably enter a space " " instead of 32 (ASCII-Code)?

The following code works like a charm though:
`<tag-input [(ngModel)]='items' [separatorKeyCodes]="[32]"></tag-input>`

So thanks for pointing me to the solution, this one works fine 👍

**Comment by Gbuomprisco** [comment]
That array should match values such as https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key/Key_Values. Problem is it is not fully compatible.

Use [separatorKeyCodes] unless you have localization issues.

Glad it works now 👍
