### ISSUE TITLE
Help me for Autocomplete

### ISSUE THREAD

**Issue by WebTalentTop** [Gbuomprisco/ng2-tag-input#361]
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request/question
```

**Current behavior**
Autocomplete added items are not showing more.

**Expected behavior**
 I think there should be a feature for not removing already added items.

**Minimal reproduction of the problem with instructions (if applicable)**
Not sure

**What is the motivation / use case for changing the behavior? (if applicable)**
Improve its variety.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
MAC

**Angular version:** 
2/4

**ng2-tag-input version:**
latest version

**Browser:** Chrome

**Comment by Gbuomprisco** [comment]
Do you mean to add a new option so that the items in the autocomplete which have already been added will still be visible? Can you provide a use-case? I can only see that useful if the user set `[allowDupes]` to `true`, it would be misleading UX otherwise, and I cannot second that case.

**Comment by WebTalentTop** [comment]
Yeah Let's imagine, we can use this library for other purpose.
I think there should be option for keeping autocomplete list items.
It would be useful when users hate to type common words by typing. It could be sentence or phrase.
If you don't need this feature, then please help me to turn it on for autocomplete.
Thanks.

**Comment by WebTalentTop** [comment]
I have a specific purpose.
So please guide me how to unremoved already added items from autocomplete.
Thanks.

**Comment by Gbuomprisco** [comment]
Sorry but I don't think it's possible

**Comment by WebTalentTop** [comment]
Yeah....Thanks, By the way, it is a great stuff.
