### ISSUE TITLE
Cannot AOT compile 1.2.0

### ISSUE THREAD

**Issue by Simon-Briggs** [Gbuomprisco/ng2-tag-input#366]
**I'm submitting a ...**  (check one with "x")
```
[ x] bug report => search github for a similar issue or PR before submitting
```

**Current behavior**

This message repeated for each use of ng2-tag-input

```

ERROR in ./src/$$_gendir/views/dashboard/dashboard.module.ngfactory.ts
Module not found: Error: Can't resolve 'ng2-tag-input/dist/ng2-tag-input.module' in '/workspace/src/$$_gendir/views/dashboard'
 @ ./src/$$_gendir/views/dashboard/dashboard.module.ngfactory.ts 24:0-67
 @ ./src/$$_gendir async
 @ ./~/@angular/core/@angular/core.es5.js
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://localhost:4200 ./src/main.ts


```

**Expected behavior**

With version 1.0.5 I could compile my app fine. I've fixed the version of this project for now in my package.json

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

Mac OSX, Angular cli 1.0.0

**Angular version:** 
4.0.1

**ng2-tag-input version:**
1.2.0 is broken
1.0.5 is working

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

AOT build step

**Comment by hackash** [comment]
I have the same issue with 1.2.0

**Comment by Gbuomprisco** [comment]
Yeah - trying to understand what happened

**Comment by rochapablo** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/issues/345

**Comment by Gbuomprisco** [comment]
@rochapablo try fixing the version to 1.0.5 for now

**Comment by hackash** [comment]
version 1.0.5 works for me.

**Comment by rochapablo** [comment]
@Gbuomprisco, thank you. Version 1.0.5 worked (https://ng2-tag-input.herokuapp.com/).

**Comment by Gbuomprisco** [comment]
1.2.2 should be good now :)
