### ISSUE TITLE
Cannot Compile, help-me please!

### ISSUE THREAD

**Issue by rdiegoss** [Gbuomprisco/ng2-tag-input#367]
I'm submitting a ... (check one with "x")

[ x] bug report => search github for a similar issue or PR before submitting
Current behavior

This message repeated for each use of ng2-tag-input

<img src="http://ap.imagensbrasil.org/images/2017/04/26/ScreenShot2017-04-26at22.44.28.png" alt="ScreenShot2017-04-26at22.44.28.png" border="0">
<img src="http://ap.imagensbrasil.org/images/2017/04/26/ScreenShot2017-04-26at22.46.14.png" alt="ScreenShot2017-04-26at22.46.14.png" border="0">

Expected behavior

With version 1.0.0 I could compile my app fine. But not work Drag and Drop.

What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version

Mac OSX, Webpack

Angular version:
2.4.6

ng2-tag-input version:
1.2.0 is broken
1.0.5 is broken
1.0.0 work (without drag and drop)

Browser: [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

AOT build step

**Comment by Simon-Briggs** [comment]
Renderer2 is new to angular 4, so won't work angular 2.X.
You'll have to lock the version of this library at a lower version until you upgrade to ng4?

**Comment by Gbuomprisco** [comment]
Stick to 1.0.0 or update your project. A release cannot be changed.
