### ISSUE TITLE
Angular 4.1.0 AoT error

### ISSUE THREAD

**Issue by lbertenasco** [Gbuomprisco/ng2-tag-input#373]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

```
ERROR in Unexpected value 'Ng2DropdownModule in /project/web/node_modules/ng2-material-dropdown/index.ts' imported by the module 'TagInputModule in /project/web/node_modules/ng2-tag-input/dist/modules/index.d.ts'. Please add a @NgModule annotation.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/project/web/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
```

**Expected behavior**

`ng build -prod --aot`to work

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

angular-cli

**Angular version:** 

4.1.0

**ng2-tag-input version:**

1.2.2

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
1.2.6 is now published
