### ISSUE TITLE
Its possible add class in "ng-tag-input" (no InputClass)?

### ISSUE THREAD

**Issue by rdiegoss** [Gbuomprisco/ng2-tag-input#376]
[x ] support request/question

**Current behavior**
It's possible to apply class in ng-tag-Input ? (No inputClass) , i wanna show only tag, without input.

**Expected behavior**
Show only Tag, without input tag, and click in TAG and add in other ng-tag-input.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

WebPack/MacOs

**Angular version:** 
Angular 2.x

**ng2-tag-input version:**
1.0.0

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
All

**Comment by Gbuomprisco** [comment]
Sorry you need to phrase this better - I didn't understand

**Comment by rdiegoss** [comment]
I would like to do this:

![capturar](https://cloud.githubusercontent.com/assets/10976074/25526319/6a42bd74-2be9-11e7-88d2-288bf1ec3b31.PNG)

One field with input and other below without input (Only tags static), have any class to do this? Or its possible apply class to do this?

Thank you!

**Comment by Gbuomprisco** [comment]
Ah sorry, this is not possible at all right now
