### ISSUE TITLE
Shared autocomplete value no duplicate on multiple input tags

### ISSUE THREAD

**Issue by hsuanweifu** [Gbuomprisco/ng2-tag-input#378]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request/question
```

**Current behavior**

Current feature checks only against parent tag inputs for duplicates. The is to feature that checks the autocomplete against multiple tag inputs for duplicates.

**Expected behavior**

an attribute that checks for the same "autocomplete zone"? It would be similar to dragzone.

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

An item can belong in no group or one group but not multiple groups.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

angular-cli: 1.0.0
windows 10
phpStorm

**Angular version:** 

angular: 4.0.2

**ng2-tag-input version:**

1.0.2

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Comment by Gbuomprisco** [comment]
Sorry this seems out of scope. You could achieve this functionality by playing witht he events anf adjusting the models passed to the components accordingly. Happy to merge a PR if you want though.
