### ISSUE TITLE
[Enhancement] Multiple tag-inputs should allow having each its own selected tag

### ISSUE THREAD

**Issue by bastienJS** [Gbuomprisco/ng2-tag-input#381]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x ] feature request
[ ] support request/question
```

**Current behavior**
1. Click on any tag of tag-input1 control
2. Click on another tag of tag-input2 control.
3. The selected tag of tag-input1 control is deselected
4. The selected tag of tag-input2 control is selected

**Expected behavior**
1. Click on any tag of tag-input1 control
2. Click on another tag of tag-input2 control.
3. The selected tag of tag-input1 control is **still** selected
4. The selected tag of tag-input2 control is selected

**Minimal reproduction of the problem with instructions (if applicable)**
see your demo page :-)

**What is the motivation / use case for changing the behavior? (if applicable)**
Well I just have 2 collection of entities: schoolclasses and subjects.
In order to assign a subject to a student, a subject must be selected AND a schoolclass must be selected.
One without the other can not work.

**Comment by bastienJS** [comment]
I have just re-pro your demo site. Maybe I misunderstand something about the blue selection which rather seems to be the focus.

**Comment by Gbuomprisco** [comment]
I think there is an issue with the UX you're trying to apply: the selected tag just refers to the focused input in order for this to be either removed or edited, but it's not to select a tag as a model. The input tag permits the collection of a list of tags, but selecting a tag among these is not its purpose. You should maybe build a select using the model of the input tags and use a select for the user to choose the tag they want. Hope it's clar :)

**Comment by bastienJS** [comment]
@Gbuomprisco Not sure wether I did understand you correctly: Can I make a feature request that you supply the selected tag feature? Or did you mean you do not want to have this feature in your input tag?
