### ISSUE TITLE
Not work event (onAdd)

### ISSUE THREAD

**Issue by h4mit** [Gbuomprisco/ng2-tag-input#383]
After update component to 1.2.4 version, not working event onAdd and onRemove !!

**Angular version:** 
4.1.0

**ng2-tag-input version:**
"ng2-tag-input": "^1.2.4"

**Browser:** [ Chrome XX | Firefox XX  ]

**Comment by atulhm** [comment]
onAdd doesn't work for me but onRemove is firing.

**Comment by atulhm** [comment]
In case anyone else runs into issues I changed my version to 1.2.2 and both onAdd and onRemove are working fine. 1.2.3 threw observable errors.

**Comment by h4mit** [comment]
onRemove  is firing for me too, but onAdd doesn't work 😢

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/384

**Comment by Gbuomprisco** [comment]
Released v1.2.5
