### ISSUE TITLE
Cannot add second tag from requestAutocompleteItems.

### ISSUE THREAD

**Issue by juntaforce** [Gbuomprisco/ng2-tag-input#386]
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

After Upgrade Angular 4 can not add second tag from requestAutocompleteItems. First tag can add from requestAutocompleteItems but second tag not.

**Expected behavior**

We can add second, third, ... item from requestAutocompleteItems 

**Minimal reproduction of the problem with instructions (if applicable)**
`<tag-input 
	[(ngModel)]="itemsAsObjects"
	[ngModelOptions]="{standalone: true}"
	theme='bootstrap'
	[displayBy]="'name'"
	[identifyBy]="'$key'"
	placeholder="+Yeni"
	secondaryPlaceholder="Etiket Ekle"
	(onAdd)="onAdd($event)"
	(onRemove)="onRemove($event)">			
		<tag-input-dropdown 
			[autocompleteItems]="itemsAsObjects"
		        [autocompleteObservable]="requestAutocompleteItems"
		        [displayBy]="'name'"
			[identifyBy]="'$key'">
		</tag-input-dropdown>	
</tag-input>`

`public requestAutocompleteItems = (text: string) : Observable<Response> => {
    
      this.tags =  this.af.database.list('/Tags', {
       query:{
         orderByChild: 'name',
         startAt: text,
         endAt: (text + '\uf8ff')
       }
      }
     );`

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

**Angular version:** 
4.0.2 Also Im using Angularfire 2 to get 

**ng2-tag-input version:**
1.2.5

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
It's possible that it happens if you use both autocompleteItems and autocompleteObservable. You should only use one of them

**Comment by juntaforce** [comment]
[autocompleteItems]="itemsAsObjects"
I removed but its still  same ??

**Comment by juntaforce** [comment]
Thaknks anyway  to your help :)

**Comment by Gbuomprisco** [comment]
Sorry, but you're using the same object for the model AND the autocomplete items? That doesn't make sense does it?

**Comment by juntaforce** [comment]
Sorry if I understood wrongly your logic. But I tried to achieve this;
When I wrote an item "mod" for example  (mod=> model, modal, modern) firstly these three items comes from  observable then I can choose one of them or I can  write (moderate) instead of observable items.
Then item add to itemsAsObjects.
This works before upgrade to Angular 4 as you see below.

`<ion-item>
						<tag-input 
						[(ngModel)]="itemsAsObjects"
						[ngModelOptions]="{standalone: true}"
						theme='bootstrap'
						[displayBy]="'name'"
						[identifyBy]="'$key'"
						placeholder="+Yeni"
						secondaryPlaceholder="Etiket Ekle"
						(onAdd)="onAdd($event)"
						(onRemove)="onRemove($event)">
							<tag-input-dropdown 
							[autocompleteItems]="itemsAsObjects"
							[focusFirstElement]="true"
							[autocompleteObservable]="requestAutocompleteItems"
							[displayBy]="'name'"
							[identifyBy]="'$key'">
							</tag-input-dropdown>
						</tag-input>
					</ion-item>`

`itemsAsObjects:Array<Object> = [];`
`removableTags: Array<Object> = [];`
`public requestAutocompleteItems = (text: string) : Observable<Response> => {
    
      this.tags =  this.af.database.list('/Tags', {
       query:{
         orderByChild: 'name',
         startAt: text,
         endAt: (text + '\uf8ff')
       }
      }
     );
    
     this.tags.map(snaps => snaps);
    
     return this.tags;
    }`
`public onAdd(item:any) {
      if(item.name === item.$key){

        this.tags = this.af.database.list('/Tags');
        this.tags.push({name:item.name}).then((newkey) =>{
          item.$key = newkey.key;
          this.removableTags.push({$key:newkey.key});
        });           
      }
    }`
`public onRemove(item:any) {
        
        this.removableTags.map((removable:any) => {
          if(removable.$key === item.$key)
              {
                // this.removetags = this.af.database.object('/Tag/${item.$key}');
                this.tags.remove(item.$key);
                this.removableTags.splice(this.removableTags.indexOf(item), 1);
              }
        });
    }`

**Comment by juntaforce** [comment]
`tags: FirebaseListObservable<any>;`
So in requestAutocompleteItems
`return this.tags;`

already return observable. there is no issue in there.

**Comment by juntaforce** [comment]
![image](https://cloud.githubusercontent.com/assets/12537343/25599906/75531e1e-2ee8-11e7-8a33-f7dc4c41175f.png)

İssue should be related that ??
$key which I added identifyBy comes undefined

If I removed 
[displayBy]="'name'" [identifyBy]="'$key'"
It says that 
Cannot read property 'toString' of undefined

**Comment by Gbuomprisco** [comment]
Not sure if I'm misunderstanding your code from these sippets, but you are adding key when an item has been added, in `onAdd`. You need that before it gets to the component.

Can you reproduce you issue here? http://www.buompris.co/ng2-tag-input/

**Comment by juntaforce** [comment]
I think I found the issue which is  related Firebase observable. 
`tags: FirebaseListObservable<any>;`

If I dont use  ` [displayBy]="'name'" [identifyBy]="'$key'"` in `<tag-input-dropdown>` component, firebase observable do not match  your matching function. If I use, $key comes always undefined as you see above.

If I use `[displayBy]="'name'" [identifyBy]="'$key'"` in `<tag-input>` component I can not add second tag from Firebase observable which is come in `<tag-input-dropdown>`

**Comment by Gbuomprisco** [comment]
@juntaforce I want to clarify:
- <tag-input> identifyBy and displayBy regard the model
- <tag-input-dropdown> identifyBy and displayBy regard the items displayed in the autocomplete

Which means, they probably are not the same, or they can be. In your code, I noticed that you add $key after an item has been added. Which means, key is undefined when they are passed into tag-input-dropdown. And it should not be undefined: if yu define it, then it's gotta be defined. I believe you could fix your issue if you just pass 'name' in both the properties. You won't be able to add dupes, in the latter case.

**Comment by juntaforce** [comment]
Yes I solved.

But Im still curious about that there is no issue before upgrading 1.2.5 or Angular 4

Anyway thanks for your help.

**Comment by MmtBkn** [comment]
@juntaforce do you have blog post, or complete example that explains how to use this component with firebase?
