### ISSUE TITLE
Prod build fails in Angular CLI because of component ng2-tag-input

### ISSUE THREAD

**Issue by jstoppa** [Gbuomprisco/ng2-tag-input#387]
**I'm submitting a ...**  (check one with "x")
```
[X ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

When building my app with Angular CLI (ng build --prod), the build fails because of errors in the package ng2-tag-input
The error I get is the following

ERROR in ng:///C:/XXX/XXX/node_modules/ng2-tag-input/dist/modules/components/tag/tag.template.html (3,6): Supplied pa
rameters do not match any signature of call target.

ERROR in ng:///C:/XXX/XXX/node_modules/ng2-tag-input/dist/modules/components/tag-input.template.html (11,6): Supplied
 parameters do not match any signature of call target.
ng:///C:/XXX/XXX/node_modules/ng2-tag-input/dist/modules/components/tag-input.template.html (54,13): Supplied paramet
ers do not match any signature of call target.

ERROR in ng:///C:/XXX/XXX/node_modules/ng2-tag-input/dist/modules/components/tag-input.template.html (11,6): Supplied
 parameters do not match any signature of call target.
ng:///C:/XXX/XXX/node_modules/ng2-tag-input/dist/modules/components/tag-input.template.html (54,13): Supplied paramet
ers do not match any signature of call target.

ERROR in ng:///C:/XXX/XXX/node_modules/ng2-tag-input/dist/modules/components/tag/tag.template.html (3,6): Supplied pa
rameters do not match any signature of call target.

**Expected behavior**

Expect my app to build in Prod mode

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

   _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
@angular/cli: 1.0.0
node: 6.9.1
os: win32 x64
@angular/animations: 4.0.2
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

**Angular version:** 

@angular/core: 4.0.1

**ng2-tag-input version:**

"ng2-tag-input": "^1.2.5"

**Comment by webcat12345** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/issues/345#issuecomment-298648044
This issue is reported here.

**Comment by jstoppa** [comment]
thanks @webcat12345

**Comment by chanm003** [comment]
Receiving same issue as @jstoppa  

"dependencies": {
    "@angular/common": "4.0.3",
    "@angular/compiler": "4.0.3",
    "@angular/core": "4.0.3",
    "@angular/forms": "4.0.3",
    "@angular/http": "4.0.3",
    "@angular/platform-browser": "4.0.3",
    "@angular/platform-browser-dynamic": "4.0.3",
    "@angular/router": "4.0.3",
    "@angular/upgrade": "4.0.3",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.25",
    "chart.js": "2.5.0",
    "core-js": "2.4.1",
    "es6-promise": "^4.1.0",
    "moment": "2.18.1",
    "ng2-charts": "1.5.0",
    "ngx-bootstrap": "1.6.6",
    "rxjs": "5.3.0",
    "sp-pnp-js": "^2.0.4",
    "ts-helpers": "1.1.2",
    "whatwg-fetch": "^2.0.3",
    "zone.js": "^0.8.7"
  },
  "devDependencies": {
    "@angular/cli": "1.0.0",
    "@angular/compiler-cli": "4.0.3",
    "@types/jasmine": "2.5.47",
    "@types/node": "7.0.13",
    "codelyzer": "2.1.1",
    "gulp": "^3.9.1",
    "gulp-rename": "^1.2.2",
    "gulp-string-replace": "^0.4.0",
    "jasmine-core": "2.5.2",
    "jasmine-spec-reporter": "3.2.0",
    "karma": "1.6.0",
    "karma-chrome-launcher": "2.0.0",
    "karma-cli": "1.0.1",
    "karma-coverage-istanbul-reporter": "1.2.0",
    "karma-jasmine": "1.1.0",
    "karma-jasmine-html-reporter": "0.2.2",
    "protractor": "5.1.1",
    "sp-rest-proxy": "^1.2.1",
    "ts-node": "3.0.2",
    "tslint": "4.5.1",
    "typescript": "2.2.2"
  }

**Comment by Gbuomprisco** [comment]
there's a PR - will merge in the weekend

**Comment by chanm003** [comment]
thanks @Gbuomprisco - My temporary fix was to downgrade to 1.0.5 and it builds fine with CLI.

**Comment by Gbuomprisco** [comment]
This should be fine now

**Comment by jstoppa** [comment]
thanks Giancarlo!
