### ISSUE TITLE
Tag input not displaying correctly on Angular 4

### ISSUE THREAD

**Issue by rezonator** [Gbuomprisco/ng2-tag-input#388]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

After adding the module and tag - it displays as a regular input box, with empty buttons instead of tags, like below : 
http://imgur.com/Am311NB

```
import {Component, OnInit, Inject} from "@angular/core";
import {Task,Engagement, TaskStatus, TSToken, ITaskService} from "../../model";
import {MessageService} from "../../shared/message.service";
import {TaskService} from "../../tasks/task.service";
import {ActivatedRoute} from "@angular/router";

@Component({
    selector : "engagement" ,
    templateUrl : "./app/engagements/engagement-details/engagement-details.component.html",
    providers : [TaskService, MessageService],
})
export class EngagementDetailsComponent implements OnInit {
  itemsAsObjects = [{value: 0, display: 'Angular'}, {value: 1, display: 'React'}]; 
...
```
and
```
<div class="row">
     <div  class="well hoverwell thumbnail">
      <h2>{{engagement?.name}}</h2>
      <div>Date: {{engagement?.created}}</div>
     <div>Description: {{engagement?.description}}</div>
      <tag-input [ngModel]="itemsAsObjects"></tag-input>
    </div>
</div>
```

At the same time - I can't see any errors in the console, but JS seems to be broken elsewhere.

**Expected behavior**

Expected to be a working tag input component.

**Minimal reproduction of the problem with instructions (if applicable)**

1. using Angular 4
2. added the tag module to the main app module 
3. added the tag to the component

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

Windows

**Angular version:** 

Using Angular 4 atm.

**ng2-tag-input version:**

Latest from master, pulled today

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Both on Chrome and Edge (haven't tested on FF)

**Comment by Gbuomprisco** [comment]
Have you added BrowserAnimationModule?

**Comment by rezonator** [comment]
awesome, works now ! I had to do a bit of head scratching due to using BrowserModule already elsewhere, but that's what I was missing :) thanks!
