### ISSUE TITLE
Performance Improvement in IE11?

### ISSUE THREAD

**Issue by chrisbmoore** [Gbuomprisco/ng2-tag-input#389]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[X] support request/question
```

**Current behavior**

This may vary, but when I have over 200 tags, the page starts to lag on scroll (around 100ms). For 400+ tags, it is significantly noticeable (220ms to 350ms scroll and creating/deleting tag events).

**Expected behavior**

If this is possible, to be able to scroll the page and add/remove tags without significant slowdown (<100ms) for at least 400 items.

**Minimal reproduction of the problem with instructions (if applicable)**

Add over 400+ tags and view noticeable (~250ms) delay on scroll or tag add/remove.

**What is the motivation / use case for changing the behavior? (if applicable)**

Better user experience.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

SystemJS 0.19.41

**Angular version:** 

Angular 4.1.0

**ng2-tag-input version:**

1.2.0. Using this version as other errors happen with newer versions during build/runtime. Possibly due to any recent module changes. That is for another issue.

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

IE 11.0.96

**Comment by Gbuomprisco** [comment]
Hi @chrisbmoore,

I'd never tried with so many tags. Do you also experience the same lag on other browsers?

**Comment by chrisbmoore** [comment]
This seems to be an issue with IE11's performance, as there is no lag when using the latest version of Chrome.

**Comment by Gbuomprisco** [comment]
I have trouble supporting Edge and IE as I don't have a Windows machine, therefore I really can't give you a timeline on these fixes. I'd really appreciate PRs for these browsers

**Comment by chrisbmoore** [comment]
It's not priority since it works in Chrome just fine. If I have time, I'll see what I can do for this issue and my other one, #390.

**Comment by chrisbmoore** [comment]
I've tried some performance settings for my project, and when using the production build setting in mgechev's angular seed, it seems to have no performance lag in IE11 (possibly due to enableProdMode() reducing change detection calls). 

You can close this issue if you want, as performance is good for me now.

**Comment by Gbuomprisco** [comment]
perfect, thanks @chrisbmoore
