### ISSUE TITLE
Getting error: TS2304: Build:Cannot find name 'require'.Cannot find name 'exports'.

### ISSUE THREAD

**Issue by Glebby** [Gbuomprisco/ng2-tag-input#39]
The project won't compile:

1>C:\Project\node_modules\ng2-tag-input\index.ts(1,18): error TS2304: Build:Cannot find name 'require'.
2>C:\Projects\node_modules\ng2-tag-input\index.ts(3,1): error TS2304: Build:Cannot find name 'exports'.

I am using RC5. See my  package.json

============

{
  "version": "1.0.0",
  "name": "project",
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "@angular/upgrade": "2.0.0-rc.5",
    "core-js": "^2.4.0",
    "ng2-tag-input": "^0.2.3",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "systemjs": "0.19.27",
    "zone.js": "^0.6.12"
  },
  "devDependencies": {
    "gulp-clean": "^0.3.2",
    "gulp-concat": "2.6.0",
    "gulp-cssmin": "0.1.7",
    "gulp-notify-growl": "^1.0.2",
    "gulp-sass": "^2.3.2",
    "gulp-sourcemaps": "^1.6.0",
    "gulp-tsc": "^1.2.0",
    "gulp-typescript": "^2.13.6",
    "gulp-uglify": "2.0.0",
    "gulp-watch": "^4.3.9",
    "path": "^0.12.7",
    "rimraf": "2.5.3",
    "typescript": "^1.8.10",
    "typings": "^1.3.1"
  }
}

**Comment by Gbuomprisco** [comment]
Hi @Glebby!

The files are already compiled in the /dist folder. It's strange the compiler is compiling index.ts. is your tsconfig.json excluding the node_modules folder?

If that doesn't help, I'll try setting up a system.js configuration (as I have never used it with this, only Webpack) and paste here a working configuration. :)

**Comment by Glebby** [comment]
Hi, yes, node_modules are excluded

{
	"compilerOptions": {
		"emitDecoratorMetadata": true,
		"experimentalDecorators": true,
		"module": "commonjs",
		"noEmitOnError": true,
		"noImplicitAny": false,
		"outDir": "../wwwroot/admin/appScripts/",
		"removeComments": false,
		"inlineSourceMap": true,
		"target": "es5",
		"moduleResolution": "node"
	},
	"exclude": [
		"node_modules",
		"typings",
		"typings/globals",
		"typings/index",
		"typings/index.d.ts"
	]
}


I tried different options but ended up with removing index.ts and tweaking defaults in systemjs.config.js

/**
 * System configuration for Angular 2 samples
 * Adjust as necessary for your application needs.
 */
(function (global) {
	// map tells the System loader where to look for things
	var map = {
		'app': "appScripts", // 'dist',
		'@angular': "../lib/@angular",
		'ng2-tag-input': "../lib/ng2-tag-input",
		'rxjs': "../lib/rxjs"
	};
	// packages tells the System loader how to load when no filename and/or no extension
	var packages = {
		'app': { main: "main.js", defaultExtension: "js" },
		'ng2-tag-input': { main: "index.js", defaultExtension: "js" },
		'rxjs': { defaultExtension: "js" },
	};
	var ngPackageNames = [
      "common",
      "compiler", 
      "core",
      "forms",
      "http",
      "platform-browser",
      "platform-browser-dynamic",
      "router",
      "router-deprecated",
      "upgrade",
	  "ng2-tag-input"
	];

This way the control is rendered correctly.
However, when I start typing, I get error:

platform-browser.umd.js:937 TypeError: Cannot read property 'state' of undefined
    at Ng2DropdownMenu.handleKeypress (ng2-dropdown-menu.ts:106)
    at eval (platform-browser.umd.js:1836)
    at eval (platform-browser.umd.js:1913)
    at ZoneDelegate.invoke (zone.js:332)
    at Object.onInvoke (core.umd.js:9245)
    at ZoneDelegate.invoke (zone.js:331)
    at Zone.runGuarded (zone.js:239)
    at NgZoneImpl.runInnerGuarded (core.umd.js:9278)
    at NgZone.runGuarded (core.umd.js:9510)
    at HTMLBodyElement.outsideHandler (platform-browser.umd.js:1913)BrowserDomAdapter.logError @ platform-browser.umd.js:937
zone.js:269 Uncaught TypeError: Cannot read property 'state' of undefined

My tag is below:

			<tag-input name="userRoles" [ngModel]="user.roles"
						   [onlyFromAutocomplete]="true"
						   [autocompleteItems]="allRoles"
						   [autocomplete]="true"
				           placeholder="add a new team"
						   secondaryPlaceholder="Start typing to add a team"
				           (onAdd)="onTeamAdded($event)"
						   (onRemove)="onTeamRemoved($event)"
						   ></tag-input>

**Comment by Gbuomprisco** [comment]
Glad it compiles now! I published a new version (0.2.4) which fixes that issue. It was related to another package. Let me know 👍

**Comment by Glebby** [comment]
It is working now! thank you. However there is another issue now related to case sensitivity. I will post it as another issue to not mix things up.
