### ISSUE TITLE
addOnBlur creates focus issues.

### ISSUE THREAD

**Issue by kkotak** [Gbuomprisco/ng2-tag-input#394]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

When addOnBlur is set to true, the input control doesn't let go of focus. Pressing tab or clicking away from the control does add the typed content as the new tag, but the focus stays with the control and the user can't move it.

**Expected behavior**

Pressing tab or clicking away from the tag-input control, should move focus out to the next field int he form.

**Minimal reproduction of the problem with instructions (if applicable)**

Here's my tag attributes
          <tag-input [(ngModel)]="modelx"
                     [modelAsStrings]="true"
                     [autocompleteItems]="listx"
                     [placeholder]="' +' +placeholderx"
                     [secondaryPlaceholder]="placeholderx"
                     [editable]="true"
                     [addOnBlur]="true"
                     [autocomplete]="true"
                     id="idx"
                     name="namex"
          >
            <tag-input-dropdown [autocompleteItems]="listx"></tag-input-dropdown>
          </tag-input>

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

OSX, Webstorm, WebPack, Angular2 CLI

**Angular version:** 

4.0.1

**ng2-tag-input version:**

1.2.6

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome Version 57.0.2987.98 (64-bit)

**Comment by kurdyak** [comment]
Have the same issue

`<tag-input [(ngModel)]="model"
             [addOnBlur]="true"
             [separatorKeys]="[',', ' ']"
             [editable]="true"
             (onAdd)="onAdd($event)"
             (onRemove)="onRemove($event)"
  ></tag-input>`
**Angular version:**
4.0.1
**ng2-tag-input version:**
1.2.6

**Comment by Gbuomprisco** [comment]
Hi, will check it over the weekend

**Comment by hiren-bhalgama** [comment]
Having the same issue after upgrading version

`<tag-input [(ngModel)]="model" 
                    placeholder="+ Email Address" 
                    secondaryPlaceholder="Enter Email Address"  
                    name="contactEmails" 
                    formControlName="contactEmails" 
                   addOnBlur="true" 
                   [errorMessages]="errorMessages" 
                   [validators]="emailTagValidators"  
                   modelAsStrings="true">
</tag-input>`

**Angular version:** 
4.1.2
**ng2-tag-input version:**
1.2.6

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/399

**Comment by Gbuomprisco** [comment]
v1.2.7 released, let me if still an issue :)

**Comment by kkotak** [comment]
Confirming [addOnBlur]="true" is working with 1.2.8. Thanks!
