### ISSUE TITLE
Angular 2 compatibility?

### ISSUE THREAD

**Issue by sorenfalch** [Gbuomprisco/ng2-tag-input#395]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request/question
```

**Current behavior**

Get the errors:
TS2307: Cannot find module '@angular/platform-browser/animations'.
TS2305: Module [...]/node_modules/@angular/core/index"' has no exported member 'Renderer2'.
- Both seems to be related to ng2-tag-input expecting an NG4 environment and not NG2 that I'm running in (2.4.10).

**Expected behavior**

Error would not be shown...

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

You write (in README.md): "This is a component for Angular >= 2"
Would like to use ng2-tag-input with ng2 project.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

MacOS, Webpack in a dotnet-core environment. 

**Angular version:** 

2.4.10

**ng2-tag-input version:**

1.2.6

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome Version 58.0.3029.96 (64-bit)

**Comment by Gbuomprisco** [comment]
Downgrade to ng2-tag-input to v1.0.0

**Comment by sorenfalch** [comment]
Thanks 👍
