### ISSUE TITLE
Keyboard Keys

### ISSUE THREAD

**Issue by sspringer** [Gbuomprisco/ng2-tag-input#40]
What do these values correspond to?  Are they ASCII values?  Are they keyboard codes?  Are they platform specific? 

How would I go about making a comma a code to separate the tags?

Any help would be appreciated!  Thanks!

**Comment by Gbuomprisco** [comment]
Hi @sspringer! They correspond to keyboard keys. See https://css-tricks.com/snippets/javascript/javascript-keycodes/

**Comment by sspringer** [comment]
Thanks!  That's what I needed!

**Comment by Gbuomprisco** [comment]
Cool:)
