### ISSUE TITLE
Missing Licence

### ISSUE THREAD

**Issue by jakubstrama** [Gbuomprisco/ng2-tag-input#402]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request/question
```

**Current behavior**

No Licence is defined.

**Expected behavior**

A type o open-source licence should be defined. [NPM](https://www.npmjs.com/package/ng2-tag-input) states that this project's licence is MIT, but Github has no visible licence.

**Minimal reproduction of the problem with instructions (if applicable)**

N/A

**What is the motivation / use case for changing the behavior? (if applicable)**

ng2-tag-input may not be used in many projects because of a missing licence - [Licence Info](https://choosealicense.com/no-license/)

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

N/A

**Angular version:** 

N/A

**ng2-tag-input version:**

^1.2.8

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/403 :)

**Comment by jakubstrama** [comment]
brilliant, thanks!
