### ISSUE TITLE
Disable=true attribute does not remove disable attribute from input tag

### ISSUE THREAD

**Issue by jakubstrama** [Gbuomprisco/ng2-tag-input#404]
**I'm submitting a ...**  
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

`<tag-input [disabled]="!value" > ` sets `<input ... disabled="false">`

**Expected behavior**

Switch to `<tag-input [disabled]="false" >`  should remove _disabled_ attribute from an _input_ tag altogether. Chrome still interprets `disabled="false"` as disabled

**Minimal reproduction of the problem with instructions (if applicable)**

Launch in Chrome

**What is the motivation / use case for changing the behavior? (if applicable)**

To restore proper working of a component. 

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

Webpack

**Angular version:** 

4.0.1

**ng2-tag-input version:**

^1.2.8

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome 57.0.2987.133

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/413
