### ISSUE TITLE
Allow a mix of readonly and R/W tags.

### ISSUE THREAD

**Issue by kkotak** [Gbuomprisco/ng2-tag-input#405]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request/question
```

**Current behavior**

There is no way to initialize tag-input with read-only tags and allow adding new tags that are not readonly.

**Expected behavior**

Allow initializing the tag component with values that are read-only. All values added after initializing may be removed. 

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

The use-case is when you want to have a set of tags that are required in a model but additional tags may be added by the user. This could also be accomplished if you allow specifying a new object property 'readonly' in addition to 'name', 'value' in the model object array. This will allow developers to insert immutable values in the tag-input while still keeping the new values as r/w.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

Webpack

**Angular version:** 

4.0.1 CLI

**ng2-tag-input version:**

1.2.8

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome Latest.

**Comment by Gbuomprisco** [comment]
it makes sense @kkotak, I'll check this out

**Comment by Gbuomprisco** [comment]
This should be done :)

**Comment by kkotak** [comment]
Cool! Thanks @Gbuomprisco Will check it out today. Appreciate it.
