### ISSUE TITLE
Shorten long tags with ... and add a tool-tip that shows the full value

### ISSUE THREAD

**Issue by kkotak** [Gbuomprisco/ng2-tag-input#406]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request/question
```

**Current behavior**

Currently with limited width of tag-input, if the tag value is really long, it is truncated and the 'X' button that allows removing of the tag is not visible. This create two issues - 1. Not showing the full tag value 2. Crippling the functionality of removing long tags.

**Expected behavior**

1. Truncate long tag values with ... (optionally adding a tooltip that shows the full value)
2. Making sure the 'X' button is alway visible, even in care of long tags.

**Minimal reproduction of the problem with instructions (if applicable)**

Add a very long tag.

**What is the motivation / use case for changing the behavior? (if applicable)**

We currently have long tags (procedure names, etc.) that can not be shortened and require this functionality.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

Angulare-cli

**Angular version:** 

4.0.1

**ng2-tag-input version:**

1.2.8

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome Latest.

**Comment by Gbuomprisco** [comment]
Yeah it's an edge case I hadn't experienced

**Comment by kkotak** [comment]
Totally understandable. Something to keep in the list.

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/413
