### ISSUE TITLE
Debounce Autocomplete

### ISSUE THREAD

**Issue by chanm003** [Gbuomprisco/ng2-tag-input#407]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request/question
```

**Current behavior**
autocomplete using an Observable<Response> sends HTTP requests as soon as user types a single character.   

**Expected behavior**

Is there an easy way to debounce?  For example, only fire the network request after the user has stopped typing for 500ms. I see there is a `minimumTextLength` property.  If that works as I expect, I suppose I could only send the HTTP request after the user types at least X amount of characters.

**Comment by Gbuomprisco** [comment]
Hi @chanm003,

can you try `onTextChangeDebounce`? This should work, but I haven't tried it yet with autocompleteObservable. Let me know :)

**Comment by chanm003** [comment]
Hi @Gbuomprisco,

Worked like a charm with autCompleteObservable! I should have found that!

**Comment by Gbuomprisco** [comment]
Awesome :)
