### ISSUE TITLE
OnRemoving not trigger by backspace and drag remove

### ISSUE THREAD

**Issue by hsuanweifu** [Gbuomprisco/ng2-tag-input#408]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

OnRemoving is triggered by clicking x but not triggered by backspace and drag remove.

**Expected behavior**

OnRemoving is triggered by both x and backspace and drag remove.

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

angular-cli 1.0.0
PHP Storm

**Angular version:** 

angular 4.0.2

**ng2-tag-input version:**

1.2.8

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/413

**Comment by hsuanweifu** [comment]
There are still some issues with the update.

1. Backspace tag removal seems to be triggering onSelect instead of onRemoving.
2. dragZone does not work with this update. The onRemoving will be triggered when trying to drag the tags between fields.

**Comment by Gbuomprisco** [comment]
I guess it's because:
- the tag gets first selected, and then (once it is selected) the onRemoving will be triggered.
- yeah I think dragZone won't work with this as the item is removed right away when the dragging starts. I am not sure we can get the event of the item being dropped before removing it which would be ideal.
