### ISSUE TITLE
close tag (x) should not triggers onSelect

### ISSUE THREAD

**Issue by hsuanweifu** [Gbuomprisco/ng2-tag-input#409]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

When clicking x the onSelect is triggered.

**Expected behavior**

OnSelect should not be triggered when click on x or dragging.

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

I am using both onRemoving an onSelect together. The tags will display a confirm box when user wants to remove a tag. The tag can also be selected(clicked) to be redirect to the info page for the tag.

Currently when I click cancel on confirm box the onSelect will be triggered and take me to the tag info page.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

angular-cli 1.0.0
PHP Storm

**Angular version:** 

angular 4.0.2

**ng2-tag-input version:**

1.2.8

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/413

**Comment by hsuanweifu** [comment]
For temporary fix, add event.stopPropagation(); to onRemoving function;
