### ISSUE TITLE
ng build --prod Problem

### ISSUE THREAD

**Issue by manuelsanchezaponte** [Gbuomprisco/ng2-tag-input#412]
I have one project and I am using ng2-tag-input. Now, I want to build my project in production but...

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

ng build --prod

ERROR in ng:///home/lolo/RunningIsLife/Events/loginEvents/node_modules/ng2-tag-input/dist/modules/components/tag/tag.template.html (3,6): Supplied parameters do not match any signature of call target.

ERROR in ng:///home/lolo/RunningIsLife/Events/loginEvents/node_modules/ng2-tag-input/dist/modules/components/tag-input.template.html (11,6): Supplied parameters do not match any signature of call target.
ng:///home/lolo/RunningIsLife/Events/loginEvents/node_modules/ng2-tag-input/dist/modules/components/tag-input.template.html (54,13): Supplied parameters do not match any signature of call target.

**Expected behavior**

No problem at all.

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

I am using angular-cli

**Angular version:** 

Angular 4

**ng2-tag-input version:**

npm list ng2-tag-input
*********************************************
└── ng2-tag-input@1.2.5 

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Distributor ID:	LinuxMint
Description:	Linux Mint 18.1 Serena
Release:	18.1
Codename:	serena

**Comment by Gbuomprisco** [comment]
@manuelsanchezaponte complete ng2-tag-input version please

**Comment by manuelsanchezaponte** [comment]
Thank you.

npm -v ng2-tag-input   ->   4.6.1

Manuel.

**Comment by Gbuomprisco** [comment]
Hi @manuelsanchezaponte,

that must be npm's version, not ng2-tag-input's.

**Comment by manuelsanchezaponte** [comment]
You are rigth, sorry.

npm list ng2-tag-input
*********************************************
└── ng2-tag-input@1.2.5

**Comment by Gbuomprisco** [comment]
upgrade to 1.2.8 :) (always check you're running the latest version before opening a new issue)

**Comment by manuelsanchezaponte** [comment]
It worked!!

Thank you!.

Manuel.
