### ISSUE TITLE
Property 'readonly' does not exist on type 'TagInputComponent'

### ISSUE THREAD

**Issue by cport1** [Gbuomprisco/ng2-tag-input#414]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**
angular-cli ng build --aot --prod results in ::
node_modules/ng2-tag-input/dist/modules/components/tag-input.template.html (13,6): Property 'readonly' does not exist on type 'TagInputComponent'.

**Expected behavior**

successful build

**Minimal reproduction of the problem with instructions (if applicable)**
ng build --aot --prod

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

```
    "@angular/cli": "^1.0.1",
    "@angular/compiler-cli": "next",
    "@angular/animations": "next",
    "@angular/common": "next",
    "@angular/compiler": "next",
    "@angular/core": "next",
    "@angular/flex-layout": "^2.0.0-beta.8",
    "@angular/forms": "next",
    "@angular/http": "next",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "next",
    "@angular/platform-browser-dynamic": "next",
    "@angular/router": "next",
```

**Angular version:** 
angular 4.2.0-rc.0

**ng2-tag-input version:**

^1.2.9

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

build

**Comment by cport1** [comment]
#413 didn't seem to fix this

**Comment by Gbuomprisco** [comment]
Hi @cport1,

readonly has been removed. It's a breaking change (actually, I'm surprised it was used). To fix this, assign a readonly property to each tag object (or downgrade to 1.2.8). I'll update the readme soon.

**Comment by ljieyao** [comment]
How to solve this problem? I don't understand. @Gbuomprisco @cport1

**Comment by bfan1256** [comment]
I am having the same problem, I did not use the readonly property and it still cannot build.

**Comment by Gbuomprisco** [comment]
@bfan1256 can you paste here your stacktrace? 

To make readonly work, you'll need to assign a property called 'readonly' set to true to the model of the item that you are passing as ngmodel. If you are using strings, then use objects instead. Or, use a combination of [removable]=false and [hideForm]=true

**Comment by bfan1256** [comment]
I seem to have fixed it by going into the html of the node_modules and removing all instances of read_only.  I can reproduce the result real quick.

**Comment by bfan1256** [comment]
`ERROR in ng:///D:/kaylor-form/node_modules/ng2-tag-input/dist/modules/components/tag-input.template.html (13,6): Property 'readonly' does not exist on type 'TagInputComponent'.

ERROR in ng:///D:/kaylor-form/node_modules/ng2-tag-input/dist/modules/components/tag-input.template.html (13,6): Property 'readonly' does not exist on type 'TagInputComponent'.`

**Comment by ljieyao** [comment]
@Gbuomprisco what about with ReactiveForms as I have no ngModel?

**Comment by Gbuomprisco** [comment]
As far as I remember you must use an ngModel

**Comment by acuntex** [comment]
The bug is in "tag-input.template.html":
Since you removed the property readonly in TagInputComponent in commit b90801d94b809ee7ec64f522e48f3f44e1602db9 (May 24th 2017), AOT cannot bind to any "readonly" property thus breaking AOT-support

**Comment by tartexs** [comment]
@Gbuomprisco why do you removed the reandOnly option?

**Comment by Gbuomprisco** [comment]
@tartexs by giving each tag model a readonly property makes the component more powerful, as you can now set predefined readonly properties, for example. It's still there - you just use it in a different way

**Comment by ekevjn** [comment]
@Gbuomprisco i used to have 2 different page, one for edit and one for view only and this changed force me to find a way to workaround

**Comment by Gbuomprisco** [comment]
sorry to hear that, but breaking changes happen
