### ISSUE TITLE
Problem with separatorKeys and separatorKeyCodes

### ISSUE THREAD

**Issue by bfan1256** [Gbuomprisco/ng2-tag-input#416]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**
separatorKeyCodes or separatorKeys not working when manually adding keycodes/strings

**Expected behavior**
The new keycodes/strings would be registered and using the desired keys could separate between tags

**Minimal reproduction of the problem with instructions (if applicable)**
Trying any tag-input in code?

**What is the motivation / use case for changing the behavior? (if applicable)**
So the tag input can use more than one key to separate between tags

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
angular-cli
version: 1.0.2

**Angular version:** 
4.1.3

**ng2-tag-input version:**
1.2.9

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by Gbuomprisco** [comment]
Hi @bfan1256, I am not sure I understand the issue :\

**Comment by 1khdmurdolo** [comment]
I am having the same problem.

`<tag-input [(ngModel)]='tags' [transform]="makeHashtag" [maxItems]="10" [separatorKeys]="[32]" [theme]="'scoop'"
></tag-input>`

Spacebar does not trigger the creation of the tag even though [separatorKeys] exists.

**Angular version:**
4.1.0

**ng2-tag-input version:**
1.2.5

**Comment by Gbuomprisco** [comment]
@1khdmurdolo can you try using [separatorKeyCodes]?

**Comment by 1khdmurdolo** [comment]
@Gbuomprisco That did the job. Thanks.

**Comment by bfan1256** [comment]
So I was trying to implement 
`
<tag-input [(ngModel)]='listOfBenefits' placeholder="+Benefit" secondaryPlaceholder="Enter A Benefit" [editable]='true' [separatorKeyCodes]='[9, 188]' [addOnPaste]='true' [modelAsStrings]='true'></tag-input>
`
But it seems like there was a problem recognizing the separatorKeyCodes? I'm not sure why. I also seemed to have the problem that every time I added a new tag, the value I inputted would continue over and I would have to backspace to start a new tag. Do you know what may be the problem with this?

**Comment by Gbuomprisco** [comment]
@bfan1256 that usually refers to an issue with the ngModel. Can you paste here the controller's code?

**Comment by bfan1256** [comment]
Sure, I was trying to reference the `listOfBenefits` variable and pass each value into the array as your API states that I could. I just wanted the Strings so I used `[modelAsStrings]='true'`.  Here is the code for the `listOfBenefits` variable: `listOfBenefits: Array<string> = [];`

**Comment by Gbuomprisco** [comment]
Very odd. I'm trying to reproduce, so I've added to the example in the demo:

```html
{{ emptyList | json }}
<tag-input [(ngModel)]="emptyList"
                   placeholder="+Benefit"
                   secondaryPlaceholder="Enter A Benefit"
                   [editable]='true'
                   [separatorKeyCodes]='[9, 188]'
                   [addOnPaste]='true'
                   [modelAsStrings]="true">
</tag-input>
```

```javascript
// controller's class
emptyList: string[] = [];
```

![screen shot 2017-05-26 at 15 57 08](https://cloud.githubusercontent.com/assets/3512197/26497538/2ab66418-422c-11e7-89e9-e9a694c884d7.png)

Not sure what's wrong :|

**Comment by bfan1256** [comment]
Do the keycodes also work? I might try a reinstall?

**Comment by Gbuomprisco** [comment]
Yeah, I tried tabs and comma, working OK. Don't think a reinstall will do anything...just to be sure, can you try reference {{ listOfBenefits | json }} in your template and check the value? (should be '[]
').

**Comment by bfan1256** [comment]
Yeah sure will do.

**Comment by bfan1256** [comment]
It seems like it's still not working?

![capture](https://cloud.githubusercontent.com/assets/15917894/26497921/3b2a45d4-41fb-11e7-8912-34e82b130ecf.PNG)

**Comment by bfan1256** [comment]
Okay, the code is working, there is some problem with some of my other code that is hindering this from working. Very interesting?

**Comment by Gbuomprisco** [comment]
I suppose you need to add `name="something"` to `tag-input` is you're trying to use it inside a form

**Comment by bfan1256** [comment]
Wow that did the trick! Thank you so much @Gbuomprisco ! Thanks for being so quick to respond and helpful!

**Comment by Gbuomprisco** [comment]
Great!:)

**Comment by kavithamahe** [comment]
@Gbuomprisco i need the tags with spaces allowed,can u please help me for comeout this issue
