### ISSUE TITLE
Error when building in AOT mode (Error encountered resolving symbol values statically - TagInputComponent)

### ISSUE THREAD

**Issue by jstoppa** [Gbuomprisco/ng2-tag-input#419]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

Getting the following error when doing ng build --aot

ERROR in Error encountered resolving symbol values statically. Could not resolve components relative to C:/XXX/XXX/nod
e_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.d.ts., resolving symbol TagInputComponent in C:/XXX/XXX/node_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.d.ts, resolving symbol TagInputComponent in C:/XXX/XXX/node_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.d.ts

**Expected behavior**

Be able to do ng build in aot mode

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

Angular CLI

**Angular version:** 

@angular/cli: 1.0.0
node: 6.9.1
os: win32 x64
@angular/animations: 4.0.2
@angular/common: 4.0.1
@angular/compiler: 4.0.1
@angular/core: 4.0.1
@angular/forms: 4.0.1
@angular/http: 4.0.1
@angular/material: 2.0.0-beta.3
@angular/platform-browser: 4.0.1
@angular/platform-browser-dynamic: 4.0.1
@angular/router: 4.0.1
@angular/cli: 1.0.0
@angular/compiler-cli: 4.0.1

**ng2-tag-input version:**

1.3.0

**Comment by Gbuomprisco** [comment]
Hi @jstoppa,

thanks for reporting, I suggest to use v1.2.9 for now

**Comment by reco** [comment]
similar issue here. going back to 1.2.9 works.



```
ERROR in /xx/node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.d.ts (3,26): Cannot find module 'core'.

ERROR in /xx/node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.d.ts (4,35): Cannot find module 'components'.

ERROR in /xx/node_modules/ng2-tag-input/dist/modules/components/tag/tag.component.d.ts (2,26): Cannot find module 'core'.

ERROR in /xx/node_modules/ng2-tag-input/dist/modules/components/tag/tag.component.d.ts (3,27): Cannot find module 'tag'.

ERROR in /xx/node_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.d.ts (8,44): Cannot find module 'core'.

ERROR in /xx/node_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.d.ts (9,62): Cannot find module 'components'.
```


**versions**

@angular/cli: 1.0.6
node: 7.10.0
os: darwin x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/compiler-cli: 4.1.3
@angular/core: 4.1.3
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/material: 2.0.0-beta.6
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/platform-server: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.6

ng2-tag-input version: 1.3.0

**Comment by thereiskeks** [comment]
Version 1.2.9 works for me.

```
    "@angular/animations": "4.1.3",
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@angular/router": "4.1.3",
    "@angular/upgrade": "4.1.3",
    "@types/core-js": "^0.9.41",
    "ng-select": "^1.0.0-beta.5",
    "ts-helpers": "1.1.2",
    "typescript-collections": "^1.2.3",
    "zone.js": "0.8.11"
    "@angular/cli": "1.0.6",
    "@angular/compiler-cli": "4.1.3",
    "typescript": “2.3.4”,
    "ng2-tag-input": "1.2.9",
```

Don’t use "ng2-tag-input": “^1.2.9” since it will resolve version 1.3.0.

**Comment by osahner** [comment]
same with `@angular/cli: 1.1.0 `
```
ERROR in /Users/osahner/Developer/js/app-innovation-be/node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.d.ts (3,26): Cannot find module 'core'.

ERROR in /Users/osahner/Developer/js/app-innovation-be/node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.d.ts (4,35): Cannot find module 'components'.

ERROR in /Users/osahner/Developer/js/app-innovation-be/node_modules/ng2-tag-input/dist/modules/components/tag/tag.component.d.ts (2,26): Cannot find module 'core'.

ERROR in /Users/osahner/Developer/js/app-innovation-be/node_modules/ng2-tag-input/dist/modules/components/tag/tag.component.d.ts (3,27): Cannot find module 'tag'.

ERROR in /Users/osahner/Developer/js/app-innovation-be/node_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.d.ts (8,44): Cannot find module 'core'.

ERROR in /Users/osahner/Developer/js/app-innovation-be/node_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.d.ts (9,62): Cannot find module 'components'.

```

**Comment by Gbuomprisco** [comment]
Will be fixing this in the weekend :)

**Comment by acuntex** [comment]
Same in version 1.3.1.
When running with "ng serve" there is the error by @osahner and @reco 
When running with "ng build --aot" there is the error by @jstoppa

**Comment by KeitaElric** [comment]
+1

**Comment by Gbuomprisco** [comment]
Hi all, this should have been fixed by @eyalhakim. I would have loved to keep the named paths intact, but apparently the CLI won't work with them just yet. Please reopen this ticket if you still have issues.:)

**Comment by jstoppa** [comment]
thanks @Gbuomprisco ! this build (1.3.3) fixes the issue
