### ISSUE TITLE
Global default settings

### ISSUE THREAD

**Issue by altschuler** [Gbuomprisco/ng2-tag-input#420]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[X] feature request
[ ] support request/question
```

**Current behavior**
There is no way to set global defaults, you have to configure each component individually

**What is the motivation / use case for changing the behavior? (if applicable)**
I'm using this in a lot of different places and when I want to tweak something I have to go through all instances of the component and set settings individually.

It would be helpful to somehow specify global defaults, eg. when import the module, like:

```
TagInputModule.withDefaults({ maxItems: 2, ... })
```

**Angular version:** 
4.1.3

**ng2-tag-input version:**
1.3.0

**Comment by Gbuomprisco** [comment]
Sounds sensible :)

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/464/files

**Comment by altschuler** [comment]
Wonderful! Thank you very much!
