### ISSUE TITLE
Cannot find module 'Core', 'Components', 'tag'.

### ISSUE THREAD

**Issue by SaikrishnaViridis** [Gbuomprisco/ng2-tag-input#424]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

Unable to compile the code.

**Expected behavior**

Need to use of the module as in the examples.

**Minimal reproduction of the problem with instructions (if applicable)**

1. Added the module and added "Basic example" code to test the module.
2. While compiling the code the below issue is coming up.
ERROR in xyz/node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.d.ts (3,26): Cannot find module 'core'.

ERROR in xyz/node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.d.ts (4,35): Cannot find module 'components'.

ERROR in xyz/node_modules/ng2-tag-input/dist/modules/components/tag/tag.component.d.ts (2,26): Cannot find module 'core'.

ERROR in xyz/node_modules/ng2-tag-input/dist/modules/components/tag/tag.component.d.ts (3,27): Cannot find module 'tag'.

ERROR in xyz/node_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.d.ts (8,44): Cannot find module 'core'.

ERROR in xyz/node_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.d.ts (9,62): Cannot find module 'components'.
webpack: Failed to compile.

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

Webpack

**Angular version:** 

"@angular/core": "^4.0.0"

**ng2-tag-input version:**

"ng2-tag-input": "^1.3.1"

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

All browsers.

**Comment by acuntex** [comment]
Already filed here: https://github.com/Gbuomprisco/ng2-tag-input/issues/419

**Comment by cport1** [comment]
Can we get #419  merged and version bumped please?

**Comment by Gbuomprisco** [comment]
i'll try get this fixed in the weekend guys

**Comment by aiqingyuyan** [comment]
Got the same error, also using angular*: ^4.0.0, ng2-tag-input: "^1.3.2"

**Comment by smartHasmukh** [comment]
Got the same error, also using angular/*: ^4.0.0, ng2-tag-input: "^1.3.2"

![erro](https://cloud.githubusercontent.com/assets/8941195/26751769/19803ad2-485f-11e7-8330-3e395456d2ba.png)

`{
  "name": "scroll-down",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "angular2-useful-swiper": "^4.0.5",
    "core-js": "^2.4.1",
    "ng2-fullpage": "^2.1.0",
    "ng2-owl-carousel": "^0.1.15",
    "ng2-tag-input": "^1.2.9",
    "primeng": "^4.0.3",
    "rxjs": "^5.1.0",
    "zone.js": "^0.8.4"
  },
  "devDependencies": {
    "@angular/cli": "1.0.2",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.38",
    "@types/jquery": "^2.0.45",
    "@types/node": "~6.0.60",
    "codelyzer": "~2.0.0",
    "jasmine-core": "~2.5.2",
    "jasmine-spec-reporter": "~3.2.0",
    "karma": "~1.4.1",
    "karma-chrome-launcher": "~2.0.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^0.2.0",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.0",
    "ts-node": "~2.0.0",
    "tslint": "~4.5.0",
    "typescript": "~2.2.0"
  }
}
`

**Comment by teban1812** [comment]
Same error here. 

```
ERROR in C:/dev/coro-joven/webapp/webapp/node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.d.ts (3,26): Canno
t find module 'core'.

ERROR in C:/dev/coro-joven/webapp/webapp/node_modules/ng2-tag-input/dist/modules/components/dropdown/tag-input-dropdown.component.d.ts (4,35): Canno
t find module 'components'.

ERROR in C:/dev/coro-joven/webapp/webapp/node_modules/ng2-tag-input/dist/modules/components/tag/tag.component.d.ts (2,26): Cannot find module 'core'
.

ERROR in C:/dev/coro-joven/webapp/webapp/node_modules/ng2-tag-input/dist/modules/components/tag/tag.component.d.ts (3,27): Cannot find module 'tag'.

ERROR in C:/dev/coro-joven/webapp/webapp/node_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.d.ts (8,44): Cannot find module 'cor
e'.

ERROR in C:/dev/coro-joven/webapp/webapp/node_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.d.ts (9,62): Cannot find module 'com
ponents'.
```
@angular/cli: 1.1.0
node: 6.10.3
os: win32 x64
@angular/animations: 4.1.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/upgrade: 4.1.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3

npm -v
5.0.2

**Comment by nirelbaz** [comment]
Same here and can't use 1.2.9 - I get the "readonly" error. any other workaround?

**Comment by Gbuomprisco** [comment]
Try 1.2.8

**Comment by Gbuomprisco** [comment]
Hi all, this should have been fixed by @eyalhakim. I would have loved to keep the named paths intact, but apparently the CLI won't work with them just yet. Please reopen this ticket if you still have issues.:)
