### ISSUE TITLE
Allow to pass/get items via Input

### ISSUE THREAD

**Issue by artaommahe** [Gbuomprisco/ng2-tag-input#428]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ x ] feature request
[ ] support request/question
```

**Current behavior**
We can pass/get items only via form directives like `ngModel` or `formControlName`

**Expected behavior**
Ability to pass items and receive results via component input without forms directive, like
```html
<tag-input [(items)]='items'></tag-input>
```

**What is the motivation / use case for changing the behavior? (if applicable)**
More flexible usage without additional things.

**Comment by Gbuomprisco** [comment]
Hi @artaommahe,

sorry but I am not planning on adding additional properties/features at this time
