### ISSUE TITLE
Cannot find name 'TagModel'

### ISSUE THREAD

**Issue by menshinobi** [Gbuomprisco/ng2-tag-input#429]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**
I run npm install --save ng2-tag-input. Then, I added necessary code into my app.module.ts. However, upon running ionic serve, the console reports the following

```
[00:35:43]  typescript: node_modules/ng2-tag-input/dist/modules/components/tag/tag.component.d.ts, line: 34 
            Cannot find name 'TagModel'. 

      L33:  onBlurred(event: any): void;
      L34:  getDisplayValue(item: TagModel): string;
      L35:  isRippleVisible(): boolean;
```
Here is my app.module.ts

```
import {TagInputModule} from 'ng2-tag-input';
import {BrowserAnimationsModule} from '@angular/platform-browser/animations';
@NgModule({
    declarations   : [
        MyApp,
    ],
    imports        : [
        CommonModule,
        BrowserModule,
        HttpModule,
        PagesModule,
        TagInputModule,
        BrowserAnimationsModule,
        IonicModule.forRoot(MyApp, {}, {
            // DeepLinker
            // http://blog.ionic.io/deeplinking-in-ionic-apps/
            links: [
                {component: ProfilePage, name: 'Profile', segment: 'profile/:username'},
                {component: PhotoCardComponent, name: 'Photo', segment: 'photo/:id'},
                {component: ChatMessagePage, name: 'Chat', segment: 'chat/:id'},
                {component: TermsPage, name: 'Terms', segment: 'terms'},
            ]
        })
    ],
```
**Expected behavior**

The ng2-tag-input should be executed successfully

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

ionic-app-scripts 1.3.1

**Angular version:** 

Angular 4.1.1

**ng2-tag-input version:**

1.3.1
**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by Gbuomprisco** [comment]
Hi @menshinobi, can you try 1.3.3?

**Comment by menshinobi** [comment]
@Gbuomprisco Thanks. Version 1.3.3 seems to fix the issue. However, I met a new one

```
polyfills.js:3 Unhandled Promise rejection: Template parse errors:
'tag-input' is not a known element:
1. If 'tag-input' is an Angular component, then verify that it is part of this module.
2. If 'tag-input' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
                </ion-select>
            </ion-item>
            [ERROR ->]<tag-input [(ngModel)]="items"></tag-input>
            <!-- Album -->
```

My app.component.ts is the same. Not sure what I did wrong here. Can you help me with this?

Thanks!

**Comment by Gbuomprisco** [comment]
Try importing TagInputModule in the module you're using the component in. If they're lazy routes, then need TagInputModule imported too.
