### ISSUE TITLE
The autocomplete is not working with uppercase

### ISSUE THREAD

**Issue by Glebby** [Gbuomprisco/ng2-tag-input#43]
My autocomplete array is ["Item1", "item2", "item3"]
When I type either "i" or "I" the popup  always displays only item2 and item3.

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/44

**Comment by Gbuomprisco** [comment]
Hi @Glebby , version 0.2.5 should fix it :)

**Comment by kkotak** [comment]
Hi - I believe this bug might be back, as I am seeing the same behavior with 0.8.0.

**Comment by Gbuomprisco** [comment]
Hi @kkotak,

that's pretty outdated. Try the newest version

**Comment by kkotak** [comment]
Thanks @Gbuomprisco  I did update and the issue is indeed resolved. Appreciate the quick response. Best, _K
