### ISSUE TITLE
build AOT error

### ISSUE THREAD

**Issue by phamtienmanh** [Gbuomprisco/ng2-tag-input#432]
Import TagInputModule into my project leads build error, but in run it works well.
Error: Child compilation failed:
Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example

**Comment by Gbuomprisco** [comment]
Hi @phamtienmanh, please fill out the template
