### ISSUE TITLE
ngModel is not updated automatically whenever I am adding or removing a tag. Do I need to update my item array manually?

### ISSUE THREAD

**Issue by Souvik93** [Gbuomprisco/ng2-tag-input#440]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ "x"] support request/question
```

**Current behavior**

ngModel (ex- items[]) is not updated. Do I need to update the items by calling onAdd? 

**Expected behavior**

It should be updated as we are using ngModel.

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
 Angular-CLI (1.0.3),Windows 10 , package manager- NPM 

**Angular version:** 
 Angular 4.0.0 

**ng2-tag-input version:**
1.3.3 

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
@Souvik93 can you add some code?

**Comment by Souvik93** [comment]
<tag-input [ngModel]="items" (onAdd)="addTag($event)"  [theme]="'bootstrap3-info'" >
        </tag-input>

**Comment by Souvik93** [comment]
yes. my html file-
<tag-input [ngModel]="items" (onAdd)="addTag(items)"  [theme]="'bootstrap3-info'" >
 </tag-input>

In .ts file-
items = ['Javascript', 'Typescript'];
addTag(ev){
   alert("Hello, There"+ev)
   console.log(ev);
 }

It always prints 'Javascript', 'Typescript' in console. Do I need to push newly added value(ex-Java) manually in 'items' array? It is showing three value in <tag-input> . But new values are not reflected in items array.

**Comment by Gbuomprisco** [comment]
No, you need to use 2-way data binding with you model, so add () to the ngModel
