### ISSUE TITLE
Does not compile - ng2-tag-input/index.ts is not under 'rootDir'

### ISSUE THREAD

**Issue by jnfsmile** [Gbuomprisco/ng2-tag-input#441]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**
When trying to compile
```
 error TS6059: File 'D:/Github/Galit-Beshvili/node_modules/ng2-tag-input/index.ts' is not under 'rootDir' 'D:/Github/Galit-Beshvili/client/app'. 'rootDir' is expected to contain all source files.

 error TS6059: File 'D:/Github/Galit-Beshvili/node_modules/ng2-tag-input/node_modules/ng2-material-dropdown/index.ts' is not under 'rootDir' 'D:/Github/Galit-Beshvili/client/app'. 'rootDir' is expected to contain all source files.

```
**Expected behavior**
compile successful

**Minimal reproduction of the problem with instructions (if applicable)**
I installed and followed **SystemJS** instructions.

**What is the motivation / use case for changing the behavior? (if applicable)**
Using the package

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
systemJS@0.19.40

**Angular version:** 
2.4

**ng2-tag-input version:**
1.3.3

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
all

**Comment by Gbuomprisco** [comment]
This component is not compatible with your version

**Comment by jnfsmile** [comment]
Version of what?

**Comment by Gbuomprisco** [comment]
Angular? Upgrade to 4+ or use v1.0.0 of this component
