### ISSUE TITLE
Populate items using an Observable TypeError: data.map is not a function

### ISSUE THREAD

**Issue by Floyd1256** [Gbuomprisco/ng2-tag-input#442]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request/question
```

**Current behavior**
 I am currently trying to populate items for autocomplete using an Observable, and trying to achieve that using something simple such as github search. I am always getting data.map is not a function as soon as I type a letter, knowing that github is returning results that i can view in the console 

**Expected behavior**
Can you please provide a basic example on that? I think the problem is in parsing the returned JSON, but I can not seem to fix that, would be great if I can get a little help.

**Minimal reproduction of the problem with instructions (if applicable)**
public requestAutocompleteItems = (text: string): Observable<Response> => {

let url = 'https://api.github.com/search/repositories?q=${text}';
return this.http.get(url).map(data=>data.json());

};

    <tag-input [ngModel]="['@item']">
        <tag-input-dropdown [autocompleteObservable]='requestAutocompleteItems'></tag-input-dropdown>
    </tag-input>

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
angular-cli

**Angular version:** 
4.0

**ng2-tag-input version:**
1.3.3

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Have you imported the map operator in your own component?

**Comment by Floyd1256** [comment]
Not really, can you provide a basic example on how to do that? Sorry but I am new to angular

**Comment by Gbuomprisco** [comment]
No worries.
Just add `import 'rxjs/add/operator/map` before creating the component, it should solve it

**Comment by Floyd1256** [comment]
you mean just add import 'rxjs/add/operator/map' along with other imports? Or is there an additional step I should do? I just put the code that I provided above, should I add anything else to it? I am using ionic btw. Thanks again for your time

**Comment by Floyd1256** [comment]
I was able to make it work, the issue was I did not provide valid [identifyBy] and  [displayBy] tags. Thanks a lot!

**Comment by bhardwajsuresh** [comment]
I still face this issue with Angular 14
