### ISSUE TITLE
Ability to add text along with tags

### ISSUE THREAD

**Issue by Floyd1256** [Gbuomprisco/ng2-tag-input#443]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[x] feature request
[ ] support request/question
```

**Current behavior**
Currently, control is given only on the tags and how they can be created or selected from autocomplete list for example.

**Expected behavior**
A good feature would be to have the ability to add normal text in addition to tags, such as twitter or github tag functionality, where normal text can be written, then on @ or other special character notation, there could be use of the tag functionality as it is implemented now

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
angular-cli

**Angular version:** 
4.0

**ng2-tag-input version:**
1.3.3

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by Gbuomprisco** [comment]
Hi @Floyd1256, I understand the use-case but this might out of the scope of this component. Certainly such a functionality would be easy to achieve using ng2-material-dropdown, but I don't think it belongs to this component (which is already pretty fat in terms of options and functionality)
