### ISSUE TITLE
Backwards Compatibility

### ISSUE THREAD

**Issue by kunal3** [Gbuomprisco/ng2-tag-input#444]
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[x] support request/question
```

**Current behavior**

Using Angular2, would like to use some of the bug fixes introduced past v1.0.0 of tag-input

**Expected behavior**

Backwards compatibility of at least v1.0.5 for Angular2

**What is the motivation / use case for changing the behavior? (if applicable)**

(addOnBlur) does't work as expected on v1.0.0. Doesn't do anything at all on on blur, I am assuming because of https://github.com/Gbuomprisco/ng2-tag-input/issues/309

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

Webpack

**Angular version:** 

Angular 2.4

**ng2-tag-input version:**

1.0.0, would like to use at least 1.0.5

**Comment by Gbuomprisco** [comment]
Might be better if you forked and cherry picked the commits you need. I don't honestly have enough time to support old versions. Hope you understand.
