### ISSUE TITLE
Installation error with Angular2

### ISSUE THREAD

**Issue by raghles** [Gbuomprisco/ng2-tag-input#445]
I have Angular2 project. I am trying to install ng2-tag-input on it. But I am getting the following error.
npm WARN ng2-tag-input@1.3.3 requires a peer of @angular/common@^4.0.0 but none was installed.
npm WARN ng2-tag-input@1.3.3 requires a peer of @angular/core@^4.0.0 but none was installed.
npm WARN ng2-tag-input@1.3.3 requires a peer of @angular/forms@^4.0.0 but none was installed.

**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**
Shows warning on installation on angular2

**Expected behavior**
Install on Angular2

**Minimal reproduction of the problem with instructions (if applicable)**

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
Angular-cli

**Angular version:** 
angular2

**ng2-tag-input version:**
1.3.3

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]
osx terminal

**Comment by Gbuomprisco** [comment]
Hi, the error "ng2-tag-input@1.3.3 requires a peer of @^4.0.0 but none was installed" means exactly what it says: you need to upgrade your angular version in order to use this component.

**Comment by raghles** [comment]
Okay.. Can you please add Prerequisites column in README.md?
