### ISSUE TITLE
Duplicate check ignores transformation value

### ISSUE THREAD

**Issue by tonysparks** [Gbuomprisco/ng2-tag-input#448]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

When you have `allowDupes = false` and a `transform` defined, you are able to add duplicate items.

**Expected behavior**

Duplicates should be detected based off of the `transform` function -- which should not allow duplicate items.

The `findDupe` function should transform the `tag.value` (or it should be transformed sometime before hand.

[Code](https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/tag-input/tag-input.ts#L1033) in question.

**Minimal reproduction of the problem with instructions (if applicable)**

```typescript
    public transformer(text: string) : string {
        return text + "Test";
    }
```
```html
<tag-input               
        [(ngModel)]="promptItems"            
        [blinkIfDupe]="true"          
        [allowDupes]="false"
        [transform]="transformer"      
        #input                      
        >
    </tag-input>
```

**What is the motivation / use case for changing the behavior? (if applicable)**

To not allow duplicate items.

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

```
"@angular/cli": "^1.0.3",
"@angular/compiler-cli": "^4.1.2",
"@angular/core": "^4.1.2",
```

**Angular version:** 

```
"@angular/core": "^4.1.2",
```

**ng2-tag-input version:**

```
"ng2-tag-input": "1.3.3",
```

**Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

all

**Comment by tonysparks** [comment]
You can work around this bug by:

```typescript
    public onAdding(tag : any) : Observable<any> {        
        tag.value = tag.value + "Test"; // use your transform function here
        
        return Observable.of(undefined)                         
                         .mapTo(tag);
    }
```
```html
<tag-input               
        [(ngModel)]="promptItems"            
        [blinkIfDupe]="true"          
        [allowDupes]="false"
        [transform]="transformer"      
        [onAdding]="onAdding"
        #input                      
        >
    </tag-input>
```

**Comment by Gbuomprisco** [comment]
Hi @tonysparks,

thanks for this. I deprecated `transform` and your workaround is now the recommended way

**Comment by gitalvininfo** [comment]
@tonysparks thanks for this. Actually it transform the first letter of the string to uppercase.

However when I select the tags from the tag-input-dropdown, it does not add the selected tag.

This is my view

`<div class="tagInput-container">
	<tag-input (onRemove)="RemoveTags($event)" [modelAsStrings]="true" [validators]="validators"
		[errorMessages]="errorMessage" (onAdd)="onTagsAdded($event)" [onTextChangeDebounce]="50" [maxItems]='3'
		separatorKeyCodes='[{9, 32}]' [secondaryPlaceholder]="'Enter your indicated tags...'"
		[placeholder]="'Enter your indicated tags...'" [(ngModel)]="InputTags" [identifyBy]="'value'"
		[displayBy]="'display'" [addOnBlur]="true">
		<tag-input-dropdown [appendToBody]="false" [showDropdownIfEmpty]="true" [autocompleteItems]="UserTags"
			[identifyBy]="'value'" [displayBy]="'display'" [dynamicUpdate]="true" [keepOpen]="false">
		</tag-input-dropdown>
	</tag-input>
</div>`



This is my component.ts

`public transform(value: string): Observable<object> {
		const item = { display: `${value.charAt(0).toUpperCase() + value.slice(1)}`, value: `${value.charAt(0).toUpperCase() + value.slice(1)}` };
		return of(item);
	}`



Please tell if I made mistake here. Thanks
