### ISSUE TITLE
Dragged tags shows incorrect text

### ISSUE THREAD

**Issue by altschuler** [Gbuomprisco/ng2-tag-input#449]
**I'm submitting a ...**  (check one with "x")
```
[X] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```
**Current behavior**
When dragging tags, the dragged tag is being shown as the incorrect one. Eg. if you drag "Foo" the dragged tag will show "Bar", but when you drop it, it actually moved "Foo". It seems that the dragged one always has the text of the tag to the right of the selected one, except when dragging the last tag in a list in which case it shows the correct tag.

**Expected behavior**
The dragged tag should always show the correct text.

**Minimal reproduction of the problem with instructions (if applicable)**
The issue is reproducible by dragging the "C#" tag under "Drag and drop" on the demo site: http://www.buompris.co/ng2-tag-input. The dragged tag will show as "Java" and not "C#" as expected.

**What do you use to build your app:** angular-cli 1.1.1 (webpack)
**Angular version:**  4.1.3
**ng2-tag-input version:** 1.3.3
**Browser:** Tested in Chrome and Firefox on Linux

**Comment by micheledicosmo** [comment]
Just cloned and played a bit with it. Can reproduce. See following examples:

# Case 1
Initial
- Have the tags: a, b, c, d, e, f
Repro:
- Start dragging f
- Drop f in first position
Expected:
- f disappears
- f is being dragged
- f appears in first position
Actual:
- f disappears :heavy_check_mark: 
- f is being dragged :heavy_check_mark: 
- f appears in first position :heavy_check_mark: 

# Case 2
Initial
- have the tags: a, b, c, d, e, f
Repro:
- Start dragging e
- Drop e in first position
Expected:
- e disappears
- e is being dragged
- e appears in first position:
Actual:
- e disappears :heavy_check_mark: 
- f is being dragged :heavy_multiplication_x: 
- e appears in first position :heavy_check_mark: 
(This happens with all the letters but the last one, case 1)

**Comment by Gbuomprisco** [comment]
A recent PR caused this :( The fix is not super-straightforward so I'll have to find a decent way

**Comment by Gbuomprisco** [comment]
WiIl be fixed by https://github.com/Gbuomprisco/ng2-tag-input/pull/462

**Comment by altschuler** [comment]
Wonderful! Thank you very much!

**Comment by Gbuomprisco** [comment]
v.1.3.8 released - dragging should work better!

**Comment by altschuler** [comment]
Works beautifully! Another improvement would be "live" updating the positions of each tag, but that's for another day/issue :) Thank you!
