### ISSUE TITLE
Async validators prevent tags from being added

### ISSUE THREAD

**Issue by ahushh** [Gbuomprisco/ng2-tag-input#454]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

If I add an async validator that always resolves to null, tags won't be added by pressing enter. They just disappear like not passing the validation.

**Expected behavior**

**Minimal reproduction of the problem with instructions (if applicable)**

Code:
```
import { Component } from '@angular/core';
import {FormControl} from '@angular/forms'

@Component({
  selector: 'app-inbox',
  templateUrl: './inbox.component.html',
})
export class InboxComponent {
  emails = []
  async = []
  constructor() {
    const emailAvaliable = (control: FormControl) => {
      return new Promise(resolve => {
        return resolve(null)
      })
    }
    this.async = [emailAvaliable]
  }
}
```
Markup:
`<tag-input [(ngModel)]="emails" [asyncValidators]="async"></tag-input>
`

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**
**Angular version:** 

```
@angular/cli: 1.1.0
node: 6.10.3
os: linux x64
@angular/animations: 4.2.3
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.1.0
@angular/compiler-cli: 4.1.3
```

**ng2-tag-input version:**

1.3.5

**Browser:** all

**Comment by tartexs** [comment]
i have the same problem here, sync validator works well, but async validators doesn't add tags

**Comment by Gbuomprisco** [comment]
Seems due to https://github.com/angular/angular/issues/13200

**Comment by Gbuomprisco** [comment]
To be fixed in https://github.com/Gbuomprisco/ng2-tag-input/pull/461/files

**Comment by Gbuomprisco** [comment]
Hi @ahushh and @ahushh,

would you be able to check v1.3.6? thanks

**Comment by ahushh** [comment]
Works fine. Thanks!
