### ISSUE TITLE
seems showDropdownIfEmpty doesn't work with autocompleteObservable

### ISSUE THREAD

**Issue by gen4sp** [Gbuomprisco/ng2-tag-input#455]
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => search github for a similar issue or PR before submitting
[ ] feature request
[ ] support request/question
```

**Current behavior**

It doesn't  show dropdown (doesn't fire autocompleteObservable function) right after I focus on input.

**Expected behavior**

If showDropdownIfEmpty == true it should show dropdown right after focus to show all possible items.

**Minimal reproduction of the problem with instructions (if applicable)**

Just use showDropdownIfEmpty and autocompleteObservable in one time
```
<tag-input [(ngModel)]="data.category"
                   [placeholder]="'Add a category'"
                   [secondaryPlaceholder]="'Add a category'"
                   [onlyFromAutocomplete]="true">

            <tag-input-dropdown [showDropdownIfEmpty]="true"
                                [appendToBody]="true"
                                [autocompleteObservable]='requestAutocompleteCategory'>
            </tag-input-dropdown>
        </tag-input>
```

**What is the motivation / use case for changing the behavior? (if applicable)**

**What do you use to build your app? (SystemJS, Webpack, angular-cli, etc.). Please specify the version**

angular-cli

**Angular version:** 

4

**ng2-tag-input version:**

```
"ng2-tag-input": "1.2.8",
```

**Browser:** 
Chrome 58.0.3029.110 (64-bit) and Safari Version 10.1.1 (12603.2.4) at least

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/461

**Comment by Gbuomprisco** [comment]
Hi @gen4sp,

thanks for reporting. would you be able to check v1.3.6? thanks

**Comment by gen4sp** [comment]
there is no such version at npm 
```
npm ERR! notarget No compatible version found: ng2-tag-input@1.3.6
npm ERR! notarget Valid install targets:
npm ERR! notarget 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9, 0.3.0, 0.3.1, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.5, 0.4.6, 0.4.7, 0.4.8, 0.4.9, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5, 0.7.6, 0.7.7, 0.7.8, 0.7.9, 0.8.0, 0.8.1, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.1.5-beta.0, 1.1.7, 1.1.8, 1.1.9, 1.2.0, 1.2.1-beta.0, 1.2.1-beta.1, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.2.8, 1.2.9, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5
```

**Comment by Gbuomprisco** [comment]
sorry the publish had failed - should be up now :)

**Comment by gen4sp** [comment]
`ERROR in TagInputModule is not an NgModule`
now. any crucial changes with import?

**Comment by Gbuomprisco** [comment]
no nothing new - i'm investigating

**Comment by Gbuomprisco** [comment]
For some reason node_modules got i the dist folder. can you try with 1.3.7? Thanks

**Comment by gen4sp** [comment]
Thanks for your fixes, but it still doesn't work as expected. 
Now it works, but only(!) after some search done. 
So if I focus on the input  it doesn't make a request. It just shows some items it already has.

**Comment by Gbuomprisco** [comment]
I applied some changes to this in v.1.3.8, my tests were OK, hopefully I haven't missed anything

**Comment by gen4sp** [comment]
Yey! It works fine now. 
thank you very much! <3

**Comment by Gbuomprisco** [comment]
Great!

**Comment by anil-agrawal** [comment]
Update module declaration file ng-input.module.d.ts as below

import { Options } from './core';
import { NgModule } from '';
@NgModule() export declare class TagInputModule {
static withDefaults(options: Options): void;
}

**Comment by Gbuomprisco** [comment]
@anil-agrawal declarations are not for user's consumption, you should never having to change them

**Comment by paninee** [comment]
Can you provide a sample snippet of code? Mine is not working. Version is ^2.0.0-beta.0

**Comment by paninee** [comment]
> Yey! It works fine now.
> thank you very much! <3

Can you provide a sample snippet of code? Mine is not working. Version is ^2.0.0-beta.0
