### ISSUE TITLE
focus loss addition

### ISSUE THREAD

**Issue by FallenRiteMonk** [Gbuomprisco/ng2-tag-input#46]
Hy,

would it be possible to add the current input to the tags if the input looses focus?
Example:
If I go to the life demo, select the first tag input and start typing, then (without clicking enter) use the mouse to jump to the second tag input, the tag I entered into the first is not added to the tag list.

I don't know if this is intended, but I think this should be changed, because then one could tab to the next form field without having to hit enter.

Thanks and Greetings

**Comment by Gbuomprisco** [comment]
Hi @FallenRiteMonk!

In general I follow the same behaviour as https://material.angularjs.org/latest/demo/chips, so yes it is intended that the chip is not added. If you want to add <tab> as a key to add new tags, you could add it to the separatorKeys array (see API) and then press tab again to jump to the next input. 

Does it make sense? Thanks for the suggestion :)

**Comment by FallenRiteMonk** [comment]
It partly makes sens yes! I understand that I could add the tabulator to the separatorKeys array, buth what if one uses the mouse to navigate around?

**Comment by Gbuomprisco** [comment]
I think it's how most similar inputs work and probably how most people would expect it to work :) 

What I can do is to add output events to the input-tag - onBlur and onFocus, which return the current value of the input. In this way, you can subscribe to the event and push the value of the input to the model. I had already thought of these events which can be useful in many ways.

**Comment by danieltorrer** [comment]
@FallenRiteMonk @Gbuomprisco How did you guys solved this? I guess I need to use the blur event but how do I push the values to my model?
