### ISSUE TITLE
Error when built AOT

### ISSUE THREAD

**Issue by KeitaElric** [Gbuomprisco/ng2-tag-input#465]
I installed version 1.3.8 when build aot, I get error below.
Pls check it 😃 
```
[at-loader] Checking finished with 2 errors
Error in bail mode: [at-loader] ./compiled/node_modules/ng2-tag-input/dist/modules/components/tag-input/tag-input.ngfactory.ts:526:50 
    TS2341: Property 'dragProvider' is private and only accessible within class 'TagInputComponent'.
```

**Comment by limpep** [comment]
Getting the same issue.

**Comment by Gbuomprisco** [comment]
HI, can you try v.1.3.9?

**Comment by limpep** [comment]
@Gbuomprisco got the following error 
```
ERROR in Unexpected value 'TagInputModule in /node_modules/ng2-tag-input/dist/modules/tag-input.module.d.ts' imported by the module 'AppModule in /src/app/app.module.ts'. Please add a @NgModule annotation.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/src'
 @ ./src/main.ts 3:0-74
 @ multi ./src/main.ts
```

**Comment by Gbuomprisco** [comment]
right - releasing a fix

**Comment by Gbuomprisco** [comment]
1.4.0 should be OK, at least it is for me :)

**Comment by limpep** [comment]
Yeah just tested on 1.4.0 and its working fine for me.

**Comment by FriOne** [comment]
@Gbuomprisco now it works with 1.4.0 but doesn't with higher versions

**Comment by Gbuomprisco** [comment]
Hi @FriOne can you share your stacktrace?

**Comment by Gbuomprisco** [comment]
Hi @FriOne,

try v 1.2.5-beta and make sure you install @angular/animations >= 4.2.0

**Comment by FriOne** [comment]
@Gbuomprisco I use 'ng2-tag-input', 1.4.0 works fine with angular 4.2.5.
The stacktrace is simple :)

> ERROR in Unexpected value 'TagInputModule in D:/Projects/xerox/node_modules/ng2-tag-input/dist/modules/tag-input.module.d.ts' imported by the module 'AppModule in D:/Projects/xerox/src/app/app.module.ts'. Please add a @NgModule annotation.
> 
> ERROR in ./src/main.ts
> Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in 'D:\Projects\xerox\src'
>  @ ./src/main.ts 5:0-74
>  @ multi ./src/main.ts

**Comment by Gbuomprisco** [comment]
Use ngx-chips, ng2-tag-input is now deprecated

**Comment by FriOne** [comment]
@Gbuomprisco It hadn't worked until 1.4.5 of ngx-chips, now it works, thanks.
