### ISSUE TITLE
Add an option to specify dropdown placement

### ISSUE THREAD

**Issue by cyrilrbt** [Gbuomprisco/ng2-tag-input#47]
I have a TagInput at the bottom of my page, which means the dropdown for autocomplete is mostly hidden, I can only see the top row. It would be great to have an option to choose its placement.

Temporary solution is to move it in an AfterViewChecked callback, which is not great.

**Comment by Gbuomprisco** [comment]
Hi @cyrilrbt. I need to update another package (https://github.com/Gbuomprisco/ng2-material-dropdown), so I opened an issue in there.

I guess the right way to fix it is to detect the position of the input in the page and move the dropdown to the top of the input in this case. Would that work for you?

Cheers

**Comment by cyrilrbt** [comment]
Yeah, if you could do it automatically, that would be even better. Essentially if it's not entirely in view, it should be moved to the opposite side.

**Comment by Gbuomprisco** [comment]
Hi @cyrilrbt, sorry for resolving this so late, but the new version should allow the behaviour you mentioned :) It's not perfect yet, but the dropdown will at least show up in the screen

**Comment by cyrilrbt** [comment]
Thanks!
