### ISSUE TITLE
invalid message

### ISSUE THREAD

**Issue by FallenRiteMonk** [Gbuomprisco/ng2-tag-input#50]
Is it somehow possible to display a error message if the entered tag is not valid?

Like for example in the demo with the custom validator show a message that a tag must start with a @ if the users enters a tag that doesn't.

Or can I access the form validation status somehow to show/hide a message accordingly?

Thanks

**Comment by Gbuomprisco** [comment]
Hi @FallenRiteMonk!

Yeah I like that, will surely look at it.

**Comment by Gbuomprisco** [comment]
https://github.com/Gbuomprisco/ng2-tag-input/pull/53

**Comment by Gbuomprisco** [comment]
1 error:

![screen shot 2016-09-08 at 19 19 02 2](https://cloud.githubusercontent.com/assets/3512197/18361392/857f5ca6-75f9-11e6-985b-4e0b23b906e8.png)

2 errors:

![screen shot 2016-09-08 at 19 19 06 2](https://cloud.githubusercontent.com/assets/3512197/18361393/8594b02e-75f9-11e6-8017-90d7e5fd483c.png)

**Comment by Gbuomprisco** [comment]
I released a new version with these updates. Hopefully it's how you wanted it :)

**Comment by FallenRiteMonk** [comment]
looks great thanks! I'll implement it as soon as possible thanks!

**Comment by FallenRiteMonk** [comment]
Works great thanks!
