### ISSUE TITLE
Broken minification with UglifyJS

### ISSUE THREAD

**Issue by mlessio** [Gbuomprisco/ng2-tag-input#52]
Hi, @Gbuomprisco !

With the new RC.6 the minification for production enviroments is broken.
If i try to run UglifyJS on my sources with webpack, it gives me: 
`
ERROR in app.js from UglifyJs
SyntaxError: Unexpected token punc «,», expected punc «:» [./~/ng2-tag-input/dist/ng2-tag-input.bundle.js:543,0]
`

I think it is due to the fact that the bundles are not compiled in commonjs.

**Comment by Gbuomprisco** [comment]
Hi @mlessio, thanks, I'll have a look!

**Comment by mlessio** [comment]
@Gbuomprisco i don't think it is related to this issue. It was preventing to import modules in RC.5, but it is now solved in RC.6.

I have also tried to compile your module in commonjs modifying the webpack configuration but the issue is still here.

It may be related to the import of Ng2Dropdown and its related libraries?

Because the error is in this chunk of code: 
`
	module.exports = {
	    Ng2Dropdown,
	    Ng2DropdownMenu,
	    Ng2DropdownButton,
	    Ng2MenuItem,
	    Ng2DropdownModule
	};
`
It expects something slightly different, and if i modify it like this, it passes the minification with uglifyjs:
`
	module.exports = [
	    Ng2Dropdown,
	    Ng2DropdownMenu,
	    Ng2DropdownButton,
	    Ng2MenuItem,
	    Ng2DropdownModule
	];
`
but then it fails at runtime because all those objects are undefined.
Is it necessary to import this library for the tag input?

**Comment by Gbuomprisco** [comment]
I see. Unfortunately that package is used by the autocomplete function. I'll try to fix it this evening :) in the meantime you can try to stick with the previous version if that works for you?
Cheers, Giancarlo

**Comment by mlessio** [comment]
The previous version is not working under RC.6, and unfortunately i have already migrated my whole project to RC.6 specs.

I have forked your repo and i have dropped the Ng2Dropdown component since i am not using the autocomplete, and i can now tell that this module is the problem.
Without it the tag-input works like a charm, so i'll wait until you fix it, by now i can use my modified version of the library.

Cheers! M

**Comment by Gbuomprisco** [comment]
Yeah that's great :) 👍

**Comment by eromero90** [comment]
Hello @Gbuomprisco!

I'm experiencing the same error. Is there a solution for that error?

Thanks!

**Comment by Gbuomprisco** [comment]
Released a new version, hopefully it works! I tried with angular-seed minified and it seemed to be OK.

**Comment by eromero90** [comment]
@Gbuomprisco I'm going to try building my app again and I'll let you know if the new solution works. Thanks!

**Comment by eromero90** [comment]
Hi @Gbuomprisco, It's working for me now, thanks!

**Comment by Gbuomprisco** [comment]
Awesome :)

**Comment by mlessio** [comment]
@Gbuomprisco It works! Great! 👍
