### ISSUE TITLE
Update Webpack Bin Demo to latest version

### ISSUE THREAD

**Issue by Gbuomprisco** [Gbuomprisco/ng2-tag-input#55]

**Comment by FallenRiteMonk** [comment]
How would that be done?
I mean I can edit the example on webpackbin and see the changes, but will everybody else also see all those changes? will they persist? or can I somehow propose a submit to you that you can then accept?

**Comment by Gbuomprisco** [comment]
Unfortunately it's not possible to propose changes, but when you change something and then you save your "bin", it will create a new persistent URL that you can share. So the old example will remain intact. :)

**Comment by FallenRiteMonk** [comment]
Here is the new version:
http://www.webpackbin.com/4kF45Fio-

The only thing that you have to fix is the last example. The validation of the minimum amount of tags doesn't work!

**Comment by Gbuomprisco** [comment]
HI @FallenRiteMonk, thanks for this!

I update the example for the form http://www.webpackbin.com/VyLKAtssb, will update the readme now. Unfortunately it seems the template is not working... :)

**Comment by FallenRiteMonk** [comment]
No problem, after all the quick replies, fixes and features you made!
