### ISSUE TITLE
make the borders optional

### ISSUE THREAD

**Issue by ckemmler** [Gbuomprisco/ng2-tag-input#57]
This is purely a styling issue. I can't think of a way that I can override the css styling on the component to remove the input borders that IMO make it unnecessary big. Besides, in my app, the close buttons appear slightly misplaced (http://pasteboard.co/2YSDQYkK1.png) which I suspect is due to some interaction with my own stylesheet. Problem is, short of forking the entire component, I don't know how to fix it.

Just making the borders optional would be great for now. But Angular 2 really needs a to figure out an unintrusive way to override the style of reusable components.

**Comment by Gbuomprisco** [comment]
HI @ckemmler, are the tags too big or the input (the padding between the tags and the input maybe)?

**Comment by Gbuomprisco** [comment]
Should be done in 0.3.5 with the new themes (or open a PR for a new nicer theme) :)
