### ISSUE TITLE
Cannot find name 'require'. in index.ts

### ISSUE THREAD

**Issue by hmtai6** [Gbuomprisco/ng2-tag-input#64]
Thank you, the project is excellent.

I encounter a problem during compilation.  

[default] /client/node_modules/ng2-tag-input/index.ts:1:20 
    Cannot find name 'require'.
[default] Checking finished with 1 errors

Is there anything i miss in my node modules ?

**Comment by Gbuomprisco** [comment]
Hi @hmtai6, thanks!

It seems related to the typings settings. Can you post here your the deps and dev-deps n your package.json? I'll check out the versions.

**Comment by hmtai6** [comment]
The following is my package.json, thank you 

{
  "name": "client",
  "version": "0.0.0",
  "license": "MIT",
  "angular-cli": {},
  "scripts": {
    "start": "ng serve",
    "lint": "tslint \"src/**/*.ts\"",
    "test": "ng test",
    "pree2e": "webdriver-manager update",
    "e2e": "protractor",
    "build.prod": "ng build --base-href /admin/   --target=production ",
    "build.dev": "ng build --base-href /admin/   --target=development ",
    "serve": "ng serve --live-reload-base-url /admin"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "2.0.0",
    "@angular/compiler": "^2.0.0",
    "@angular/compiler-cli": "^0.6.3",
    "@angular/core": "2.0.0",
    "@angular/forms": "2.0.0",
    "@angular/http": "^2.0.0",
    "@angular/platform-browser": "2.0.0",
    "@angular/platform-browser-dynamic": "2.0.0",
    "@angular/platform-server": "^2.0.1",
    "@angular/router": "3.0.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.0-alpha.5",
    "@types/jquery": "^2.0.32",
    "@types/select2": "^4.0.30",
    "bootstrap": "^4.0.0-alpha.4",
    "font-awesome": "4.6.3",
    "highcharts": "4.2.5",
    "jquery": "3.0.0",
    "moment": "2.14.1",
    "ng2-bootstrap": "^1.1.5",
    "ng2-tag-input": "^0.3.4",
    "reflect-metadata": "0.1.8",
    "rxjs": "5.0.0-beta.11",
    "select2": "^4.0.3",
    "socket.io-client": "^1.4.8",
    "systemjs": "0.19.27",
    "ts-helpers": "^1.1.1",
    "zone.js": "^0.6.23"
  },
  "devDependencies": {
    "@types/jasmine": "^2.2.30",
    "@types/socket.io-client": "^1.4.27",
    "angular-cli": "1.0.0-beta.15",
    "codelyzer": "~0.0.26",
    "jasmine-core": "2.4.1",
    "jasmine-spec-reporter": "2.5.0",
    "karma": "1.2.0",
    "karma-chrome-launcher": "^2.0.0",
    "karma-cli": "^1.0.1",
    "karma-jasmine": "^1.0.2",
    "karma-remap-istanbul": "^0.2.1",
    "protractor": "4.0.5",
    "ts-node": "1.2.1",
    "tslint": "3.13.0",
    "typescript": "2.0.2"
  }
}

**Comment by Gbuomprisco** [comment]
Hi @hmtai6, can you try with version 0.3.6?

**Comment by hmtai6** [comment]
@Gbuomprisco  Thank you so much !!! <3<3
