### ISSUE TITLE
Error with angular-cli and AoT

### ISSUE THREAD

**Issue by FallenRiteMonk** [Gbuomprisco/ng2-tag-input#65]
I get the following error when i try to build/serve my project using angular-cli beta 16 and ng2-tag-input module version 0.3.4 with the --aot option:

```
Error encountered resolving symbol values statically. Calling function 'require', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol TagInputModule in <PROJECT_PATH>/node_modules/ng2-tag-input/index.ts, resolving symbol <MODULE_NAME> in <MODULE_TS_FILE_PATH>, resolving symbol <MODULE_NAME> in <MODULE_TS_FILE_PATH>
```

**Comment by Gbuomprisco** [comment]
Hi @FallenRiteMonk, can you try with the version 0.3.6? let me know :)

**Comment by FallenRiteMonk** [comment]
fixed the problem thanks!

**Comment by FallenRiteMonk** [comment]
I still cant test if it completely works due to some other problems i have, but i found this! maybe have a look at it:
https://medium.com/@isaacplmann/getting-your-angular-2-library-ready-for-aot-90d1347bcad#.t901jn4lz

**Comment by soyersoyer** [comment]
With the same circumstances, I get this error message:
Error: Unexpected value 'TagInputModule' imported by the module 'SharedModule'

**Comment by FallenRiteMonk** [comment]
Just updated to the new version of angular-cli (beta.20-4) in the hope to be finally able to use aot, but i get the exact same error:
Error: Unexpected value 'TagInputModule' imported by the module 'MODULE_NAME'

**Comment by DODMax** [comment]
According to [this thread](https://github.com/gevgeny/angular2-highcharts/issues/75) the package would need to be compiled by ngc first in order to generate a required ` index.metadata.json ` file.

**Comment by Gbuomprisco** [comment]
Hi,

the library should be working with AOT now. Please reopen if still an issue (and sorry for the huge delay, I just found some time as am on holidays)
