### ISSUE TITLE
How to pass an array of object to autocomplete and specify the property to display?

### ISSUE THREAD

**Issue by dverbovyi** [Gbuomprisco/ng2-tag-input#68]
Hi, 

Thank you for your hard work. The component is very nice and simply.

But I faced with the next requirement on my project to pass an array of object inside of [autocompleteItems] and specify a property to display/search like this:

`<tag-input
    [onlyFromAutocomplete]="true"
    [autocompleteItems]="[{name: 'Item1', id: 1}, {name: 'Item2', id: 2}]" 
    [autocompleteDisplayProperty]="'name'" // display property name
    [autocomplete]="true"
    [ngModel]="tags">
</tag-input>`

Do you have similar features?

Regards, 
Dmytro

**Comment by Gbuomprisco** [comment]
Hi @dverbovyi, unfortunately that is not possible. 

Unless you need to search by the id value, you could though map the array and only pass the names to the component?

Ex 
```javascript

public get myValues(): string[] {
   return this.myArray.map(item => item.name);
}

```

**Comment by dverbovyi** [comment]
I know have to grab and pass the names. Actually, it's not what I need.

I need to catch id of item inside of `(onAdd)="onAdd($event)"`. Not the string only

**Comment by Gbuomprisco** [comment]
I see, unfortunately at the moment is not supported, but I guess I'll get on it at some point cause I see the need 👍

**Comment by anvesh48** [comment]
@dverbovyi 
I have the similar requirement to display the label name from the object instead of array of strings. Have you found a way to do that.Or do you found a better solution for it?

**Comment by Gbuomprisco** [comment]
Hi @dverbovyi and @anvesh48,

the latest version should make this possible :)

**Comment by anvesh48** [comment]
Wow good news..! 
Thank you so much..!
