### ISSUE TITLE
Provide own getMatchingItems

### ISSUE THREAD

**Issue by wolfgang-lausenhammer** [Gbuomprisco/ng2-tag-input#70]
Hey,

I was looking at ng2-tag-input as a replacement for ng2-select.
Your library seems like the perfect match for us. The only option I'm missing right now is to specify my own getMatchingItems function.
In our use case, we need not only provide beginning of word matching, but also return items that match in the middle of the word (so not really an autocomplete functionality, but more a simple search functionality). Also, we'd like to show the whole list of options, when the input is empty and the user clicks into it.

Hope that makes sense,
Wolfgang

**Comment by Gbuomprisco** [comment]
HI @wolfgang-lausenhammer,

I believe your points make sense in general, so I am adding those behaviours as default for the library. I am not sure it will fully fill your needs, but in case I guess it's possible to add custom matching. 

PR https://github.com/Gbuomprisco/ng2-tag-input/pull/71

**Comment by wolfgang-lausenhammer** [comment]
That's pretty awesome! Exactly what I was looking for. Thanks a lot!
- Wolfgang
