### ISSUE TITLE
CSS conflict

### ISSUE THREAD

**Issue by toxa16** [Gbuomprisco/ng2-tag-input#72]
There are some CSS class names in the component like "tag", which may conflict with external libraries' CSS, e.g. Bootstrap (there is also a "tag" class). Eventually your "tag" class dominates over the Bootstrap's one so it looks pretty disgusting.

I recommend you to edit your CSS class names adding no-conflict prefixes, for example:
```
.n2ti-tag {...}
```
And even better yet, add the possibility to turn off a component theme completely.

**Comment by Gbuomprisco** [comment]
Hi @toxa16,

As far as I know the style should not leak as it uses Shadow DOM emulation. I'll try to reproduce

**Comment by Gbuomprisco** [comment]
I updated the classes and prefixed them with ng2- :)

**Comment by toxa16** [comment]
Alright, you have earned a star from me :)
