### ISSUE TITLE
Failed to npm start

### ISSUE THREAD

**Issue by tmtrung** [Gbuomprisco/ng2-tag-input#73]
I say an error when I execute "npm start":
[1] 16.10.06 00:08:21 404 GET /node_modules/ng2-tag-input/dist/dist/modules/ng2-tag-input.module.js                         
[1] 16.10.06 00:08:21 404 GET /node_modules/ng2-tag-input/dist/dist/modules/components/tag-input.js  

This is my systemjs.config.js

(function(global) {
  // map tells the System loader where to look for things
  var map = {
    'moment': 'node_modules/moment/moment.js',
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs',
    'ng2-tag-input': 'node_modules/ng2-tag-input/dist'
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
    'ng2-tag-input':            { defaultExtension: 'js', main:'index' },
  };

**Comment by Gbuomprisco** [comment]
Hi @tmtrung,

can you try setting the main file like this?
 ```
"main": "./dist/ng2-tag-input.bundle.js"
```

As you can see in the package.json, the main file changed recently :)

**Comment by simoazzo** [comment]
Hi Gbuomprisco,

recently, I have updated ng2-tag-input and nothing is working now.

localhost/:136 Error: TypeError: core_1.NgModule is not a function(…) "Report this error at https://github.com/mgechev/angular2-seed/issues"

Can I get is solved ?

Thank you
