### ISSUE TITLE
Facing issue in loading the index.js file

### ISSUE THREAD

**Issue by sharmilemurugaraj** [Gbuomprisco/ng2-tag-input#76]
Hi,
   I am using 0.3.7 version, I couldnot able to load .js file. Can someone please help me on this?

Thanks in advance

**Comment by Gbuomprisco** [comment]
Hi @sharmilemurugaraj,

Can you post more info on how you're loading the library? Thanks!

**Comment by sharmilemurugaraj** [comment]
Hi @Gbuomprisco ,
    I could able to run the module. Is there any display property, so that only that property can loaded in the autocomplete like in "http://mbenford.github.io/ngTagsInput/documentation/api"

**Comment by Gbuomprisco** [comment]
Hi @sharmilemurugaraj, unfortunately not at the moment. I do want to support objects as model soon :)
