### ISSUE TITLE
Tags with label and value

### ISSUE THREAD

**Issue by erlopezh** [Gbuomprisco/ng2-tag-input#81]
Hi,
Is it possible to have tags with a label and value?
First, selecting autocomplete label:

![captura de pantalla 2016-10-18 a las 17 24 50](https://cloud.githubusercontent.com/assets/16109226/19498751/5c7b3342-9558-11e6-8e9a-d3750298ecfb.png)

Second, the tag creates with "Label:Value"

![captura de pantalla 2016-10-18 a las 17 25 15](https://cloud.githubusercontent.com/assets/16109226/19498754/61d0d1da-9558-11e6-8db3-5df867c8986a.png)

Thanks.

**Comment by Gbuomprisco** [comment]
Hi @erlopezh, sorry, but not at the moment, but I plan on this being possible, has been asked before.

**Comment by Gbuomprisco** [comment]
This should now be possible I guess?
