### ISSUE TITLE
onlyFromAutocomplete doesn't work

### ISSUE THREAD

**Issue by rolandoldengarm** [Gbuomprisco/ng2-tag-input#82]
See example: http://www.webpackbin.com/VkBmiq1yM

When typing in "Ty", selecting Type Script, it doesn't select it.
Doesn't matter what you do, no value is accepted, even though it's a valid choice.

**Comment by Gbuomprisco** [comment]
Hi @rolandoldengarm,

I see that bin is using the version 0.3.0. Any reason for that? Otherwise, I tried using the latest version and it appears to be working :)

Also, use [] for sending the attributes autocomplete and onlyFromAutocomplete :) Let me know!

**Comment by rolandoldengarm** [comment]
Hi @Gbuomprisco I've just used a bin from one of the demos on your site :)
I didn't use [] for onlyFromAutoComplete. That has fixed it. Thanks :)
