### ISSUE TITLE
Autocomplete: Dropdown is always shown

### ISSUE THREAD

**Issue by rolandoldengarm** [Gbuomprisco/ng2-tag-input#83]
Using autocomplete. When I click on the input, the dropdown shows with ALL possible values. 
Debugged the code; I see that it's calling getMatchingItems with an empty string:

![image](https://cloud.githubusercontent.com/assets/14539000/19500309/601ae146-95f8-11e6-8e9e-89499cfda694.png)

Not sure why, but I can't replicate it on webpackbin.

The solution is probably simple: Do an empty string check in getMatchingItems? Happy to submit a PR for that :)

**Comment by Gbuomprisco** [comment]
Hi @rolandoldengarm,

the reason you can't replicate is that webpackbin is using another version, but another user brought this up so I changed it to be like this instead. I understand users have different thoughts on how this should work, so I will probably set an option with a default being the previous behaviour :)

**Comment by rolandoldengarm** [comment]
Ah yeah I used the bin from one of the demos. Thanks! 
Looking forward to the implementation 👍

**Comment by Gbuomprisco** [comment]
Hi @rolandoldengarm,

this should be back to normal now :) If you want the reverse, there's an input
