### ISSUE TITLE
Feature request: Highlighting in auto complete

### ISSUE THREAD

**Issue by rolandoldengarm** [Gbuomprisco/ng2-tag-input#84]
It's required by our project that the autocomplete has highlighting, i.e.: 
- auto complete values: ['Lorem Ipsum', 'Ipsum Lorem']
- When typing in "ipsu", the text "Ipsu" is marked as bold in the drop down.

To be more precise; it's about this line of code: https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/tag-input.template.html#L67
Instead of just displaying the text, it should mark the part of the item that equals the query in bold.

**Comment by Gbuomprisco** [comment]
Hi @rolandoldengarm,

This should now be working with the latest release :)
