### ISSUE TITLE
Feature Request: Populate from HTTP results

### ISSUE THREAD

**Issue by philjones88** [Gbuomprisco/ng2-tag-input#85]
I've searched the docs, demos and issues and strangely no one has requested this that I could see or that it is possible.

Can we provide a method that returns say a bunch of results? Maybe an Observable?

The scenario is that we want a tag input for selecting users, so obviously with a large number of users you don't want to store them client side but do a http request to say `/api/users?term=foo` and get back `Foo Bar` `Foo Foo` etc results.

**Comment by Gbuomprisco** [comment]
Hi @philjones88,

I want to definitely add this feature. 

Given my current workload I may take while: something easy I may do quickly is add an output when the input text changes, so that you can intercept that and send a request to repopulate the autocomplete items. Does that sound sensible?

**Comment by philjones88** [comment]
HI @Gbuomprisco 

I think that could work, as long as changing the autocomplete items array didn't wipe out selected items.

**Comment by philjones88** [comment]
Hi @Gbuomprisco would you be happy to accept a PR with this feature?

I was thinking just another `@Output` and `EventEmitter` plus updating the demo/documentation is what is required?

**Comment by Gbuomprisco** [comment]
Hi @philjones88, 

sure, it would great :)

That should be all I guess!

**Comment by Gbuomprisco** [comment]
HI @philjones88,

This should be in the latest version now. Feel free to open a PR if you want to change something!
