### ISSUE TITLE
Custom templates not working?

### ISSUE THREAD

**Issue by jonwilkinson** [Gbuomprisco/ng2-tag-input#87]
I cant seem to get a custom template to work (currently using v0.3.7). 
My template is never being detected and I always get the default one.
I noticed the "custom template" example on the demo page is actually using the default template too.

**Comment by Gbuomprisco** [comment]
Hi @jonwilkinson!

you're right, something changed in the latest Angular versions and it's not working anymore. I'll look into this

**Comment by Gbuomprisco** [comment]
Hi @jonwilkinson,

Can you download the new version and check the example at http://www.webpackbin.com/NJy38G8kM?

I think you should see this working now :)
