### ISSUE TITLE
Add property to specify id on <input> element 

### ISSUE THREAD

**Issue by ZhangYiJiang** [Gbuomprisco/ng2-tag-input#91]
If it's not too much trouble, it would be very useful to be able to link `<label>` tags to the `<input>` tag. We could of course wrap the whole thing inside the `<label>`, but that's not always possible due to constraints with the layout.

**Comment by Gbuomprisco** [comment]
Hi @ZhangYiJiang,

This is now possible with the latest release :) The property is `inputId`.
