### ISSUE TITLE
User can crash autocompleting tag inputs with malformed regex expressions 

### ISSUE THREAD

**Issue by ZhangYiJiang** [Gbuomprisco/ng2-tag-input#94]
At https://github.com/Gbuomprisco/ng2-tag-input/blob/master/modules/components/pipes/highlight.pipe.ts#L12, the code passes user input directly into the `RegExp` constructor. If the user were to input something that causes the resulting regex to be malformed, the constructor will throw an exception, and this will crash the entire application. I have reproduced this issue using the demo tag input using the input value `i(`. 

A temporary fix would be to wrap the constructor in a try-catch block, but a better (and more permanent) solution would be to avoid using regex for this at all, and instead transform both strings to lowercase, then use normal string manipulation code to do the string replacement. The code will be longer, but it is safer.

**Comment by Gbuomprisco** [comment]
Hi @ZhangYiJiang,
thanks for spotting this, I'm releasing a fix :)
