### ISSUE TITLE
Issues selecting elements with Android / iOS

### ISSUE THREAD

**Issue by wolfgang-lausenhammer** [Gbuomprisco/ng2-tag-input#96]
Hi,
I just tested the component with an Android, an iPhone and an iPad and found a problem there.
When selecting items from the dropdown, all three of them show the same weird behavior.
Clicks on item A selects item B and some items cannot at all be selected. This can be reproduced with the current [webpackbin](http://www.webpackbin.com/VkEgHA8xM).

Do you have a clue why this might happen?

Thanks!

**Comment by Gbuomprisco** [comment]
Hi @wolfgang-lausenhammer!

To be honest I had never tried it on mobile. I just tried on my Nexus 5, and except the UI not being really ideal for mobile phones, I haven't found weird behaviours, or maybe I haven't tried hard enough :)

I'll have a deeper look asap. The ng2-material-dropdown package has several issues I need to address in overall.

**Comment by wolfgang-lausenhammer** [comment]
I was able to reproduce the issue on my desktop Google Chrome, when I enable "Toggle device toolbar" in the developer console. The browser behaves similar to the phones then. Specifically, this issue only appears, when I open a dropdown, scroll down and select an item.
Also, when the margin to the bottom is too low for the dropdown to appear below the element, so the dropdown would be rendered upwards instead of downwards, different items (if any) get selected.

I think I finally have a fix for this, though :-) --> will be coming soon in a pull request.

Btw. this issue also appears on a desktop browser, since the position hasn't been updated during scroll events.

**Comment by Gbuomprisco** [comment]
Hi @wolfgang-lausenhammer,

Thanks a lot for the PR! It's really helpful.

I just published a version with your fixes for both the components

**Comment by wolfgang-lausenhammer** [comment]
Well, I think I created a bug, while closing another :-/
`this.button` is undefined, when used in ng2-tag-input. I haven't tested the interaction of the two components. I'll have a look at that in a second.
