### ISSUE TITLE
Overriding default styles

### ISSUE THREAD

**Issue by manilsson** [Gbuomprisco/ng2-tag-input#99]
Hi!

I'm having problem with styling the default styles of the tag-input. The biggest problem is that all the Css styles are inlined in <styles></style> tag wich means I have to override all of my own style changes with !important.

Currently I use the "minimal" theme, but it would be nice with a theme that doesn't contain any Css rules at all.

/Kind regards
Markus

**Comment by aslubsky** [comment]
+1
Or just put all styles into some root class. As example class `caret` make broken bootstrap `catet`

**Comment by okachynskyy** [comment]
+1
I also have issue with bootstrap `caret`.

**Comment by Gbuomprisco** [comment]
Nice suggestion. Does anyone know the best way to do this with A2? It was my intention from the beginning but I still am to find a nice solution for this

**Comment by Gbuomprisco** [comment]
Hi! This should be possible with the latest release :) Reopen if you have any issues
